export const fields = [
  {
    "field_name": "id",
    "field_label": "ID",
    "field_type": "auto_increment",
    "field_length": "11",
    "is_required": "true",
    "is_unique": "true",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Primary Key"
  },
  {
    "field_name": "layanan_id",
    "field_label": "Layanan",
    "field_type": "varchar",
    "field_length": "10",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "FK ke layanan_menpanrb (LY177-LY190)"
  },
  {
    "field_name": "jenis_layanan_inspeksi",
    "field_label": "Jenis Layanan",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Inspeksi Lapangan,Audit Sertifikasi,Audit Ulang,Pengambilan Sampel,Pengujian Mutu,Verifikasi Hasil Uji,Rekomendasi Pengawasan,Pembinaan,Koordinasi OPD,Monitoring Perbaikan,Penjadwalan,Pelaksanaan Lapangan,Pelaporan Teknis,Data Layanan",
    "help_text": "Jenis layanan inspeksi"
  },
  {
    "field_name": "nomor_inspeksi",
    "field_label": "Nomor Inspeksi",
    "field_type": "varchar",
    "field_length": "100",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Nomor registrasi inspeksi"
  },
  {
    "field_name": "nomor_audit_ins",
    "field_label": "Nomor Audit",
    "field_type": "varchar",
    "field_length": "100",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Nomor audit sertifikasi"
  },
  {
    "field_name": "tanggal_inspeksi",
    "field_label": "Tanggal Inspeksi",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tanggal inspeksi dilakukan"
  },
  {
    "field_name": "lokasi_inspeksi",
    "field_label": "Lokasi Inspeksi",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Lokasi inspeksi"
  },
  {
    "field_name": "objek_inspeksi",
    "field_label": "Objek Inspeksi",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Apa yang diinspeksi (UMKM pasar rumah makan dll)"
  },
  {
    "field_name": "nama_usaha_inspeksi",
    "field_label": "Nama Usaha",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Nama usaha yang diinspeksi"
  },
  {
    "field_name": "pemilik_usaha_inspeksi",
    "field_label": "Pemilik",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Nama pemilik"
  },
  {
    "field_name": "alamat_inspeksi",
    "field_label": "Alamat",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Alamat lokasi inspeksi"
  },
  {
    "field_name": "tim_inspeksi",
    "field_label": "Tim Inspeksi",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Nama-nama tim inspeksi"
  },
  {
    "field_name": "jenis_sertifikasi_audit",
    "field_label": "Jenis Sertifikasi",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "GMP,GHP,NKV,Prima 1,Prima 2,Prima 3,GFP,HACCP,Lainnya",
    "help_text": "Jenis sertifikasi yang diaudit"
  },
  {
    "field_name": "audit_awal_ulang",
    "field_label": "Audit",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "Awal",
    "validation": "none",
    "dropdown_options": "Awal,Ulang,Surveillance",
    "help_text": "Audit awal atau ulang"
  },
  {
    "field_name": "alasan_audit_ulang",
    "field_label": "Alasan Audit Ulang",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Alasan audit ulang"
  },
  {
    "field_name": "checklist_inspeksi",
    "field_label": "Checklist Inspeksi",
    "field_type": "json",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "JSON checklist inspeksi"
  },
  {
    "field_name": "skor_inspeksi",
    "field_label": "Skor Inspeksi",
    "field_type": "decimal",
    "field_length": "5,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Skor hasil inspeksi"
  },
  {
    "field_name": "hasil_inspeksi",
    "field_label": "Hasil Inspeksi",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Lulus,Tidak Lulus,Lulus Bersyarat",
    "help_text": "Hasil inspeksi"
  },
  {
    "field_name": "temuan_inspeksi",
    "field_label": "Temuan Inspeksi",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Temuan hasil inspeksi"
  },
  {
    "field_name": "catatan_inspeksi",
    "field_label": "Catatan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Catatan inspeksi"
  },
  {
    "field_name": "rekomendasi_inspeksi",
    "field_label": "Rekomendasi",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Rekomendasi tindak lanjut"
  },
  {
    "field_name": "tindakan_korektif_inspeksi",
    "field_label": "Tindakan Korektif",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tindakan perbaikan yang diperlukan"
  },
  {
    "field_name": "batas_waktu_ins",
    "field_label": "Batas Waktu Perbaikan",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Deadline perbaikan"
  },
  {
    "field_name": "jenis_sampel_pangan",
    "field_label": "Jenis Sampel",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Jenis sampel pangan"
  },
  {
    "field_name": "lokasi_pengambilan",
    "field_label": "Lokasi Pengambilan",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Lokasi pengambilan sampel"
  },
  {
    "field_name": "tanggal_sampling",
    "field_label": "Tanggal Sampling",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tanggal pengambilan sampel"
  },
  {
    "field_name": "sampler",
    "field_label": "Sampler",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Nama petugas sampling"
  },
  {
    "field_name": "jumlah_sampel_diambil",
    "field_label": "Jumlah Sampel",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Jumlah sampel yang diambil"
  },
  {
    "field_name": "metode_sampling",
    "field_label": "Metode Sampling",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Metode pengambilan sampel"
  },
  {
    "field_name": "kondisi_sampel",
    "field_label": "Kondisi Sampel",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "Baik",
    "validation": "none",
    "dropdown_options": "Baik,Rusak,Kadaluarsa",
    "help_text": "Kondisi sampel"
  },
  {
    "field_name": "penyimpanan_sampel",
    "field_label": "Penyimpanan",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Cara penyimpanan sampel"
  },
  {
    "field_name": "nomor_sampel",
    "field_label": "Nomor Sampel",
    "field_type": "varchar",
    "field_length": "100",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Nomor identifikasi sampel"
  },
  {
    "field_name": "parameter_pengujian",
    "field_label": "Parameter Pengujian",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Parameter yang diuji"
  },
  {
    "field_name": "metode_pengujian",
    "field_label": "Metode Pengujian",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Metode pengujian"
  },
  {
    "field_name": "analis_pengujian",
    "field_label": "Analis",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Nama analis"
  },
  {
    "field_name": "tanggal_pengujian_mulai",
    "field_label": "Tanggal Pengujian Mulai",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tanggal mulai uji"
  },
  {
    "field_name": "tanggal_pengujian_selesai",
    "field_label": "Tanggal Pengujian Selesai",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tanggal selesai uji"
  },
  {
    "field_name": "hasil_pengujian",
    "field_label": "Hasil Pengujian",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Hasil pengujian"
  },
  {
    "field_name": "kesimpulan_pengujian",
    "field_label": "Kesimpulan",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Memenuhi Syarat,Tidak Memenuhi Syarat",
    "help_text": "Kesimpulan hasil uji"
  },
  {
    "field_name": "tanggal_verifikasi_uji",
    "field_label": "Tanggal Verifikasi",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tanggal verifikasi hasil"
  },
  {
    "field_name": "verifikator_uji",
    "field_label": "Verifikator",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Nama verifikator"
  },
  {
    "field_name": "hasil_verifikasi_uji",
    "field_label": "Hasil Verifikasi",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Approved,Rejected,Need Retest",
    "help_text": "Hasil verifikasi"
  },
  {
    "field_name": "catatan_verifikasi_uji",
    "field_label": "Catatan Verifikasi",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Catatan verifikasi"
  },
  {
    "field_name": "jenis_rekomendasi_pengawasan",
    "field_label": "Jenis Rekomendasi",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Rekomendasi Tindakan,Rekomendasi Sanksi,Rekomendasi Pembinaan,Rekomendasi Pemantauan",
    "help_text": "Jenis rekomendasi"
  },
  {
    "field_name": "isi_rekomendasi_pengawasan",
    "field_label": "Isi Rekomendasi",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Isi rekomendasi pengawasan"
  },
  {
    "field_name": "tindak_lanjut_rekomendasi",
    "field_label": "Tindak Lanjut",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tindak lanjut rekomendasi"
  },
  {
    "field_name": "status_rekomendasi_pengawasan",
    "field_label": "Status",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "Open",
    "validation": "none",
    "dropdown_options": "Open,In Progress,Closed",
    "help_text": "Status rekomendasi"
  },
  {
    "field_name": "jenis_pembinaan",
    "field_label": "Jenis Pembinaan",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Pembinaan Langsung,Bimbingan Teknis,Konsultasi,Pelatihan,Lainnya",
    "help_text": "Jenis pembinaan"
  },
  {
    "field_name": "tanggal_pembinaan",
    "field_label": "Tanggal Pembinaan",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tanggal pembinaan"
  },
  {
    "field_name": "lokasi_pembinaan",
    "field_label": "Lokasi Pembinaan",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Lokasi pembinaan"
  },
  {
    "field_name": "penerima_pembinaan",
    "field_label": "Penerima Pembinaan",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Yang dibina"
  },
  {
    "field_name": "materi_pembinaan",
    "field_label": "Materi Pembinaan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Materi yang diberikan"
  },
  {
    "field_name": "hasil_pembinaan",
    "field_label": "Hasil Pembinaan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Hasil pembinaan"
  },
  {
    "field_name": "opd_dikoordinasikan",
    "field_label": "OPD Dikoordinasikan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "OPD yang dikoordinasikan (Dinkes BPOM dll)"
  },
  {
    "field_name": "tanggal_koordinasi",
    "field_label": "Tanggal Koordinasi",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tanggal rapat koordinasi"
  },
  {
    "field_name": "topik_koordinasi_opd",
    "field_label": "Topik Koordinasi",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Topik rapat"
  },
  {
    "field_name": "hasil_koordinasi_opd",
    "field_label": "Hasil Koordinasi",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Hasil rapat koordinasi"
  },
  {
    "field_name": "tindak_lanjut_koordinasi",
    "field_label": "Tindak Lanjut",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tindak lanjut koordinasi"
  },
  {
    "field_name": "objek_monitoring",
    "field_label": "Objek Monitoring",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Apa yang dimonitoring"
  },
  {
    "field_name": "tanggal_monitoring",
    "field_label": "Tanggal Monitoring",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tanggal monitoring"
  },
  {
    "field_name": "hasil_monitoring",
    "field_label": "Hasil Monitoring",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Hasil monitoring perbaikan"
  },
  {
    "field_name": "status_perbaikan_monitoring",
    "field_label": "Status Perbaikan",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Belum,Proses,Selesai,Verified",
    "help_text": "Status perbaikan"
  },
  {
    "field_name": "tanggal_penjadwalan",
    "field_label": "Tanggal Dijadwalkan",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tanggal kegiatan dijadwalkan"
  },
  {
    "field_name": "jenis_kegiatan_jadwal",
    "field_label": "Jenis Kegiatan",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Inspeksi,Audit,Sampling,Pengujian,Pembinaan,Monitoring",
    "help_text": "Jenis kegiatan yang dijadwalkan"
  },
  {
    "field_name": "petugas_dijadwalkan",
    "field_label": "Petugas",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Petugas yang dijadwalkan"
  },
  {
    "field_name": "status_jadwal",
    "field_label": "Status Jadwal",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "Scheduled",
    "validation": "none",
    "dropdown_options": "Scheduled,Ongoing,Completed,Cancelled,Rescheduled",
    "help_text": "Status jadwal"
  },
  {
    "field_name": "jenis_layanan_lapangan",
    "field_label": "Jenis Layanan Lapangan",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Jenis layanan yang dilaksanakan"
  },
  {
    "field_name": "tanggal_pelaksanaan",
    "field_label": "Tanggal Pelaksanaan",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tanggal pelaksanaan"
  },
  {
    "field_name": "lokasi_pelaksanaan",
    "field_label": "Lokasi Pelaksanaan",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Lokasi pelaksanaan"
  },
  {
    "field_name": "tim_pelaksana",
    "field_label": "Tim Pelaksana",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tim yang melaksanakan"
  },
  {
    "field_name": "hasil_pelaksanaan",
    "field_label": "Hasil Pelaksanaan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Hasil pelaksanaan"
  },
  {
    "field_name": "periode_pelaporan_teknis",
    "field_label": "Periode Pelaporan",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Periode laporan teknis"
  },
  {
    "field_name": "jenis_laporan_teknis",
    "field_label": "Jenis Laporan",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Bulanan,Triwulanan,Semesteran,Tahunan",
    "help_text": "Jenis laporan"
  },
  {
    "field_name": "total_inspeksi",
    "field_label": "Total Inspeksi",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Total inspeksi dalam periode"
  },
  {
    "field_name": "total_audit_teknis",
    "field_label": "Total Audit",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Total audit dalam periode"
  },
  {
    "field_name": "total_sampel_diambil",
    "field_label": "Total Sampel",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Total sampel diambil"
  },
  {
    "field_name": "total_pengujian_teknis",
    "field_label": "Total Pengujian",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Total pengujian dilakukan"
  },
  {
    "field_name": "persentase_kelulusan_teknis",
    "field_label": "Persentase Kelulusan (%)",
    "field_type": "decimal",
    "field_length": "5,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Persentase kelulusan"
  },
  {
    "field_name": "temuan_tidak_sesuai",
    "field_label": "Temuan Tidak Sesuai",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Total temuan"
  },
  {
    "field_name": "tindakan_pengawasan",
    "field_label": "Tindakan Pengawasan",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Total tindakan pengawasan"
  },
  {
    "field_name": "pembinaan_dilakukan",
    "field_label": "Pembinaan Dilakukan",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Total pembinaan"
  },
  {
    "field_name": "ringkasan_laporan_teknis",
    "field_label": "Ringkasan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Ringkasan laporan teknis"
  },
  {
    "field_name": "jenis_data_layanan",
    "field_label": "Jenis Data",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Data Inspeksi,Data Audit,Data Sampling,Data Pengujian,Data Sertifikasi,Data Pembinaan,Data Monitoring",
    "help_text": "Jenis data layanan"
  },
  {
    "field_name": "periode_data",
    "field_label": "Periode Data",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Periode data"
  },
  {
    "field_name": "format_data",
    "field_label": "Format Data",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "Excel",
    "validation": "none",
    "dropdown_options": "Excel,PDF,CSV,JSON",
    "help_text": "Format data"
  },
  {
    "field_name": "keterangan_data",
    "field_label": "Keterangan Data",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Keterangan data"
  },
  {
    "field_name": "file_laporan_inspeksi",
    "field_label": "File Laporan Inspeksi",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Upload laporan inspeksi"
  },
  {
    "field_name": "file_laporan_audit_ins",
    "field_label": "File Laporan Audit",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Upload laporan audit"
  },
  {
    "field_name": "file_hasil_pengujian",
    "field_label": "File Hasil Pengujian",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Upload hasil uji"
  },
  {
    "field_name": "file_berita_acara",
    "field_label": "File Berita Acara",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Upload BA sampling/inspeksi"
  },
  {
    "field_name": "file_dokumentasi",
    "field_label": "File Dokumentasi",
    "field_type": "json",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Array foto dokumentasi"
  },
  {
    "field_name": "file_laporan_teknis_ins",
    "field_label": "File Laporan Teknis",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Upload laporan teknis"
  },
  {
    "field_name": "file_data_layanan",
    "field_label": "File Data Layanan",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Upload data layanan"
  },
  {
    "field_name": "rincian_layanan",
    "field_label": "Rincian Layanan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Detail layanan"
  },
  {
    "field_name": "penanggung_jawab",
    "field_label": "Penanggung Jawab",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "Kasi Manajemen Teknis",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "PIC"
  },
  {
    "field_name": "pelaksana",
    "field_label": "Pelaksana",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Yang melaksanakan"
  },
  {
    "field_name": "kelompok_penerima",
    "field_label": "Kelompok Penerima",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "Pelaku Usaha/Masyarakat",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Siapa yang terima"
  },
  {
    "field_name": "jenis_data",
    "field_label": "Jenis Data",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Jenis data"
  },
  {
    "field_name": "is_sensitive",
    "field_label": "Tingkat Sensitivitas",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "Sensitif",
    "validation": "none",
    "dropdown_options": "Biasa,Sensitif",
    "help_text": "Data inspeksi sensitif (kecuali penjadwalan & pelaksanaan umum)"
  },
  {
    "field_name": "status",
    "field_label": "Status",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "pending",
    "validation": "none",
    "dropdown_options": "pending,scheduled,ongoing,completed,verified",
    "help_text": "Status"
  },
  {
    "field_name": "keterangan",
    "field_label": "Keterangan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Catatan"
  },
  {
    "field_name": "created_by",
    "field_label": "Dibuat Oleh",
    "field_type": "int",
    "field_length": "11",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "User ID"
  },
  {
    "field_name": "created_at",
    "field_label": "Dibuat Pada",
    "field_type": "timestamp",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "CURRENT_TIMESTAMP",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": ""
  },
  {
    "field_name": "updated_at",
    "field_label": "Diperbarui Pada",
    "field_type": "timestamp",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "CURRENT_TIMESTAMP",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": ""
  }
];
