export const fields = [
  {
    "field_name": "id",
    "field_label": "ID",
    "field_type": "auto_increment",
    "field_length": "11",
    "is_required": "true",
    "is_unique": "true",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Primary Key"
  },
  {
    "field_name": "layanan_id",
    "field_label": "Layanan",
    "field_type": "varchar",
    "field_length": "10",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "LY048",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "FK ke layanan_menpanrb"
  },
  {
    "field_name": "periode",
    "field_label": "Periode",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Bulan periode laporan (YYYY-MM-01)"
  },
  {
    "field_name": "tahun",
    "field_label": "Tahun",
    "field_type": "int",
    "field_length": "4",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tahun"
  },
  {
    "field_name": "bulan",
    "field_label": "Bulan",
    "field_type": "int",
    "field_length": "2",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Bulan (1-12)"
  },
  {
    "field_name": "total_komoditas",
    "field_label": "Total Komoditas",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Jumlah komoditas dipantau"
  },
  {
    "field_name": "total_stok",
    "field_label": "Total Stok (Ton)",
    "field_type": "decimal",
    "field_length": "15,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Total stok pangan"
  },
  {
    "field_name": "stok_aman",
    "field_label": "Stok Aman",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Jumlah komoditas stok aman"
  },
  {
    "field_name": "stok_menipis",
    "field_label": "Stok Menipis",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Jumlah komoditas stok menipis"
  },
  {
    "field_name": "stok_kritis",
    "field_label": "Stok Kritis",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Jumlah komoditas stok kritis"
  },
  {
    "field_name": "wilayah_rawan_pangan",
    "field_label": "Wilayah Rawan Pangan",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Jumlah wilayah rawan"
  },
  {
    "field_name": "tingkat_kerawanan",
    "field_label": "Tingkat Kerawanan",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "Aman",
    "validation": "none",
    "dropdown_options": "Aman,Waspada,Rawan,Sangat Rawan",
    "help_text": "Tingkat kerawanan pangan"
  },
  {
    "field_name": "komoditas_kritis",
    "field_label": "Komoditas Kritis",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Daftar komoditas yang kritis"
  },
  {
    "field_name": "produksi_pangan_total",
    "field_label": "Produksi Total (Ton)",
    "field_type": "decimal",
    "field_length": "15,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Total produksi bulan ini"
  },
  {
    "field_name": "konsumsi_estimasi",
    "field_label": "Estimasi Konsumsi (Ton)",
    "field_type": "decimal",
    "field_length": "15,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Estimasi kebutuhan"
  },
  {
    "field_name": "surplus_defisit",
    "field_label": "Surplus/Defisit (Ton)",
    "field_type": "decimal",
    "field_length": "15,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Produksi - Konsumsi"
  },
  {
    "field_name": "analisis",
    "field_label": "Analisis",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Analisis kondisi ketersediaan"
  },
  {
    "field_name": "rekomendasi",
    "field_label": "Rekomendasi",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Rekomendasi tindakan"
  },
  {
    "field_name": "sumber_data",
    "field_label": "Sumber Data",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "Bidang Ketersediaan & Kerawanan Pangan",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Dari bidang mana"
  },
  {
    "field_name": "file_laporan",
    "field_label": "File Laporan",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Upload laporan PDF"
  },
  {
    "field_name": "file_data_pendukung",
    "field_label": "File Data Pendukung",
    "field_type": "json",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Array file Excel/data"
  },
  {
    "field_name": "penanggung_jawab",
    "field_label": "Penanggung Jawab",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "Sekretaris",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "PIC"
  },
  {
    "field_name": "pelaksana",
    "field_label": "Pelaksana",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "Bidang Ketersediaan",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Yang menyusun"
  },
  {
    "field_name": "is_sensitive",
    "field_label": "Tingkat Sensitivitas",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "Biasa",
    "validation": "none",
    "dropdown_options": "Biasa,Sensitif",
    "help_text": "Klasifikasi data"
  },
  {
    "field_name": "status",
    "field_label": "Status",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "draft",
    "validation": "none",
    "dropdown_options": "draft,review,final",
    "help_text": "Status"
  },
  {
    "field_name": "keterangan",
    "field_label": "Keterangan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Catatan"
  },
  {
    "field_name": "created_by",
    "field_label": "Dibuat Oleh",
    "field_type": "int",
    "field_length": "11",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "User ID"
  },
  {
    "field_name": "created_at",
    "field_label": "Dibuat Pada",
    "field_type": "timestamp",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "CURRENT_TIMESTAMP",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": ""
  },
  {
    "field_name": "updated_at",
    "field_label": "Diperbarui Pada",
    "field_type": "timestamp",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "CURRENT_TIMESTAMP",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": ""
  }
];
