// =====================================================
// AUTO-GENERATED ROUTE INDEX
// Generated: 2026-07-17T11:27:03.417Z
// Total Routes: 124
// =====================================================

import BDSBMBRoutes from './BDS-BMB.js';
import BDSCPDRoutes from './BDS-CPD.js';
import BDSEVLRoutes from './BDS-EVL.js';
import BDSHRGRoutes from './BDS-HRG.js';
import BDSKBJRoutes from './BDS-KBJ.js';
import BDSLAPRoutes from './BDS-LAP.js';
import BDSMONRoutes from './BDS-MON.js';
import BKSBMBRoutes from './BKS-BMB.js';
import BKSDVRRoutes from './BKS-DVR.js';
import BKSEVLRoutes from './BKS-EVL.js';
import BKSKBJRoutes from './BKS-KBJ.js';
import BKSKMNRoutes from './BKS-KMN.js';
import BKSLAPRoutes from './BKS-LAP.js';
import BKTBMBRoutes from './BKT-BMB.js';
import BKTFSLRoutes from './BKT-FSL.js';
import BKTKBJRoutes from './BKT-KBJ.js';
import BKTKRWRoutes from './BKT-KRW.js';
import BKTMEVRoutes from './BKT-MEV.js';
import BKTPGDRoutes from './BKT-PGD.js';
import RoleRoutes from './Role.js';
import SEKADMRoutes from './SEK-ADM.js';
import SEKASTRoutes from './SEK-AST.js';
import SEKHUMRoutes from './SEK-HUM.js';
import SEKKBJRoutes from './SEK-KBJ.js';
import SEKKEPRoutes from './SEK-KEP.js';
import SEKKEURoutes from './SEK-KEU.js';
import SEKLDSRoutes from './SEK-LDS.js';
import SEKLKSRoutes from './SEK-LKS.js';
import SEKLKTRoutes from './SEK-LKT.js';
import SEKLUPRoutes from './SEK-LUP.js';
import SEKRENRoutes from './SEK-REN.js';
import SEKRMHRoutes from './SEK-RMH.js';
import UPTADMRoutes from './UPT-ADM.js';
import UPTASTRoutes from './UPT-AST.js';
import UPTINSRoutes from './UPT-INS.js';
import UPTKEPRoutes from './UPT-KEP.js';
import UPTKEURoutes from './UPT-KEU.js';
import UPTMTURoutes from './UPT-MTU.js';
import UPTTKNRoutes from './UPT-TKN.js';
import UserRoutes from './User.js';
import User_legacyRoutes from './User_legacy.js';
import WorkflowHistoryRoutes from './WorkflowHistory.js';
import WorkflowInstanceRoutes from './WorkflowInstance.js';
import approvalRoutes from './approval.js';
import approvalLogRoutes from './approvalLog.js';
import approvalWorkflowRoutes from './approvalWorkflow.js';
import audittrailRoutes from './audit-trail.js';
import auditLogRoutes from './auditLog.js';
import auditLogControllerRoutes from './auditLogController.js';
import authRoutes from './auth.js';
import authControllerRoutes from './authController.js';
import bendaharabarangRoutes from './bendahara-barang.js';
import bendaharagajiRoutes from './bendahara-gaji.js';
import bendaharapengeluaranRoutes from './bendahara-pengeluaran.js';
import bidangRoutes from './bidang.js';
import bridgeEpelaraRoutes from './bridgeEpelara.js';
import bypassDetectionRoutes from './bypassDetection.js';
import caseRoutes from './case.js';
import chatbotRoutes from './chatbot.js';
import clarificationRoutes from './clarification.js';
import commentRoutes from './comment.js';
import complianceRoutes from './compliance.js';
import coordinationRoutes from './coordination.js';
import dashboardRoutes from './dashboard.js';
import dataRoutes from './data.js';
import dataIntegrationLogRoutes from './dataIntegrationLog.js';
import ePelaraRoutesRoutes from './ePelaraRoutes.js';
import executionThreadRoutes from './executionThread.js';
import gubernurRoutes from './gubernur.js';
import inflasiRoutes from './inflasi.js';
import integrationLogRoutes from './integrationLog.js';
import integrationLogControllerRoutes from './integrationLogController.js';
import jfdistribusiRoutes from './jf-distribusi.js';
import jfketersediaanRoutes from './jf-ketersediaan.js';
import jfkeuanganRoutes from './jf-keuangan.js';
import jfkonsumsiRoutes from './jf-konsumsi.js';
import jfperencanaanRoutes from './jf-perencanaan.js';
import kabiddistribusiRoutes from './kabid-distribusi.js';
import kabidketersediaanRoutes from './kabid-ketersediaan.js';
import kabidkonsumsiRoutes from './kabid-konsumsi.js';
import kadinRoutes from './kadin.js';
import kasubagRoutes from './kasubag.js';
import kgbRoutes from './kgb.js';
import kgbControllerRoutes from './kgbController.js';
import komoditasRoutes from './komoditas.js';
import komoditasControllerRoutes from './komoditasController.js';
import komoditasStockRoutes from './komoditasStock.js';
import layananRoutes from './layanan.js';
import masterDataSyncRoutes from './masterDataSync.js';
import masterDataSyncControllerRoutes from './masterDataSyncController.js';
import mfaRoutes from './mfa.js';
import migrationMasterRoutesRoutes from './migrationMasterRoutes.js';
import migrationTransactionRoutes from './migrationTransaction.js';
import migrationTransactionAdminRoutesRoutes from './migrationTransactionAdminRoutes.js';
import moduleGeneratorRoutes from './moduleGenerator.js';
import moduleGeneratorControllerRoutes from './moduleGeneratorController.js';
import modulesRoutes from './modules.js';
import notificationRoutes from './notification.js';
import panelRoutes from './panel.js';
import pegawaiRoutes from './pegawai.js';
import pegawaiControllerRoutes from './pegawaiController.js';
import pelaksanabidangRoutes from './pelaksana-bidang.js';
import perintahRoutes from './perintah.js';
import publicRoutes from './public.js';
import reminderRoutes from './reminder.js';
import renjaRoutes from './renja.js';
import reportRoutes from './report.js';
import rkpdRoutes from './rkpd.js';
import spipRoutes from './spip.js';
import spjRoutes from './spj.js';
import stokRoutes from './stok.js';
import stokControllerRoutes from './stokController.js';
import subKegiatanUsulRoutes from './subKegiatanUsul.js';
import suratRoutes from './surat.js';
import tablesRoutes from './tables.js';
import taskDiscussionRoutes from './taskDiscussion.js';
import tasksRoutes from './tasks.js';
import uptdRoutes from './uptd.js';
import uptdOpsRoutes from './uptdOps.js';
import workflowstatusRoutes from './workflow-status.js';
import workflowRoutes from './workflow.js';
import workflowControllerRoutes from './workflowController.js';
import workflowTransitionLogRoutes from './workflowTransitionLog.js';
import workflowsRoutes from './workflows.js';

export default function registerRoutes(app) {
  app.use('/api/bds-bmb', BDSBMBRoutes);
  app.use('/api/bds-cpd', BDSCPDRoutes);
  app.use('/api/bds-evl', BDSEVLRoutes);
  app.use('/api/bds-hrg', BDSHRGRoutes);
  app.use('/api/bds-kbj', BDSKBJRoutes);
  app.use('/api/bds-lap', BDSLAPRoutes);
  app.use('/api/bds-mon', BDSMONRoutes);
  app.use('/api/bks-bmb', BKSBMBRoutes);
  app.use('/api/bks-dvr', BKSDVRRoutes);
  app.use('/api/bks-evl', BKSEVLRoutes);
  app.use('/api/bks-kbj', BKSKBJRoutes);
  app.use('/api/bks-kmn', BKSKMNRoutes);
  app.use('/api/bks-lap', BKSLAPRoutes);
  app.use('/api/bkt-bmb', BKTBMBRoutes);
  app.use('/api/bkt-fsl', BKTFSLRoutes);
  app.use('/api/bkt-kbj', BKTKBJRoutes);
  app.use('/api/bkt-krw', BKTKRWRoutes);
  app.use('/api/bkt-mev', BKTMEVRoutes);
  app.use('/api/bkt-pgd', BKTPGDRoutes);
  app.use('/api/role', RoleRoutes);
  app.use('/api/sek-adm', SEKADMRoutes);
  app.use('/api/sek-ast', SEKASTRoutes);
  app.use('/api/sek-hum', SEKHUMRoutes);
  app.use('/api/sek-kbj', SEKKBJRoutes);
  app.use('/api/sek-kep', SEKKEPRoutes);
  app.use('/api/sek-keu', SEKKEURoutes);
  app.use('/api/sek-lds', SEKLDSRoutes);
  app.use('/api/sek-lks', SEKLKSRoutes);
  app.use('/api/sek-lkt', SEKLKTRoutes);
  app.use('/api/sek-lup', SEKLUPRoutes);
  app.use('/api/sek-ren', SEKRENRoutes);
  app.use('/api/sek-rmh', SEKRMHRoutes);
  app.use('/api/upt-adm', UPTADMRoutes);
  app.use('/api/upt-ast', UPTASTRoutes);
  app.use('/api/upt-ins', UPTINSRoutes);
  app.use('/api/upt-kep', UPTKEPRoutes);
  app.use('/api/upt-keu', UPTKEURoutes);
  app.use('/api/upt-mtu', UPTMTURoutes);
  app.use('/api/upt-tkn', UPTTKNRoutes);
  app.use('/api/user', UserRoutes);
  app.use('/api/user_legacy', User_legacyRoutes);
  app.use('/api/workflowhistory', WorkflowHistoryRoutes);
  app.use('/api/workflowinstance', WorkflowInstanceRoutes);
  app.use('/api/approval', approvalRoutes);
  app.use('/api/approvallog', approvalLogRoutes);
  app.use('/api/approvalworkflow', approvalWorkflowRoutes);
  app.use('/api/audit-trail', audittrailRoutes);
  app.use('/api/auditlog', auditLogRoutes);
  app.use('/api/auditlogcontroller', auditLogControllerRoutes);
  app.use('/api/auth', authRoutes);
  app.use('/api/authcontroller', authControllerRoutes);
  app.use('/api/bendahara-barang', bendaharabarangRoutes);
  app.use('/api/bendahara-gaji', bendaharagajiRoutes);
  app.use('/api/bendahara-pengeluaran', bendaharapengeluaranRoutes);
  app.use('/api/bidang', bidangRoutes);
  app.use('/api/bridgeepelara', bridgeEpelaraRoutes);
  app.use('/api/bypassdetection', bypassDetectionRoutes);
  app.use('/api/case', caseRoutes);
  app.use('/api/chatbot', chatbotRoutes);
  app.use('/api/clarification', clarificationRoutes);
  app.use('/api/comment', commentRoutes);
  app.use('/api/compliance', complianceRoutes);
  app.use('/api/coordination', coordinationRoutes);
  app.use('/api/dashboard', dashboardRoutes);
  app.use('/api/data', dataRoutes);
  app.use('/api/dataintegrationlog', dataIntegrationLogRoutes);
  app.use('/api/epelararoutes', ePelaraRoutesRoutes);
  app.use('/api/executionthread', executionThreadRoutes);
  app.use('/api/gubernur', gubernurRoutes);
  app.use('/api/inflasi', inflasiRoutes);
  app.use('/api/integrationlog', integrationLogRoutes);
  app.use('/api/integrationlogcontroller', integrationLogControllerRoutes);
  app.use('/api/jf-distribusi', jfdistribusiRoutes);
  app.use('/api/jf-ketersediaan', jfketersediaanRoutes);
  app.use('/api/jf-keuangan', jfkeuanganRoutes);
  app.use('/api/jf-konsumsi', jfkonsumsiRoutes);
  app.use('/api/jf-perencanaan', jfperencanaanRoutes);
  app.use('/api/kabid-distribusi', kabiddistribusiRoutes);
  app.use('/api/kabid-ketersediaan', kabidketersediaanRoutes);
  app.use('/api/kabid-konsumsi', kabidkonsumsiRoutes);
  app.use('/api/kadin', kadinRoutes);
  app.use('/api/kasubag', kasubagRoutes);
  app.use('/api/kgb', kgbRoutes);
  app.use('/api/kgbcontroller', kgbControllerRoutes);
  app.use('/api/komoditas', komoditasRoutes);
  app.use('/api/komoditascontroller', komoditasControllerRoutes);
  app.use('/api/komoditasstock', komoditasStockRoutes);
  app.use('/api/layanan', layananRoutes);
  app.use('/api/masterdatasync', masterDataSyncRoutes);
  app.use('/api/masterdatasynccontroller', masterDataSyncControllerRoutes);
  app.use('/api/mfa', mfaRoutes);
  app.use('/api/migrationmasterroutes', migrationMasterRoutesRoutes);
  app.use('/api/migrationtransaction', migrationTransactionRoutes);
  app.use('/api/migrationtransactionadminroutes', migrationTransactionAdminRoutesRoutes);
  app.use('/api/modulegenerator', moduleGeneratorRoutes);
  app.use('/api/modulegeneratorcontroller', moduleGeneratorControllerRoutes);
  app.use('/api/modules', modulesRoutes);
  app.use('/api/notification', notificationRoutes);
  app.use('/api/panel', panelRoutes);
  app.use('/api/pegawai', pegawaiRoutes);
  app.use('/api/pegawaicontroller', pegawaiControllerRoutes);
  app.use('/api/pelaksana-bidang', pelaksanabidangRoutes);
  app.use('/api/perintah', perintahRoutes);
  app.use('/api/public', publicRoutes);
  app.use('/api/reminder', reminderRoutes);
  app.use('/api/renja', renjaRoutes);
  app.use('/api/report', reportRoutes);
  app.use('/api/rkpd', rkpdRoutes);
  app.use('/api/spip', spipRoutes);
  app.use('/api/spj', spjRoutes);
  app.use('/api/stok', stokRoutes);
  app.use('/api/stokcontroller', stokControllerRoutes);
  app.use('/api/subkegiatanusul', subKegiatanUsulRoutes);
  app.use('/api/surat', suratRoutes);
  app.use('/api/tables', tablesRoutes);
  app.use('/api/taskdiscussion', taskDiscussionRoutes);
  app.use('/api/tasks', tasksRoutes);
  app.use('/api/uptd', uptdRoutes);
  app.use('/api/uptdops', uptdOpsRoutes);
  app.use('/api/workflow-status', workflowstatusRoutes);
  app.use('/api/workflow', workflowRoutes);
  app.use('/api/workflowcontroller', workflowControllerRoutes);
  app.use('/api/workflowtransitionlog', workflowTransitionLogRoutes);
  app.use('/api/workflows', workflowsRoutes);

}
