export const fields = [
  {
    "field_name": "id",
    "field_label": "ID",
    "field_type": "auto_increment",
    "field_length": "11",
    "is_required": "true",
    "is_unique": "true",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Primary Key"
  },
  {
    "field_name": "unit_kerja",
    "field_label": "Unit Kerja",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Sekretariat,UPTD,Bidang Ketersediaan,Bidang Distribusi,Bidang Konsumsi",
    "help_text": "Unit yang input data (AUTO-SET sesuai bidang)"
  },
  {
    "field_name": "reported_to_sekretariat",
    "field_label": "Dilaporkan ke Sekretariat",
    "field_type": "boolean",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "0",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Sudah dilaporkan ke Sekretariat untuk konsolidasi"
  },
  {
    "field_name": "reported_at",
    "field_label": "Tanggal Lapor ke Sekretariat",
    "field_type": "timestamp",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Kapan dilaporkan ke Sekretariat"
  },
  {
    "field_name": "sekretariat_notes",
    "field_label": "Catatan Sekretariat",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Catatan dari Sekretaris saat review/konsolidasi"
  },
  {
    "field_name": "layanan_id",
    "field_label": "Layanan",
    "field_type": "varchar",
    "field_length": "10",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "FK ke layanan_menpanrb (LY062-LY065)"
  },
  {
    "field_name": "jenis_kerawanan",
    "field_label": "Jenis Kerawanan",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Identifikasi,Peta Kerawanan,Rencana Aksi,Koordinasi Lintas Sektor",
    "help_text": "Jenis kerawanan"
  },
  {
    "field_name": "periode",
    "field_label": "Periode",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Periode pemetaan/identifikasi"
  },
  {
    "field_name": "tahun",
    "field_label": "Tahun",
    "field_type": "int",
    "field_length": "4",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tahun"
  },
  {
    "field_name": "kabupaten",
    "field_label": "Kabupaten",
    "field_type": "varchar",
    "field_length": "100",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Kabupaten"
  },
  {
    "field_name": "kecamatan",
    "field_label": "Kecamatan",
    "field_type": "varchar",
    "field_length": "100",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Kecamatan"
  },
  {
    "field_name": "desa",
    "field_label": "Desa",
    "field_type": "varchar",
    "field_length": "100",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Desa"
  },
  {
    "field_name": "latitude",
    "field_label": "Latitude",
    "field_type": "decimal",
    "field_length": "10,8",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Koordinat GPS latitude"
  },
  {
    "field_name": "longitude",
    "field_label": "Longitude",
    "field_type": "decimal",
    "field_length": "11,8",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Koordinat GPS longitude"
  },
  {
    "field_name": "tingkat_kerawanan",
    "field_label": "Tingkat Kerawanan",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Prioritas 1,Prioritas 2,Prioritas 3,Prioritas 4,Prioritas 5,Prioritas 6",
    "help_text": "Prioritas kerawanan (1=paling rawan)"
  },
  {
    "field_name": "skor_kerawanan",
    "field_label": "Skor Kerawanan",
    "field_type": "decimal",
    "field_length": "5,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Skor hasil perhitungan"
  },
  {
    "field_name": "indikator_ketersediaan_pangan",
    "field_label": "Indikator Ketersediaan Pangan",
    "field_type": "decimal",
    "field_length": "5,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Skor indikator ketersediaan"
  },
  {
    "field_name": "indikator_akses_pangan",
    "field_label": "Indikator Akses Pangan",
    "field_type": "decimal",
    "field_length": "5,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Skor indikator akses"
  },
  {
    "field_name": "indikator_pemanfaatan_pangan",
    "field_label": "Indikator Pemanfaatan Pangan",
    "field_type": "decimal",
    "field_length": "5,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Skor indikator pemanfaatan"
  },
  {
    "field_name": "indikator_kerawanan_kesehatan",
    "field_label": "Indikator Kesehatan",
    "field_type": "decimal",
    "field_length": "5,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Skor indikator kesehatan"
  },
  {
    "field_name": "jumlah_penduduk",
    "field_label": "Jumlah Penduduk",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Total penduduk wilayah"
  },
  {
    "field_name": "jumlah_kk",
    "field_label": "Jumlah KK",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Jumlah kepala keluarga"
  },
  {
    "field_name": "jumlah_kk_miskin",
    "field_label": "Jumlah KK Miskin",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "KK miskin"
  },
  {
    "field_name": "persentase_kemiskinan",
    "field_label": "Persentase Kemiskinan",
    "field_type": "decimal",
    "field_length": "5,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Persen kemiskinan"
  },
  {
    "field_name": "stunting_prevalensi",
    "field_label": "Prevalensi Stunting",
    "field_type": "decimal",
    "field_length": "5,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Persentase stunting"
  },
  {
    "field_name": "wasting_prevalensi",
    "field_label": "Prevalensi Wasting",
    "field_type": "decimal",
    "field_length": "5,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Persentase wasting"
  },
  {
    "field_name": "underweight_prevalensi",
    "field_label": "Prevalensi Underweight",
    "field_type": "decimal",
    "field_length": "5,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Persentase underweight"
  },
  {
    "field_name": "jenis_pangan_rawan",
    "field_label": "Jenis Pangan Rawan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Komoditas yang rawan"
  },
  {
    "field_name": "stok_pangan",
    "field_label": "Stok Pangan (Ton)",
    "field_type": "decimal",
    "field_length": "15,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Stok pangan di wilayah"
  },
  {
    "field_name": "satuan_stok",
    "field_label": "Satuan",
    "field_type": "varchar",
    "field_length": "20",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "kg",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Satuan stok"
  },
  {
    "field_name": "tanggal_update_stok",
    "field_label": "Tanggal Update Stok",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Kapan data di-update"
  },
  {
    "field_name": "status_ketersediaan",
    "field_label": "Status Ketersediaan",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Aman,Waspada,Rawan,Sangat Rawan",
    "help_text": "Status ketersediaan wilayah"
  },
  {
    "field_name": "penyebab_kerawanan",
    "field_label": "Penyebab Kerawanan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Faktor penyebab"
  },
  {
    "field_name": "dampak_kerawanan",
    "field_label": "Dampak Kerawanan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Dampak yang terjadi"
  },
  {
    "field_name": "rencana_aksi",
    "field_label": "Rencana Aksi",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Rencana penanganan"
  },
  {
    "field_name": "target_intervensi",
    "field_label": "Target Intervensi",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Target yang ingin dicapai"
  },
  {
    "field_name": "waktu_pelaksanaan",
    "field_label": "Waktu Pelaksanaan",
    "field_type": "varchar",
    "field_length": "100",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Kapan dilaksanakan"
  },
  {
    "field_name": "anggaran_kebutuhan",
    "field_label": "Kebutuhan Anggaran",
    "field_type": "decimal",
    "field_length": "15,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Estimasi anggaran"
  },
  {
    "field_name": "sumber_anggaran",
    "field_label": "Sumber Anggaran",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Dari mana anggarannya"
  },
  {
    "field_name": "instansi_terkait",
    "field_label": "Instansi Terkait",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Instansi yang terlibat koordinasi"
  },
  {
    "field_name": "koordinasi_dengan",
    "field_label": "Koordinasi Dengan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Lintas sektor mana"
  },
  {
    "field_name": "hasil_koordinasi",
    "field_label": "Hasil Koordinasi",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Hasil rapat koordinasi"
  },
  {
    "field_name": "tindak_lanjut_koordinasi",
    "field_label": "Tindak Lanjut",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tindak lanjut koordinasi"
  },
  {
    "field_name": "file_peta",
    "field_label": "File Peta",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Upload peta kerawanan (PNG/PDF)"
  },
  {
    "field_name": "file_data_gis",
    "field_label": "File Data GIS",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Upload shapefile (ZIP)"
  },
  {
    "field_name": "file_laporan",
    "field_label": "File Laporan",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Laporan identifikasi PDF"
  },
  {
    "field_name": "file_rencana_aksi",
    "field_label": "File Rencana Aksi",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Dokumen rencana aksi"
  },
  {
    "field_name": "rincian_layanan",
    "field_label": "Rincian Layanan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Detail layanan"
  },
  {
    "field_name": "penanggung_jawab",
    "field_label": "Penanggung Jawab",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "Kepala Bidang Ketersediaan",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "PIC"
  },
  {
    "field_name": "pelaksana",
    "field_label": "Pelaksana",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Yang melaksanakan"
  },
  {
    "field_name": "kelompok_penerima",
    "field_label": "Kelompok Penerima",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "Pemerintah Daerah/Masyarakat",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Siapa yang terima"
  },
  {
    "field_name": "jenis_data",
    "field_label": "Jenis Data",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Jenis data"
  },
  {
    "field_name": "is_sensitive",
    "field_label": "Tingkat Sensitivitas",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "Sensitif",
    "validation": "none",
    "dropdown_options": "Biasa,Sensitif",
    "help_text": "Data kerawanan sensitif"
  },
  {
    "field_name": "status",
    "field_label": "Status",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "draft",
    "validation": "none",
    "dropdown_options": "draft,review,final,publish",
    "help_text": "Status"
  },
  {
    "field_name": "keterangan",
    "field_label": "Keterangan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Catatan"
  },
  {
    "field_name": "created_by",
    "field_label": "Dibuat Oleh",
    "field_type": "int",
    "field_length": "11",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "User ID"
  },
  {
    "field_name": "created_at",
    "field_label": "Dibuat Pada",
    "field_type": "timestamp",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "CURRENT_TIMESTAMP",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": ""
  },
  {
    "field_name": "updated_at",
    "field_label": "Diperbarui Pada",
    "field_type": "timestamp",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "CURRENT_TIMESTAMP",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": ""
  }
];
