export const up = async (queryInterface) => {
  await queryInterface.bulkInsert(
    "Users",
    [
      {
        id: 1,
        username: "super_admin_user_1",
        email: "super_admin@example.com",
        password: "password123",
        plain_password: "password123",
        name: "SUPER ADMIN",
        role_id: "super_admin",
        unit_id: "unit_1",
        unit_kerja: "Unit Kerja 1",
        is_active: true,
      },
      {
        id: 2,
        username: "gubernur_user_2",
        email: "gubernur@example.com",
        password: "password123",
        plain_password: "password123",
        name: "GUBERNUR",
        role_id: "gubernur",
        unit_id: "unit_2",
        unit_kerja: "Unit Kerja 2",
        is_active: true,
      },
      {
        id: 3,
        username: "sekretaris_user_3",
        email: "sekretaris@example.com",
        password: "password123",
        plain_password: "password123",
        name: "SEKRETARIS",
        role_id: "sekretaris",
        unit_id: "unit_3",
        unit_kerja: "Unit Kerja 3",
        is_active: true,
      },
      {
        id: 4,
        username: "kepala_bidang_ketersediaan_user_4",
        email: "kepala_bidang_ketersediaan@example.com",
        password: "password123",
        plain_password: "password123",
        name: "KEPALA BIDANG KETERSEDIAAN",
        role_id: "kepala_bidang_ketersediaan",
        unit_id: "unit_4",
        unit_kerja: "Unit Kerja 4",
        is_active: true,
      },
      {
        id: 5,
        username: "kepala_bidang_distribusi_user_5",
        email: "kepala_bidang_distribusi@example.com",
        password: "password123",
        plain_password: "password123",
        name: "KEPALA BIDANG DISTRIBUSI",
        role_id: "kepala_bidang_distribusi",
        unit_id: "unit_5",
        unit_kerja: "Unit Kerja 5",
        is_active: true,
      },
      {
        id: 6,
        username: "kepala_bidang_konsumsi_user_6",
        email: "kepala_bidang_konsumsi@example.com",
        password: "password123",
        plain_password: "password123",
        name: "KEPALA BIDANG KONSUMSI",
        role_id: "kepala_bidang_konsumsi",
        unit_id: "unit_6",
        unit_kerja: "Unit Kerja 6",
        is_active: true,
      },
      {
        id: 7,
        username: "kepala_uptd_user_7",
        email: "kepala_uptd@example.com",
        password: "password123",
        plain_password: "password123",
        name: "KEPALA UPTD",
        role_id: "kepala_uptd",
        unit_id: "unit_7",
        unit_kerja: "Unit Kerja 7",
        is_active: true,
      },
      {
        id: 8,
        username: "publik_user_8",
        email: "publik@example.com",
        password: "password123",
        plain_password: "password123",
        name: "PUBLIK",
        role_id: "publik",
        unit_id: "unit_8",
        unit_kerja: "Unit Kerja 8",
        is_active: true,
      },
      {
        id: 9,
        username: "fungsional_ketersediaan_user_9",
        email: "fungsional_ketersediaan@example.com",
        password: "password123",
        plain_password: "password123",
        name: "FUNGSIONAL KETERSEDIAAN",
        role_id: "fungsional",
        unit_id: "unit_9",
        unit_kerja: "Unit Kerja 9",
        is_active: true,
      },
    ],
    {},
  );
};

export const down = async (queryInterface) => {
  await queryInterface.bulkDelete("Users", null, {});
};
