export const fields = [
  {
    "field_name": "id",
    "field_label": "ID",
    "field_type": "auto_increment",
    "field_length": "11",
    "is_required": "true",
    "is_unique": "true",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Primary Key"
  },
  {
    "field_name": "layanan_id",
    "field_label": "Layanan",
    "field_type": "varchar",
    "field_length": "10",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "FK ke layanan_menpanrb (LY040-LY045)"
  },
  {
    "field_name": "jenis_layanan_perencanaan",
    "field_label": "Jenis Layanan",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Renstra,Renja,Fasilitasi Program,Sinkronisasi,LKJIP/LAKIP,Laporan Kinerja",
    "help_text": "Jenis layanan perencanaan"
  },
  {
    "field_name": "tahun_perencanaan",
    "field_label": "Tahun",
    "field_type": "int",
    "field_length": "4",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tahun perencanaan"
  },
  {
    "field_name": "periode_renstra",
    "field_label": "Periode Renstra",
    "field_type": "varchar",
    "field_length": "20",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Contoh: 2024-2029"
  },
  {
    "field_name": "visi",
    "field_label": "Visi",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Visi organisasi"
  },
  {
    "field_name": "misi",
    "field_label": "Misi",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Misi organisasi"
  },
  {
    "field_name": "tujuan",
    "field_label": "Tujuan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tujuan strategis"
  },
  {
    "field_name": "sasaran",
    "field_label": "Sasaran",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Sasaran"
  },
  {
    "field_name": "strategi",
    "field_label": "Strategi",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Strategi pencapaian"
  },
  {
    "field_name": "kode_program",
    "field_label": "Kode Program",
    "field_type": "varchar",
    "field_length": "50",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Kode program"
  },
  {
    "field_name": "nama_program",
    "field_label": "Nama Program",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Nama program"
  },
  {
    "field_name": "kode_kegiatan",
    "field_label": "Kode Kegiatan",
    "field_type": "varchar",
    "field_length": "50",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Kode kegiatan"
  },
  {
    "field_name": "nama_kegiatan",
    "field_label": "Nama Kegiatan",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Nama kegiatan"
  },
  {
    "field_name": "indikator_kinerja",
    "field_label": "Indikator Kinerja",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Indikator keberhasilan"
  },
  {
    "field_name": "target_kinerja",
    "field_label": "Target Kinerja",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Target yang ingin dicapai"
  },
  {
    "field_name": "satuan_target",
    "field_label": "Satuan",
    "field_type": "varchar",
    "field_length": "50",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Satuan target"
  },
  {
    "field_name": "realisasi_kinerja",
    "field_label": "Realisasi",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Realisasi pencapaian"
  },
  {
    "field_name": "persentase_capaian",
    "field_label": "Persentase Capaian",
    "field_type": "decimal",
    "field_length": "5,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Persen capaian target"
  },
  {
    "field_name": "pagu_anggaran",
    "field_label": "Pagu Anggaran",
    "field_type": "decimal",
    "field_length": "15,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Pagu anggaran program/kegiatan"
  },
  {
    "field_name": "bidang_pelaksana",
    "field_label": "Bidang Pelaksana",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Bidang yang melaksanakan"
  },
  {
    "field_name": "penanggung_jawab_kegiatan",
    "field_label": "PJ Kegiatan",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Penanggung jawab kegiatan"
  },
  {
    "field_name": "waktu_pelaksanaan",
    "field_label": "Waktu Pelaksanaan",
    "field_type": "varchar",
    "field_length": "100",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Kapan dilaksanakan"
  },
  {
    "field_name": "output",
    "field_label": "Output",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Output kegiatan"
  },
  {
    "field_name": "outcome",
    "field_label": "Outcome",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Outcome program"
  },
  {
    "field_name": "kendala",
    "field_label": "Kendala",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Kendala yang dihadapi"
  },
  {
    "field_name": "solusi",
    "field_label": "Solusi",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Solusi atas kendala"
  },
  {
    "field_name": "rekomendasi",
    "field_label": "Rekomendasi",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Rekomendasi perbaikan"
  },
  {
    "field_name": "status_sinkronisasi",
    "field_label": "Status Sinkronisasi",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Belum,Proses,Sesuai,Tidak Sesuai",
    "help_text": "Sinkronisasi dengan RPJMD/RKPD"
  },
  {
    "field_name": "file_renstra",
    "field_label": "File Renstra",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Upload Renstra PDF"
  },
  {
    "field_name": "file_renja",
    "field_label": "File Renja",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Upload Renja PDF"
  },
  {
    "field_name": "file_lakip",
    "field_label": "File LAKIP",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Upload LAKIP PDF"
  },
  {
    "field_name": "file_laporan_kinerja",
    "field_label": "File Laporan Kinerja",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Upload laporan PDF"
  },
  {
    "field_name": "file_pendukung",
    "field_label": "File Pendukung",
    "field_type": "json",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Array file pendukung"
  },
  {
    "field_name": "penanggung_jawab",
    "field_label": "Penanggung Jawab",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "Fungsional Perencana",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "PIC"
  },
  {
    "field_name": "pelaksana",
    "field_label": "Pelaksana",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Yang melaksanakan"
  },
  {
    "field_name": "is_sensitive",
    "field_label": "Tingkat Sensitivitas",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "Sensitif",
    "validation": "none",
    "dropdown_options": "Biasa,Sensitif",
    "help_text": "Data perencanaan sensitif"
  },
  {
    "field_name": "status",
    "field_label": "Status",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "draft",
    "validation": "none",
    "dropdown_options": "draft,finalisasi,disetujui,final",
    "help_text": "Status dokumen"
  },
  {
    "field_name": "keterangan",
    "field_label": "Keterangan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Catatan"
  },
  {
    "field_name": "created_by",
    "field_label": "Dibuat Oleh",
    "field_type": "int",
    "field_length": "11",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "User ID"
  },
  {
    "field_name": "created_at",
    "field_label": "Dibuat Pada",
    "field_type": "timestamp",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "CURRENT_TIMESTAMP",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": ""
  },
  {
    "field_name": "updated_at",
    "field_label": "Diperbarui Pada",
    "field_type": "timestamp",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "CURRENT_TIMESTAMP",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": ""
  }
];
