export async function up({ context: queryInterface }) {
  await queryInterface.createTable('BDS-LAP', {
      id: { type: DataTypes.INTEGER, allowNull: false, unique: true, autoIncrement: true, primaryKey: true },
      unit_kerja: { type: DataTypes.ENUM, allowNull: false },
      reported_to_sekretariat: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: "0" },
      reported_at: { type: DataTypes.DATE, allowNull: true },
      sekretariat_notes: { type: DataTypes.TEXT, allowNull: true },
      layanan_id: { type: DataTypes.STRING(10), allowNull: false, defaultValue: "LY106" },
      periode: { type: DataTypes.DATEONLY, allowNull: false },
      tahun: { type: DataTypes.INTEGER, allowNull: false },
      bulan: { type: DataTypes.INTEGER, allowNull: true },
      triwulan: { type: DataTypes.INTEGER, allowNull: true },
      semester: { type: DataTypes.INTEGER, allowNull: true },
      judul_laporan: { type: DataTypes.STRING(255), allowNull: false },
      ringkasan_eksekutif: { type: DataTypes.TEXT, allowNull: true },
      capaian_distribusi: { type: DataTypes.TEXT, allowNull: true },
      capaian_stabilisasi_harga: { type: DataTypes.TEXT, allowNull: true },
      capaian_cppd: { type: DataTypes.TEXT, allowNull: true },
      inflasi_pangan: { type: DataTypes.DECIMAL, allowNull: true },
      target_inflasi: { type: DataTypes.DECIMAL, allowNull: true, defaultValue: "2.50" },
      status_inflasi: { type: DataTypes.ENUM, allowNull: true },
      volume_distribusi_total: { type: DataTypes.DECIMAL, allowNull: true },
      stok_cppd: { type: DataTypes.DECIMAL, allowNull: true },
      operasi_pasar_dilakukan: { type: DataTypes.INTEGER, allowNull: true },
      rapat_tpid_dilakukan: { type: DataTypes.INTEGER, allowNull: true },
      anggaran_program: { type: DataTypes.DECIMAL, allowNull: true },
      realisasi_anggaran: { type: DataTypes.DECIMAL, allowNull: true },
      persentase_serapan: { type: DataTypes.DECIMAL, allowNull: true },
      permasalahan: { type: DataTypes.TEXT, allowNull: true },
      solusi: { type: DataTypes.TEXT, allowNull: true },
      rekomendasi: { type: DataTypes.TEXT, allowNull: true },
      tindak_lanjut: { type: DataTypes.TEXT, allowNull: true },
      file_laporan: { type: DataTypes.STRING(255), allowNull: true },
      file_data_pendukung: { type: DataTypes.JSONB, allowNull: true },
      ditujukan_kepada: { type: DataTypes.STRING(255), allowNull: true, defaultValue: "Sekretariat" },
      rincian_layanan: { type: DataTypes.TEXT, allowNull: true },
      penanggung_jawab: { type: DataTypes.STRING(255), allowNull: false, defaultValue: "Kepala Bidang Distribusi" },
      pelaksana: { type: DataTypes.STRING(255), allowNull: false },
      kelompok_penerima: { type: DataTypes.STRING(255), allowNull: true, defaultValue: "Sekretariat/Pimpinan" },
      jenis_data: { type: DataTypes.STRING(255), allowNull: true },
      is_sensitive: { type: DataTypes.ENUM, allowNull: false, defaultValue: "Sensitif" },
      status: { type: DataTypes.ENUM, allowNull: false, defaultValue: "draft" },
      keterangan: { type: DataTypes.TEXT, allowNull: true },
      created_by: { type: DataTypes.INTEGER, allowNull: false },
      created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
      updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
    });
}

export async function down({ context: queryInterface }) {
  await queryInterface.dropTable('BDS-LAP');
}
