export async function up({ context: queryInterface }) {
  await queryInterface.createTable('BDS-CPD', {
      id: { type: DataTypes.INTEGER, allowNull: false, unique: true, autoIncrement: true, primaryKey: true },
      unit_kerja: { type: DataTypes.ENUM, allowNull: false },
      reported_to_sekretariat: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: "0" },
      reported_at: { type: DataTypes.DATE, allowNull: true },
      sekretariat_notes: { type: DataTypes.TEXT, allowNull: true },
      layanan_id: { type: DataTypes.STRING(10), allowNull: false },
      jenis_layanan_cppd: { type: DataTypes.ENUM, allowNull: false },
      periode: { type: DataTypes.DATEONLY, allowNull: false },
      tahun: { type: DataTypes.INTEGER, allowNull: false },
      bulan: { type: DataTypes.INTEGER, allowNull: true },
      komoditas_id: { type: DataTypes.INTEGER, allowNull: true },
      nama_komoditas: { type: DataTypes.STRING(255), allowNull: true },
      kebutuhan_cppd: { type: DataTypes.DECIMAL, allowNull: true },
      dasar_perhitungan: { type: DataTypes.TEXT, allowNull: true },
      target_stok: { type: DataTypes.DECIMAL, allowNull: true },
      lokasi_penyimpanan: { type: DataTypes.STRING(255), allowNull: true },
      kapasitas_gudang: { type: DataTypes.DECIMAL, allowNull: true },
      rencana_pengadaan: { type: DataTypes.DECIMAL, allowNull: true },
      sumber_pengadaan: { type: DataTypes.ENUM, allowNull: true },
      metode_pengadaan: { type: DataTypes.ENUM, allowNull: true },
      penyedia: { type: DataTypes.STRING(255), allowNull: true },
      tanggal_pengadaan: { type: DataTypes.DATEONLY, allowNull: true },
      volume_pengadaan: { type: DataTypes.DECIMAL, allowNull: true },
      harga_satuan: { type: DataTypes.DECIMAL, allowNull: true },
      total_nilai: { type: DataTypes.DECIMAL, allowNull: true },
      kualitas_cppd: { type: DataTypes.ENUM, allowNull: true, defaultValue: "Baik" },
      tanggal_masuk_gudang: { type: DataTypes.DATEONLY, allowNull: true },
      stok_awal_bulan: { type: DataTypes.DECIMAL, allowNull: true },
      penerimaan_bulan_ini: { type: DataTypes.DECIMAL, allowNull: true },
      penyaluran_bulan_ini: { type: DataTypes.DECIMAL, allowNull: true },
      stok_akhir_bulan: { type: DataTypes.DECIMAL, allowNull: true },
      status_stok: { type: DataTypes.ENUM, allowNull: true, defaultValue: "Aman" },
      persentase_terhadap_target: { type: DataTypes.DECIMAL, allowNull: true },
      kondisi_fisik_cppd: { type: DataTypes.ENUM, allowNull: true, defaultValue: "Baik" },
      suhu_gudang: { type: DataTypes.DECIMAL, allowNull: true },
      kelembaban_gudang: { type: DataTypes.DECIMAL, allowNull: true },
      petugas_gudang: { type: DataTypes.STRING(255), allowNull: true },
      jenis_penyaluran: { type: DataTypes.ENUM, allowNull: true },
      alasan_penyaluran: { type: DataTypes.TEXT, allowNull: true },
      wilayah_penyaluran: { type: DataTypes.STRING(255), allowNull: true },
      penerima_penyaluran: { type: DataTypes.STRING(255), allowNull: true },
      volume_penyaluran: { type: DataTypes.DECIMAL, allowNull: true },
      tanggal_penyaluran: { type: DataTypes.DATEONLY, allowNull: true },
      status_penyaluran: { type: DataTypes.ENUM, allowNull: true },
      jumlah_penerima_manfaat: { type: DataTypes.INTEGER, allowNull: true },
      dampak_penyaluran: { type: DataTypes.TEXT, allowNull: true },
      evaluasi_pelaksanaan: { type: DataTypes.TEXT, allowNull: true },
      kendala: { type: DataTypes.TEXT, allowNull: true },
      solusi: { type: DataTypes.TEXT, allowNull: true },
      rekomendasi: { type: DataTypes.TEXT, allowNull: true },
      file_rencana: { type: DataTypes.STRING(255), allowNull: true },
      file_kontrak: { type: DataTypes.STRING(255), allowNull: true },
      file_bast: { type: DataTypes.STRING(255), allowNull: true },
      file_laporan_stok: { type: DataTypes.STRING(255), allowNull: true },
      file_foto: { type: DataTypes.JSONB, allowNull: true },
      rincian_layanan: { type: DataTypes.TEXT, allowNull: true },
      penanggung_jawab: { type: DataTypes.STRING(255), allowNull: false, defaultValue: "Kepala Bidang Distribusi" },
      pelaksana: { type: DataTypes.STRING(255), allowNull: false },
      kelompok_penerima: { type: DataTypes.STRING(255), allowNull: true },
      jenis_data: { type: DataTypes.STRING(255), allowNull: true },
      is_sensitive: { type: DataTypes.ENUM, allowNull: false, defaultValue: "Sensitif" },
      status: { type: DataTypes.ENUM, allowNull: false, defaultValue: "draft" },
      keterangan: { type: DataTypes.TEXT, allowNull: true },
      created_by: { type: DataTypes.INTEGER, allowNull: false },
      created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
      updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
    });
}

export async function down({ context: queryInterface }) {
  await queryInterface.dropTable('BDS-CPD');
}
