export async function up({ context: queryInterface }) {
  await queryInterface.createTable('UPT-TKN', {
      id: { type: DataTypes.INTEGER, allowNull: false, unique: true, autoIncrement: true, primaryKey: true },
      layanan_id: { type: DataTypes.STRING(10), allowNull: false },
      jenis_layanan_teknis: { type: DataTypes.ENUM, allowNull: false },
      nomor_pengujian: { type: DataTypes.STRING(100), allowNull: true },
      nomor_audit: { type: DataTypes.STRING(100), allowNull: true },
      tanggal_pengujian: { type: DataTypes.DATEONLY, allowNull: true },
      pemohon: { type: DataTypes.STRING(255), allowNull: true },
      instansi_pemohon: { type: DataTypes.STRING(255), allowNull: true },
      jenis_sampel: { type: DataTypes.STRING(255), allowNull: true },
      jumlah_sampel: { type: DataTypes.INTEGER, allowNull: true },
      parameter_uji: { type: DataTypes.TEXT, allowNull: true },
      metode_uji: { type: DataTypes.STRING(255), allowNull: true },
      hasil_uji: { type: DataTypes.TEXT, allowNull: true },
      kesimpulan_uji: { type: DataTypes.ENUM, allowNull: true },
      rekomendasi_uji: { type: DataTypes.TEXT, allowNull: true },
      standar_acuan: { type: DataTypes.STRING(255), allowNull: true },
      analis: { type: DataTypes.STRING(255), allowNull: true },
      verifikator: { type: DataTypes.STRING(255), allowNull: true },
      tanggal_verifikasi: { type: DataTypes.DATEONLY, allowNull: true },
      jenis_sertifikasi: { type: DataTypes.ENUM, allowNull: true },
      nama_usaha: { type: DataTypes.STRING(255), allowNull: true },
      jenis_usaha: { type: DataTypes.STRING(255), allowNull: true },
      alamat_usaha: { type: DataTypes.TEXT, allowNull: true },
      pemilik_usaha: { type: DataTypes.STRING(255), allowNull: true },
      kontak_usaha: { type: DataTypes.STRING(50), allowNull: true },
      tanggal_audit: { type: DataTypes.DATEONLY, allowNull: true },
      tim_auditor: { type: DataTypes.TEXT, allowNull: true },
      checklist_audit: { type: DataTypes.JSONB, allowNull: true },
      skor_audit: { type: DataTypes.DECIMAL, allowNull: true },
      hasil_audit: { type: DataTypes.ENUM, allowNull: true },
      catatan_audit: { type: DataTypes.TEXT, allowNull: true },
      tindakan_korektif: { type: DataTypes.TEXT, allowNull: true },
      batas_waktu_perbaikan: { type: DataTypes.DATEONLY, allowNull: true },
      status_sertifikat: { type: DataTypes.ENUM, allowNull: true },
      nomor_sertifikat: { type: DataTypes.STRING(100), allowNull: true },
      tanggal_terbit_sertifikat: { type: DataTypes.DATEONLY, allowNull: true },
      masa_berlaku_sertifikat: { type: DataTypes.DATEONLY, allowNull: true },
      jenis_produk_audit: { type: DataTypes.ENUM, allowNull: true },
      negara_asal: { type: DataTypes.STRING(100), allowNull: true, defaultValue: "Indonesia" },
      dokumen_pendukung: { type: DataTypes.JSONB, allowNull: true },
      periode_laporan: { type: DataTypes.DATEONLY, allowNull: true },
      jenis_laporan: { type: DataTypes.ENUM, allowNull: true },
      total_pengujian: { type: DataTypes.INTEGER, allowNull: true },
      total_audit: { type: DataTypes.INTEGER, allowNull: true },
      total_sertifikat: { type: DataTypes.INTEGER, allowNull: true },
      persentase_kelulusan: { type: DataTypes.DECIMAL, allowNull: true },
      ringkasan_laporan: { type: DataTypes.TEXT, allowNull: true },
      file_hasil_uji: { type: DataTypes.STRING(255), allowNull: true },
      file_sertifikat: { type: DataTypes.STRING(255), allowNull: true },
      file_laporan_audit: { type: DataTypes.STRING(255), allowNull: true },
      file_laporan_teknis: { type: DataTypes.STRING(255), allowNull: true },
      rincian_layanan: { type: DataTypes.TEXT, allowNull: true },
      penanggung_jawab: { type: DataTypes.STRING(255), allowNull: false, defaultValue: "Kepala UPTD" },
      pelaksana: { type: DataTypes.STRING(255), allowNull: false },
      kelompok_penerima: { type: DataTypes.STRING(255), allowNull: true },
      jenis_data: { type: DataTypes.STRING(255), allowNull: true },
      is_sensitive: { type: DataTypes.ENUM, allowNull: false, defaultValue: "Sensitif" },
      status: { type: DataTypes.ENUM, allowNull: false, defaultValue: "pending" },
      keterangan: { type: DataTypes.TEXT, allowNull: true },
      created_by: { type: DataTypes.INTEGER, allowNull: false },
      created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
      updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
    });
}

export async function down({ context: queryInterface }) {
  await queryInterface.dropTable('UPT-TKN');
}
