export async function up({ context: queryInterface }) {
  await queryInterface.createTable('BKS-EVL', {
      id: { type: DataTypes.INTEGER, allowNull: false, unique: true, autoIncrement: true, primaryKey: true },
      unit_kerja: { type: DataTypes.ENUM, allowNull: false },
      reported_to_sekretariat: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: "0" },
      reported_at: { type: DataTypes.DATE, allowNull: true },
      sekretariat_notes: { type: DataTypes.TEXT, allowNull: true },
      layanan_id: { type: DataTypes.STRING(10), allowNull: false },
      jenis_evaluasi: { type: DataTypes.ENUM, allowNull: false },
      periode: { type: DataTypes.DATEONLY, allowNull: false },
      tahun: { type: DataTypes.INTEGER, allowNull: false },
      bulan: { type: DataTypes.INTEGER, allowNull: true },
      triwulan: { type: DataTypes.INTEGER, allowNull: true },
      semester: { type: DataTypes.INTEGER, allowNull: true },
      judul_evaluasi: { type: DataTypes.STRING(255), allowNull: false },
      objek_evaluasi: { type: DataTypes.STRING(255), allowNull: true },
      tujuan_evaluasi: { type: DataTypes.TEXT, allowNull: true },
      metode_evaluasi: { type: DataTypes.ENUM, allowNull: true },
      tim_evaluasi: { type: DataTypes.TEXT, allowNull: true },
      tanggal_evaluasi: { type: DataTypes.DATEONLY, allowNull: true },
      lokasi_evaluasi: { type: DataTypes.STRING(255), allowNull: true },
      program_dievaluasi: { type: DataTypes.TEXT, allowNull: true },
      target_program: { type: DataTypes.TEXT, allowNull: true },
      realisasi_program: { type: DataTypes.TEXT, allowNull: true },
      persentase_capaian: { type: DataTypes.DECIMAL, allowNull: true },
      indikator_kinerja: { type: DataTypes.TEXT, allowNull: true },
      skor_pph_capaian: { type: DataTypes.DECIMAL, allowNull: true },
      skor_pph_target: { type: DataTypes.DECIMAL, allowNull: true, defaultValue: "90" },
      konsumsi_energi_per_kapita: { type: DataTypes.DECIMAL, allowNull: true },
      konsumsi_protein_per_kapita: { type: DataTypes.DECIMAL, allowNull: true },
      jumlah_kelompok_dibina: { type: DataTypes.INTEGER, allowNull: true },
      jumlah_psat_fasilitasi: { type: DataTypes.INTEGER, allowNull: true },
      jumlah_psat_tersertifikasi: { type: DataTypes.INTEGER, allowNull: true },
      kasus_keracunan_pangan: { type: DataTypes.INTEGER, allowNull: true, defaultValue: "0" },
      penanganan_keracunan: { type: DataTypes.TEXT, allowNull: true },
      temuan_evaluasi: { type: DataTypes.TEXT, allowNull: true },
      analisis_capaian: { type: DataTypes.TEXT, allowNull: true },
      permasalahan: { type: DataTypes.TEXT, allowNull: true },
      kendala: { type: DataTypes.TEXT, allowNull: true },
      solusi: { type: DataTypes.TEXT, allowNull: true },
      best_practice: { type: DataTypes.TEXT, allowNull: true },
      lesson_learned: { type: DataTypes.TEXT, allowNull: true },
      rekomendasi: { type: DataTypes.TEXT, allowNull: true },
      tindak_lanjut: { type: DataTypes.TEXT, allowNull: true },
      anggaran_program: { type: DataTypes.DECIMAL, allowNull: true },
      realisasi_anggaran: { type: DataTypes.DECIMAL, allowNull: true },
      persentase_serapan: { type: DataTypes.DECIMAL, allowNull: true },
      output_program: { type: DataTypes.TEXT, allowNull: true },
      outcome_program: { type: DataTypes.TEXT, allowNull: true },
      dampak_program: { type: DataTypes.TEXT, allowNull: true },
      file_laporan: { type: DataTypes.STRING(255), allowNull: true },
      file_data_pendukung: { type: DataTypes.JSONB, allowNull: true },
      file_foto: { type: DataTypes.JSONB, allowNull: true },
      ditujukan_kepada: { type: DataTypes.STRING(255), allowNull: true, defaultValue: "Sekretariat" },
      rincian_layanan: { type: DataTypes.TEXT, allowNull: true },
      penanggung_jawab: { type: DataTypes.STRING(255), allowNull: false, defaultValue: "Kepala Bidang Konsumsi" },
      pelaksana: { type: DataTypes.STRING(255), allowNull: false },
      kelompok_penerima: { type: DataTypes.STRING(255), allowNull: true, defaultValue: "Sekretariat/Pimpinan" },
      jenis_data: { type: DataTypes.STRING(255), allowNull: true },
      is_sensitive: { type: DataTypes.ENUM, allowNull: false, defaultValue: "Sensitif" },
      status: { type: DataTypes.ENUM, allowNull: false, defaultValue: "draft" },
      keterangan: { type: DataTypes.TEXT, allowNull: true },
      created_by: { type: DataTypes.INTEGER, allowNull: false },
      created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
      updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
    });
}

export async function down({ context: queryInterface }) {
  await queryInterface.dropTable('BKS-EVL');
}
