export async function up({ context: queryInterface }) {
  await queryInterface.createTable('BKS-LAP', {
      id: { type: DataTypes.INTEGER, allowNull: false, unique: true, autoIncrement: true, primaryKey: true },
      unit_kerja: { type: DataTypes.ENUM, allowNull: false },
      reported_to_sekretariat: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: "0" },
      reported_at: { type: DataTypes.DATE, allowNull: true },
      sekretariat_notes: { type: DataTypes.TEXT, allowNull: true },
      layanan_id: { type: DataTypes.STRING(10), allowNull: false },
      jenis_laporan: { type: DataTypes.ENUM, allowNull: false },
      periode: { type: DataTypes.DATEONLY, allowNull: false },
      tahun: { type: DataTypes.INTEGER, allowNull: false },
      bulan: { type: DataTypes.INTEGER, allowNull: true },
      triwulan: { type: DataTypes.INTEGER, allowNull: true },
      semester: { type: DataTypes.INTEGER, allowNull: true },
      judul_laporan: { type: DataTypes.STRING(255), allowNull: false },
      ringkasan_eksekutif: { type: DataTypes.TEXT, allowNull: true },
      capaian_konsumsi_pangan: { type: DataTypes.TEXT, allowNull: true },
      capaian_penganekaragaman: { type: DataTypes.TEXT, allowNull: true },
      capaian_keamanan_pangan: { type: DataTypes.TEXT, allowNull: true },
      skor_pph: { type: DataTypes.DECIMAL, allowNull: true },
      target_pph: { type: DataTypes.DECIMAL, allowNull: true, defaultValue: "90" },
      status_pph: { type: DataTypes.ENUM, allowNull: true },
      konsumsi_energi: { type: DataTypes.DECIMAL, allowNull: true },
      konsumsi_protein: { type: DataTypes.DECIMAL, allowNull: true },
      jumlah_kelompok_pangan_dibina: { type: DataTypes.INTEGER, allowNull: true },
      jumlah_psat_difasilitasi: { type: DataTypes.INTEGER, allowNull: true },
      jumlah_psat_tersertifikasi: { type: DataTypes.INTEGER, allowNull: true },
      kegiatan_edukasi_dilakukan: { type: DataTypes.INTEGER, allowNull: true },
      peserta_edukasi_total: { type: DataTypes.INTEGER, allowNull: true },
      kasus_keracunan_pangan: { type: DataTypes.INTEGER, allowNull: true, defaultValue: "0" },
      data_sakip_ikk: { type: DataTypes.TEXT, allowNull: true },
      data_sakip_capaian: { type: DataTypes.DECIMAL, allowNull: true },
      data_sakip_target: { type: DataTypes.DECIMAL, allowNull: true },
      anggaran_program: { type: DataTypes.DECIMAL, allowNull: true },
      realisasi_anggaran: { type: DataTypes.DECIMAL, allowNull: true },
      persentase_serapan: { type: DataTypes.DECIMAL, allowNull: true },
      permasalahan: { type: DataTypes.TEXT, allowNull: true },
      solusi: { type: DataTypes.TEXT, allowNull: true },
      rekomendasi: { type: DataTypes.TEXT, allowNull: true },
      tindak_lanjut: { type: DataTypes.TEXT, allowNull: true },
      file_laporan: { type: DataTypes.STRING(255), allowNull: true },
      file_data_pendukung: { type: DataTypes.JSONB, allowNull: true },
      ditujukan_kepada: { type: DataTypes.STRING(255), allowNull: true, defaultValue: "Sekretariat" },
      rincian_layanan: { type: DataTypes.TEXT, allowNull: true },
      penanggung_jawab: { type: DataTypes.STRING(255), allowNull: false, defaultValue: "Kepala Bidang Konsumsi" },
      pelaksana: { type: DataTypes.STRING(255), allowNull: false },
      kelompok_penerima: { type: DataTypes.STRING(255), allowNull: true, defaultValue: "Sekretariat/Pimpinan" },
      jenis_data: { type: DataTypes.STRING(255), allowNull: true },
      is_sensitive: { type: DataTypes.ENUM, allowNull: false, defaultValue: "Sensitif" },
      status: { type: DataTypes.ENUM, allowNull: false, defaultValue: "draft" },
      keterangan: { type: DataTypes.TEXT, allowNull: true },
      created_by: { type: DataTypes.INTEGER, allowNull: false },
      created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
      updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
    });
}

export async function down({ context: queryInterface }) {
  await queryInterface.dropTable('BKS-LAP');
}
