export async function up({ context: queryInterface }) {
  await queryInterface.createTable('BDS-BMB', {
      id: { type: DataTypes.INTEGER, allowNull: false, unique: true, autoIncrement: true, primaryKey: true },
      unit_kerja: { type: DataTypes.ENUM, allowNull: false },
      reported_to_sekretariat: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: "0" },
      reported_at: { type: DataTypes.DATE, allowNull: true },
      sekretariat_notes: { type: DataTypes.TEXT, allowNull: true },
      layanan_id: { type: DataTypes.STRING(10), allowNull: false },
      jenis_bimbingan: { type: DataTypes.ENUM, allowNull: false },
      nama_kegiatan: { type: DataTypes.STRING(255), allowNull: false },
      tanggal_kegiatan: { type: DataTypes.DATEONLY, allowNull: false },
      waktu_mulai: { type: DataTypes.STRING, allowNull: true },
      waktu_selesai: { type: DataTypes.STRING, allowNull: true },
      tempat: { type: DataTypes.STRING(255), allowNull: true },
      kabupaten: { type: DataTypes.STRING(100), allowNull: true },
      sasaran_peserta: { type: DataTypes.STRING(255), allowNull: true },
      jumlah_peserta: { type: DataTypes.INTEGER, allowNull: true },
      narasumber: { type: DataTypes.STRING(255), allowNull: true },
      fasilitator: { type: DataTypes.STRING(255), allowNull: true },
      materi_bimbingan: { type: DataTypes.TEXT, allowNull: true },
      metode_pelaksanaan: { type: DataTypes.ENUM, allowNull: true },
      area_supervisi: { type: DataTypes.STRING(255), allowNull: true },
      objek_supervisi: { type: DataTypes.STRING(255), allowNull: true },
      temuan_supervisi: { type: DataTypes.TEXT, allowNull: true },
      rekomendasi_supervisi: { type: DataTypes.TEXT, allowNull: true },
      topik_konsultasi: { type: DataTypes.STRING(255), allowNull: true },
      pemohon_konsultasi: { type: DataTypes.STRING(255), allowNull: true },
      instansi_pemohon: { type: DataTypes.STRING(255), allowNull: true },
      permasalahan_konsultasi: { type: DataTypes.TEXT, allowNull: true },
      jawaban_konsultasi: { type: DataTypes.TEXT, allowNull: true },
      stakeholder_difasilitasi: { type: DataTypes.TEXT, allowNull: true },
      topik_fasilitasi: { type: DataTypes.STRING(255), allowNull: true },
      hasil_fasilitasi: { type: DataTypes.TEXT, allowNull: true },
      output_kegiatan: { type: DataTypes.TEXT, allowNull: true },
      outcome_kegiatan: { type: DataTypes.TEXT, allowNull: true },
      evaluasi_kegiatan: { type: DataTypes.TEXT, allowNull: true },
      tindak_lanjut: { type: DataTypes.TEXT, allowNull: true },
      biaya_kegiatan: { type: DataTypes.DECIMAL, allowNull: true },
      sumber_anggaran: { type: DataTypes.STRING(255), allowNull: true },
      file_materi: { type: DataTypes.JSONB, allowNull: true },
      file_daftar_hadir: { type: DataTypes.STRING(255), allowNull: true },
      file_dokumentasi: { type: DataTypes.JSONB, allowNull: true },
      file_laporan: { type: DataTypes.STRING(255), allowNull: true },
      rincian_layanan: { type: DataTypes.TEXT, allowNull: true },
      penanggung_jawab: { type: DataTypes.STRING(255), allowNull: false, defaultValue: "Kepala Bidang Distribusi" },
      pelaksana: { type: DataTypes.STRING(255), allowNull: false },
      kelompok_penerima: { type: DataTypes.STRING(255), allowNull: true },
      jenis_data: { type: DataTypes.STRING(255), allowNull: true },
      is_sensitive: { type: DataTypes.ENUM, allowNull: false, defaultValue: "Biasa" },
      status: { type: DataTypes.ENUM, allowNull: false, defaultValue: "perencanaan" },
      keterangan: { type: DataTypes.TEXT, allowNull: true },
      created_by: { type: DataTypes.INTEGER, allowNull: false },
      created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
      updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
    });
}

export async function down({ context: queryInterface }) {
  await queryInterface.dropTable('BDS-BMB');
}
