export async function up({ context: queryInterface }) {
  await queryInterface.createTable('BKT-KRW', {
      id: { type: DataTypes.INTEGER, allowNull: false, unique: true, autoIncrement: true, primaryKey: true },
      unit_kerja: { type: DataTypes.ENUM, allowNull: false },
      reported_to_sekretariat: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: "0" },
      reported_at: { type: DataTypes.DATE, allowNull: true },
      sekretariat_notes: { type: DataTypes.TEXT, allowNull: true },
      layanan_id: { type: DataTypes.STRING(10), allowNull: false },
      jenis_kerawanan: { type: DataTypes.ENUM, allowNull: false },
      periode: { type: DataTypes.DATEONLY, allowNull: false },
      tahun: { type: DataTypes.INTEGER, allowNull: false },
      kabupaten: { type: DataTypes.STRING(100), allowNull: false },
      kecamatan: { type: DataTypes.STRING(100), allowNull: true },
      desa: { type: DataTypes.STRING(100), allowNull: true },
      latitude: { type: DataTypes.DECIMAL, allowNull: true },
      longitude: { type: DataTypes.DECIMAL, allowNull: true },
      tingkat_kerawanan: { type: DataTypes.ENUM, allowNull: false },
      skor_kerawanan: { type: DataTypes.DECIMAL, allowNull: true },
      indikator_ketersediaan_pangan: { type: DataTypes.DECIMAL, allowNull: true },
      indikator_akses_pangan: { type: DataTypes.DECIMAL, allowNull: true },
      indikator_pemanfaatan_pangan: { type: DataTypes.DECIMAL, allowNull: true },
      indikator_kerawanan_kesehatan: { type: DataTypes.DECIMAL, allowNull: true },
      jumlah_penduduk: { type: DataTypes.INTEGER, allowNull: true },
      jumlah_kk: { type: DataTypes.INTEGER, allowNull: true },
      jumlah_kk_miskin: { type: DataTypes.INTEGER, allowNull: true },
      persentase_kemiskinan: { type: DataTypes.DECIMAL, allowNull: true },
      stunting_prevalensi: { type: DataTypes.DECIMAL, allowNull: true },
      wasting_prevalensi: { type: DataTypes.DECIMAL, allowNull: true },
      underweight_prevalensi: { type: DataTypes.DECIMAL, allowNull: true },
      jenis_pangan_rawan: { type: DataTypes.TEXT, allowNull: true },
      stok_pangan: { type: DataTypes.DECIMAL, allowNull: true },
      satuan_stok: { type: DataTypes.STRING(20), allowNull: true, defaultValue: "kg" },
      tanggal_update_stok: { type: DataTypes.DATEONLY, allowNull: true },
      status_ketersediaan: { type: DataTypes.ENUM, allowNull: true },
      penyebab_kerawanan: { type: DataTypes.TEXT, allowNull: true },
      dampak_kerawanan: { type: DataTypes.TEXT, allowNull: true },
      rencana_aksi: { type: DataTypes.TEXT, allowNull: true },
      target_intervensi: { type: DataTypes.TEXT, allowNull: true },
      waktu_pelaksanaan: { type: DataTypes.STRING(100), allowNull: true },
      anggaran_kebutuhan: { type: DataTypes.DECIMAL, allowNull: true },
      sumber_anggaran: { type: DataTypes.STRING(255), allowNull: true },
      instansi_terkait: { type: DataTypes.TEXT, allowNull: true },
      koordinasi_dengan: { type: DataTypes.TEXT, allowNull: true },
      hasil_koordinasi: { type: DataTypes.TEXT, allowNull: true },
      tindak_lanjut_koordinasi: { type: DataTypes.TEXT, allowNull: true },
      file_peta: { type: DataTypes.STRING(255), allowNull: true },
      file_data_gis: { type: DataTypes.STRING(255), allowNull: true },
      file_laporan: { type: DataTypes.STRING(255), allowNull: true },
      file_rencana_aksi: { type: DataTypes.STRING(255), allowNull: true },
      rincian_layanan: { type: DataTypes.TEXT, allowNull: true },
      penanggung_jawab: { type: DataTypes.STRING(255), allowNull: false, defaultValue: "Kepala Bidang Ketersediaan" },
      pelaksana: { type: DataTypes.STRING(255), allowNull: false },
      kelompok_penerima: { type: DataTypes.STRING(255), allowNull: true, defaultValue: "Pemerintah Daerah/Masyarakat" },
      jenis_data: { type: DataTypes.STRING(255), allowNull: true },
      is_sensitive: { type: DataTypes.ENUM, allowNull: false, defaultValue: "Sensitif" },
      status: { type: DataTypes.ENUM, allowNull: false, defaultValue: "draft" },
      keterangan: { type: DataTypes.TEXT, allowNull: true },
      created_by: { type: DataTypes.INTEGER, allowNull: false },
      created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
      updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
    });
}

export async function down({ context: queryInterface }) {
  await queryInterface.dropTable('BKT-KRW');
}
