import { DataTypes } from 'sequelize';
import sequelize from '../config/database.js';
const BDS-MON = sequelize.define(
  'BDS-MON', {
    id: { type: DataTypes.INTEGER, allowNull: false, unique: true, autoIncrement: true, primaryKey: true },
    unit_kerja: { type: DataTypes.ENUM, allowNull: false },
    reported_to_sekretariat: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: "0" },
    reported_at: { type: DataTypes.DATE, allowNull: true },
    sekretariat_notes: { type: DataTypes.TEXT, allowNull: true },
    layanan_id: { type: DataTypes.STRING(10), allowNull: false },
    jenis_monitoring: { type: DataTypes.ENUM, allowNull: false },
    periode: { type: DataTypes.DATEONLY, allowNull: false },
    tahun: { type: DataTypes.INTEGER, allowNull: false },
    bulan: { type: DataTypes.INTEGER, allowNull: false },
    komoditas_id: { type: DataTypes.INTEGER, allowNull: true },
    nama_komoditas: { type: DataTypes.STRING(255), allowNull: true },
    wilayah_asal: { type: DataTypes.STRING(255), allowNull: true },
    wilayah_tujuan: { type: DataTypes.STRING(255), allowNull: true },
    volume_distribusi: { type: DataTypes.DECIMAL, allowNull: true },
    satuan: { type: DataTypes.STRING(20), allowNull: true, defaultValue: "kg" },
    moda_transportasi: { type: DataTypes.ENUM, allowNull: true },
    tanggal_distribusi: { type: DataTypes.DATEONLY, allowNull: true },
    frekuensi_distribusi: { type: DataTypes.INTEGER, allowNull: true },
    pasar_id: { type: DataTypes.INTEGER, allowNull: true },
    nama_pasar: { type: DataTypes.STRING(255), allowNull: true },
    stok_pasar: { type: DataTypes.DECIMAL, allowNull: true },
    stok_normal: { type: DataTypes.DECIMAL, allowNull: true },
    status_stok: { type: DataTypes.ENUM, allowNull: true, defaultValue: "Aman" },
    jenis_hambatan: { type: DataTypes.ENUM, allowNull: true },
    lokasi_hambatan: { type: DataTypes.STRING(255), allowNull: true },
    deskripsi_hambatan: { type: DataTypes.TEXT, allowNull: true },
    dampak_hambatan: { type: DataTypes.TEXT, allowNull: true },
    tingkat_hambatan: { type: DataTypes.ENUM, allowNull: true },
    solusi_hambatan: { type: DataTypes.TEXT, allowNull: true },
    status_penanganan: { type: DataTypes.ENUM, allowNull: true },
    jenis_fasilitasi: { type: DataTypes.ENUM, allowNull: true },
    penerima_fasilitasi: { type: DataTypes.STRING(255), allowNull: true },
    tindakan_fasilitasi: { type: DataTypes.TEXT, allowNull: true },
    hasil_fasilitasi: { type: DataTypes.TEXT, allowNull: true },
    instansi_koordinasi: { type: DataTypes.TEXT, allowNull: true },
    topik_koordinasi: { type: DataTypes.TEXT, allowNull: true },
    hasil_koordinasi: { type: DataTypes.TEXT, allowNull: true },
    tindak_lanjut_koordinasi: { type: DataTypes.TEXT, allowNull: true },
    analisis: { type: DataTypes.TEXT, allowNull: true },
    rekomendasi: { type: DataTypes.TEXT, allowNull: true },
    file_data: { type: DataTypes.STRING(255), allowNull: true },
    file_laporan: { type: DataTypes.STRING(255), allowNull: true },
    file_foto: { type: DataTypes.JSONB, allowNull: true },
    rincian_layanan: { type: DataTypes.TEXT, allowNull: true },
    penanggung_jawab: { type: DataTypes.STRING(255), allowNull: false, defaultValue: "Kepala Bidang Distribusi" },
    pelaksana: { type: DataTypes.STRING(255), allowNull: false },
    kelompok_penerima: { type: DataTypes.STRING(255), allowNull: true, defaultValue: "Sekretariat/Pimpinan" },
    jenis_data: { type: DataTypes.STRING(255), allowNull: true },
    is_sensitive: { type: DataTypes.ENUM, allowNull: false, defaultValue: "Sensitif" },
    status: { type: DataTypes.ENUM, allowNull: false, defaultValue: "draft" },
    keterangan: { type: DataTypes.TEXT, allowNull: true },
    created_by: { type: DataTypes.INTEGER, allowNull: false },
    created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
    updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
  }, { tableName: 'BDS-MON', timestamps: false });

export default BDS-MON;
