import { DataTypes } from 'sequelize';
import sequelize from '../config/database.js';
const BDS-HRG = sequelize.define(
  'BDS-HRG', {
    id: { type: DataTypes.INTEGER, allowNull: false, unique: true, autoIncrement: true, primaryKey: true },
    unit_kerja: { type: DataTypes.ENUM, allowNull: false },
    reported_to_sekretariat: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: "0" },
    reported_at: { type: DataTypes.DATE, allowNull: true },
    sekretariat_notes: { type: DataTypes.TEXT, allowNull: true },
    layanan_id: { type: DataTypes.STRING(10), allowNull: false },
    jenis_layanan_harga: { type: DataTypes.ENUM, allowNull: false },
    periode: { type: DataTypes.DATEONLY, allowNull: false },
    tahun: { type: DataTypes.INTEGER, allowNull: false },
    bulan: { type: DataTypes.INTEGER, allowNull: false },
    komoditas_id: { type: DataTypes.INTEGER, allowNull: true },
    nama_komoditas: { type: DataTypes.STRING(255), allowNull: true },
    pasar_id: { type: DataTypes.INTEGER, allowNull: true },
    nama_pasar: { type: DataTypes.STRING(255), allowNull: true },
    tanggal_pantau: { type: DataTypes.DATEONLY, allowNull: true },
    harga: { type: DataTypes.DECIMAL, allowNull: true },
    satuan: { type: DataTypes.STRING(20), allowNull: true, defaultValue: "kg" },
    harga_bulan_lalu: { type: DataTypes.DECIMAL, allowNull: true },
    perubahan_harga: { type: DataTypes.DECIMAL, allowNull: true },
    persentase_perubahan: { type: DataTypes.DECIMAL, allowNull: true },
    tren_harga: { type: DataTypes.ENUM, allowNull: true },
    tingkat_fluktuasi: { type: DataTypes.ENUM, allowNull: true },
    penyebab_fluktuasi: { type: DataTypes.TEXT, allowNull: true },
    dampak_fluktuasi: { type: DataTypes.TEXT, allowNull: true },
    analisis_harga: { type: DataTypes.TEXT, allowNull: true },
    prediksi_harga: { type: DataTypes.TEXT, allowNull: true },
    rekomendasi_stabilisasi: { type: DataTypes.TEXT, allowNull: true },
    jenis_operasi_pasar: { type: DataTypes.ENUM, allowNull: true },
    tanggal_operasi_pasar: { type: DataTypes.DATEONLY, allowNull: true },
    lokasi_operasi_pasar: { type: DataTypes.STRING(255), allowNull: true },
    komoditas_operasi_pasar: { type: DataTypes.TEXT, allowNull: true },
    harga_pasar_normal: { type: DataTypes.DECIMAL, allowNull: true },
    harga_operasi_pasar: { type: DataTypes.DECIMAL, allowNull: true },
    subsidi_per_unit: { type: DataTypes.DECIMAL, allowNull: true },
    volume_operasi_pasar: { type: DataTypes.DECIMAL, allowNull: true },
    jumlah_pembeli: { type: DataTypes.INTEGER, allowNull: true },
    total_nilai_subsidi: { type: DataTypes.DECIMAL, allowNull: true },
    sumber_anggaran: { type: DataTypes.STRING(255), allowNull: true },
    tanggal_rapat_tpid: { type: DataTypes.DATEONLY, allowNull: true },
    tempat_rapat_tpid: { type: DataTypes.STRING(255), allowNull: true },
    peserta_tpid: { type: DataTypes.TEXT, allowNull: true },
    agenda_tpid: { type: DataTypes.TEXT, allowNull: true },
    hasil_rapat_tpid: { type: DataTypes.TEXT, allowNull: true },
    rekomendasi_tpid: { type: DataTypes.TEXT, allowNull: true },
    tindak_lanjut_tpid: { type: DataTypes.TEXT, allowNull: true },
    inflasi_pangan: { type: DataTypes.DECIMAL, allowNull: true },
    target_inflasi_tpid: { type: DataTypes.DECIMAL, allowNull: true, defaultValue: "2.50" },
    status_inflasi: { type: DataTypes.ENUM, allowNull: true },
    file_data_harga: { type: DataTypes.STRING(255), allowNull: true },
    file_notulensi_tpid: { type: DataTypes.STRING(255), allowNull: true },
    file_foto_operasi_pasar: { type: DataTypes.JSONB, allowNull: true },
    file_laporan: { type: DataTypes.STRING(255), allowNull: true },
    rincian_layanan: { type: DataTypes.TEXT, allowNull: true },
    penanggung_jawab: { type: DataTypes.STRING(255), allowNull: false, defaultValue: "Kepala Bidang Distribusi" },
    pelaksana: { type: DataTypes.STRING(255), allowNull: false },
    kelompok_penerima: { type: DataTypes.STRING(255), allowNull: true, defaultValue: "Sekretariat/Pimpinan/TPID" },
    jenis_data: { type: DataTypes.STRING(255), allowNull: true },
    is_sensitive: { type: DataTypes.ENUM, allowNull: false, defaultValue: "Sensitif" },
    status: { type: DataTypes.ENUM, allowNull: false, defaultValue: "draft" },
    keterangan: { type: DataTypes.TEXT, allowNull: true },
    created_by: { type: DataTypes.INTEGER, allowNull: false },
    created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
    updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
  }, { tableName: 'BDS-HRG', timestamps: false });

export default BDS-HRG;
