import { DataTypes } from 'sequelize';
import sequelize from '../config/database.js';
const BKS-DVR = sequelize.define(
  'BKS-DVR', {
    id: { type: DataTypes.INTEGER, allowNull: false, unique: true, autoIncrement: true, primaryKey: true },
    unit_kerja: { type: DataTypes.ENUM, allowNull: false },
    reported_to_sekretariat: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: "0" },
    reported_at: { type: DataTypes.DATE, allowNull: true },
    sekretariat_notes: { type: DataTypes.TEXT, allowNull: true },
    layanan_id: { type: DataTypes.STRING(10), allowNull: false },
    jenis_kegiatan: { type: DataTypes.ENUM, allowNull: false },
    nama_kegiatan: { type: DataTypes.STRING(255), allowNull: false },
    tanggal_kegiatan: { type: DataTypes.DATEONLY, allowNull: true },
    lokasi_kegiatan: { type: DataTypes.STRING(255), allowNull: true },
    kabupaten: { type: DataTypes.STRING(100), allowNull: true },
    kecamatan: { type: DataTypes.STRING(100), allowNull: true },
    desa: { type: DataTypes.STRING(100), allowNull: true },
    jenis_pangan_lokal: { type: DataTypes.TEXT, allowNull: true },
    potensi_pangan_lokal: { type: DataTypes.TEXT, allowNull: true },
    pengembangan_dilakukan: { type: DataTypes.TEXT, allowNull: true },
    hasil_pengembangan: { type: DataTypes.TEXT, allowNull: true },
    jumlah_kk_pekarangan: { type: DataTypes.INTEGER, allowNull: true },
    luas_pekarangan_total: { type: DataTypes.DECIMAL, allowNull: true },
    jenis_tanaman: { type: DataTypes.TEXT, allowNull: true },
    hasil_panen_pekarangan: { type: DataTypes.DECIMAL, allowNull: true },
    nilai_ekonomi: { type: DataTypes.DECIMAL, allowNull: true },
    jenis_kampanye: { type: DataTypes.ENUM, allowNull: true },
    tema_kampanye: { type: DataTypes.STRING(255), allowNull: true },
    pesan_kampanye: { type: DataTypes.TEXT, allowNull: true },
    media_kampanye: { type: DataTypes.TEXT, allowNull: true },
    jangkauan_kampanye: { type: DataTypes.INTEGER, allowNull: true },
    materi_edukasi_b2sa: { type: DataTypes.TEXT, allowNull: true },
    metode_edukasi: { type: DataTypes.ENUM, allowNull: true },
    sasaran_edukasi: { type: DataTypes.STRING(255), allowNull: true },
    jumlah_peserta_edukasi: { type: DataTypes.INTEGER, allowNull: true },
    nama_kelompok_pangan: { type: DataTypes.STRING(255), allowNull: true },
    jenis_kelompok: { type: DataTypes.ENUM, allowNull: true },
    jumlah_anggota_kelompok: { type: DataTypes.INTEGER, allowNull: true },
    kegiatan_kelompok: { type: DataTypes.TEXT, allowNull: true },
    frekuensi_pendampingan: { type: DataTypes.INTEGER, allowNull: true },
    materi_pendampingan: { type: DataTypes.TEXT, allowNull: true },
    produk_kelompok: { type: DataTypes.TEXT, allowNull: true },
    omzet_kelompok: { type: DataTypes.DECIMAL, allowNull: true },
    bantuan_diberikan: { type: DataTypes.TEXT, allowNull: true },
    nilai_bantuan: { type: DataTypes.DECIMAL, allowNull: true },
    output_kegiatan: { type: DataTypes.TEXT, allowNull: true },
    outcome_kegiatan: { type: DataTypes.TEXT, allowNull: true },
    dampak: { type: DataTypes.TEXT, allowNull: true },
    kendala: { type: DataTypes.TEXT, allowNull: true },
    solusi: { type: DataTypes.TEXT, allowNull: true },
    biaya_kegiatan: { type: DataTypes.DECIMAL, allowNull: true },
    sumber_anggaran: { type: DataTypes.STRING(255), allowNull: true },
    file_dokumentasi: { type: DataTypes.JSONB, allowNull: true },
    file_laporan: { type: DataTypes.STRING(255), allowNull: true },
    rincian_layanan: { type: DataTypes.TEXT, allowNull: true },
    penanggung_jawab: { type: DataTypes.STRING(255), allowNull: false, defaultValue: "Kepala Bidang Konsumsi" },
    pelaksana: { type: DataTypes.STRING(255), allowNull: false },
    kelompok_penerima: { type: DataTypes.STRING(255), allowNull: true, defaultValue: "Masyarakat" },
    jenis_data: { type: DataTypes.STRING(255), allowNull: true },
    is_sensitive: { type: DataTypes.ENUM, allowNull: false, defaultValue: "Biasa" },
    status: { type: DataTypes.ENUM, allowNull: false, defaultValue: "perencanaan" },
    keterangan: { type: DataTypes.TEXT, allowNull: true },
    created_by: { type: DataTypes.INTEGER, allowNull: false },
    created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
    updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
  }, { tableName: 'BKS-DVR', timestamps: false });

export default BKS-DVR;
