import { DataTypes } from 'sequelize';
import sequelize from '../config/database.js';
const BKS-KMN = sequelize.define(
  'BKS-KMN', {
    id: { type: DataTypes.INTEGER, allowNull: false, unique: true, autoIncrement: true, primaryKey: true },
    unit_kerja: { type: DataTypes.ENUM, allowNull: false },
    reported_to_sekretariat: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: "0" },
    reported_at: { type: DataTypes.DATE, allowNull: true },
    sekretariat_notes: { type: DataTypes.TEXT, allowNull: true },
    layanan_id: { type: DataTypes.STRING(10), allowNull: false },
    jenis_kegiatan_keamanan: { type: DataTypes.ENUM, allowNull: false },
    tanggal_kegiatan: { type: DataTypes.DATEONLY, allowNull: true },
    lokasi: { type: DataTypes.STRING(255), allowNull: true },
    objek_pembinaan: { type: DataTypes.STRING(255), allowNull: true },
    jenis_pangan_segar: { type: DataTypes.TEXT, allowNull: true },
    aspek_pembinaan: { type: DataTypes.TEXT, allowNull: true },
    jumlah_pelaku_dibina: { type: DataTypes.INTEGER, allowNull: true },
    hasil_pembinaan: { type: DataTypes.TEXT, allowNull: true },
    tindak_lanjut_pembinaan: { type: DataTypes.TEXT, allowNull: true },
    materi_sosialisasi: { type: DataTypes.TEXT, allowNull: true },
    sasaran_sosialisasi: { type: DataTypes.STRING(255), allowNull: true },
    jumlah_peserta_sosialisasi: { type: DataTypes.INTEGER, allowNull: true },
    metode_sosialisasi: { type: DataTypes.ENUM, allowNull: true },
    psat_nama_usaha: { type: DataTypes.STRING(255), allowNull: true },
    psat_jenis_usaha: { type: DataTypes.ENUM, allowNull: true },
    psat_alamat: { type: DataTypes.STRING(255), allowNull: true },
    psat_pemilik: { type: DataTypes.STRING(255), allowNull: true },
    psat_status_sertifikat: { type: DataTypes.ENUM, allowNull: true },
    psat_jenis_fasilitasi: { type: DataTypes.TEXT, allowNull: true },
    psat_kendala: { type: DataTypes.TEXT, allowNull: true },
    psat_solusi: { type: DataTypes.TEXT, allowNull: true },
    instansi_koordinasi_pengawasan: { type: DataTypes.TEXT, allowNull: true },
    topik_koordinasi: { type: DataTypes.TEXT, allowNull: true },
    hasil_koordinasi: { type: DataTypes.TEXT, allowNull: true },
    tindak_lanjut_koordinasi: { type: DataTypes.TEXT, allowNull: true },
    tanggal_rapat: { type: DataTypes.DATEONLY, allowNull: true },
    pemohon_rekomendasi: { type: DataTypes.STRING(255), allowNull: true },
    instansi_pemohon: { type: DataTypes.STRING(255), allowNull: true },
    permasalahan: { type: DataTypes.TEXT, allowNull: true },
    analisis_teknis: { type: DataTypes.TEXT, allowNull: true },
    rekomendasi_teknis: { type: DataTypes.TEXT, allowNull: true },
    dasar_rekomendasi: { type: DataTypes.TEXT, allowNull: true },
    status_rekomendasi: { type: DataTypes.ENUM, allowNull: true },
    nomor_rekomendasi: { type: DataTypes.STRING(100), allowNull: true },
    tanggal_rekomendasi: { type: DataTypes.DATEONLY, allowNull: true },
    file_surat_rekomendasi: { type: DataTypes.STRING(255), allowNull: true },
    file_dokumentasi: { type: DataTypes.JSONB, allowNull: true },
    file_laporan: { type: DataTypes.STRING(255), allowNull: true },
    rincian_layanan: { type: DataTypes.TEXT, allowNull: true },
    penanggung_jawab: { type: DataTypes.STRING(255), allowNull: false, defaultValue: "Kepala Bidang Konsumsi" },
    pelaksana: { type: DataTypes.STRING(255), allowNull: false },
    kelompok_penerima: { type: DataTypes.STRING(255), allowNull: true },
    jenis_data: { type: DataTypes.STRING(255), allowNull: true },
    is_sensitive: { type: DataTypes.ENUM, allowNull: false, defaultValue: "Sensitif" },
    status: { type: DataTypes.ENUM, allowNull: false, defaultValue: "draft" },
    keterangan: { type: DataTypes.TEXT, allowNull: true },
    created_by: { type: DataTypes.INTEGER, allowNull: false },
    created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
    updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
  }, { tableName: 'BKS-KMN', timestamps: false });

export default BKS-KMN;
