import { DataTypes } from 'sequelize';
import sequelize from '../config/database.js';
const BKS-KBJ = sequelize.define(
  'BKS-KBJ', {
    id: { type: DataTypes.INTEGER, allowNull: false, unique: true, autoIncrement: true, primaryKey: true },
    unit_kerja: { type: DataTypes.ENUM, allowNull: false },
    reported_to_sekretariat: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: "0" },
    reported_at: { type: DataTypes.DATE, allowNull: true },
    sekretariat_notes: { type: DataTypes.TEXT, allowNull: true },
    layanan_id: { type: DataTypes.STRING(10), allowNull: false },
    jenis_kebijakan: { type: DataTypes.ENUM, allowNull: false },
    nomor_dokumen: { type: DataTypes.STRING(100), allowNull: true },
    tanggal_dokumen: { type: DataTypes.DATEONLY, allowNull: false },
    periode: { type: DataTypes.STRING(50), allowNull: true },
    tahun: { type: DataTypes.INTEGER, allowNull: false },
    judul_kebijakan: { type: DataTypes.STRING(255), allowNull: false },
    latar_belakang: { type: DataTypes.TEXT, allowNull: true },
    ruang_lingkup: { type: DataTypes.TEXT, allowNull: true },
    tujuan: { type: DataTypes.TEXT, allowNull: true },
    sasaran: { type: DataTypes.TEXT, allowNull: true },
    prinsip_b2sa: { type: DataTypes.TEXT, allowNull: true },
    pedoman_b2sa: { type: DataTypes.TEXT, allowNull: true },
    skor_pph_target: { type: DataTypes.DECIMAL, allowNull: true, defaultValue: "90" },
    strategi_penganekaragaman: { type: DataTypes.TEXT, allowNull: true },
    pangan_lokal_prioritas: { type: DataTypes.TEXT, allowNull: true },
    target_konsumsi_lokal: { type: DataTypes.TEXT, allowNull: true },
    intervensi_konsumsi: { type: DataTypes.TEXT, allowNull: true },
    kelompok_sasaran: { type: DataTypes.TEXT, allowNull: true },
    wilayah_prioritas: { type: DataTypes.TEXT, allowNull: true },
    koordinasi_dengan: { type: DataTypes.TEXT, allowNull: true },
    hasil_sinkronisasi: { type: DataTypes.TEXT, allowNull: true },
    rekomendasi: { type: DataTypes.TEXT, allowNull: true },
    indikator_keberhasilan: { type: DataTypes.TEXT, allowNull: true },
    target_capaian: { type: DataTypes.TEXT, allowNull: true },
    dasar_hukum: { type: DataTypes.TEXT, allowNull: true },
    tindak_lanjut: { type: DataTypes.TEXT, allowNull: true },
    file_dokumen: { type: DataTypes.STRING(255), allowNull: true },
    file_lampiran: { type: DataTypes.JSONB, allowNull: true },
    rincian_layanan: { type: DataTypes.TEXT, allowNull: true },
    penanggung_jawab: { type: DataTypes.STRING(255), allowNull: false, defaultValue: "Kepala Bidang Konsumsi" },
    pelaksana: { type: DataTypes.STRING(255), allowNull: false },
    kelompok_penerima: { type: DataTypes.STRING(255), allowNull: true },
    jenis_data: { type: DataTypes.STRING(255), allowNull: true },
    is_sensitive: { type: DataTypes.ENUM, allowNull: false, defaultValue: "Sensitif" },
    status: { type: DataTypes.ENUM, allowNull: false, defaultValue: "draft" },
    keterangan: { type: DataTypes.TEXT, allowNull: true },
    created_by: { type: DataTypes.INTEGER, allowNull: false },
    created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
    updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
  }, { tableName: 'BKS-KBJ', timestamps: false });

export default BKS-KBJ;
