import { DataTypes } from 'sequelize';
import sequelize from '../config/database.js';
const BKT-PGD = sequelize.define(
  'BKT-PGD', {
    id: { type: DataTypes.INTEGER, allowNull: false, unique: true, autoIncrement: true, primaryKey: true },
    unit_kerja: { type: DataTypes.ENUM, allowNull: false },
    reported_to_sekretariat: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: "0" },
    reported_at: { type: DataTypes.DATE, allowNull: true },
    sekretariat_notes: { type: DataTypes.TEXT, allowNull: true },
    layanan_id: { type: DataTypes.STRING(10), allowNull: false },
    jenis_pengendalian: { type: DataTypes.ENUM, allowNull: false },
    periode: { type: DataTypes.DATEONLY, allowNull: false },
    tahun: { type: DataTypes.INTEGER, allowNull: false },
    bulan: { type: DataTypes.INTEGER, allowNull: false },
    komoditas_id: { type: DataTypes.INTEGER, allowNull: true },
    nama_komoditas: { type: DataTypes.STRING(255), allowNull: true },
    kabupaten: { type: DataTypes.STRING(100), allowNull: true },
    kecamatan: { type: DataTypes.STRING(100), allowNull: true },
    luas_tanam: { type: DataTypes.DECIMAL, allowNull: true },
    luas_panen: { type: DataTypes.DECIMAL, allowNull: true },
    produktivitas: { type: DataTypes.DECIMAL, allowNull: true },
    produksi_total: { type: DataTypes.DECIMAL, allowNull: true },
    target_produksi: { type: DataTypes.DECIMAL, allowNull: true },
    persentase_capaian: { type: DataTypes.DECIMAL, allowNull: true },
    pasokan_lokal: { type: DataTypes.DECIMAL, allowNull: true },
    pasokan_luar_daerah: { type: DataTypes.DECIMAL, allowNull: true },
    pasokan_impor: { type: DataTypes.DECIMAL, allowNull: true },
    total_pasokan: { type: DataTypes.DECIMAL, allowNull: true },
    konsumsi_estimasi: { type: DataTypes.DECIMAL, allowNull: true },
    stok_awal: { type: DataTypes.DECIMAL, allowNull: true },
    stok_akhir: { type: DataTypes.DECIMAL, allowNull: true },
    surplus_defisit: { type: DataTypes.DECIMAL, allowNull: true },
    status_ketersediaan: { type: DataTypes.ENUM, allowNull: true, defaultValue: "Aman" },
    tingkat_kerawanan: { type: DataTypes.ENUM, allowNull: true, defaultValue: "Aman" },
    early_warning_status: { type: DataTypes.ENUM, allowNull: true, defaultValue: "Normal" },
    indikator_early_warning: { type: DataTypes.TEXT, allowNull: true },
    rekomendasi_ews: { type: DataTypes.TEXT, allowNull: true },
    neraca_pangan_ketersediaan: { type: DataTypes.DECIMAL, allowNull: true },
    neraca_pangan_penggunaan: { type: DataTypes.DECIMAL, allowNull: true },
    sumber_data: { type: DataTypes.STRING(255), allowNull: true },
    metode_pengumpulan: { type: DataTypes.ENUM, allowNull: true },
    validitas_data: { type: DataTypes.ENUM, allowNull: true, defaultValue: "Valid" },
    analisis: { type: DataTypes.TEXT, allowNull: true },
    kendala: { type: DataTypes.TEXT, allowNull: true },
    rekomendasi: { type: DataTypes.TEXT, allowNull: true },
    file_data: { type: DataTypes.STRING(255), allowNull: true },
    file_laporan: { type: DataTypes.STRING(255), allowNull: true },
    rincian_layanan: { type: DataTypes.TEXT, allowNull: true },
    penanggung_jawab: { type: DataTypes.STRING(255), allowNull: false, defaultValue: "Kepala Bidang Ketersediaan" },
    pelaksana: { type: DataTypes.STRING(255), allowNull: false },
    kelompok_penerima: { type: DataTypes.STRING(255), allowNull: true, defaultValue: "Sekretariat/Pimpinan" },
    jenis_data: { type: DataTypes.STRING(255), allowNull: true },
    is_sensitive: { type: DataTypes.ENUM, allowNull: false, defaultValue: "Sensitif" },
    status: { type: DataTypes.ENUM, allowNull: false, defaultValue: "draft" },
    keterangan: { type: DataTypes.TEXT, allowNull: true },
    created_by: { type: DataTypes.INTEGER, allowNull: false },
    created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
    updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
  }, { tableName: 'BKT-PGD', timestamps: false });

export default BKT-PGD;
