import { DataTypes } from 'sequelize';
import sequelize from '../config/database.js';
const BKT-FSL = sequelize.define(
  'BKT-FSL', {
    id: { type: DataTypes.INTEGER, allowNull: false, unique: true, autoIncrement: true, primaryKey: true },
    unit_kerja: { type: DataTypes.ENUM, allowNull: false },
    reported_to_sekretariat: { type: DataTypes.BOOLEAN, allowNull: false, defaultValue: "0" },
    reported_at: { type: DataTypes.DATE, allowNull: true },
    sekretariat_notes: { type: DataTypes.TEXT, allowNull: true },
    layanan_id: { type: DataTypes.STRING(10), allowNull: false, defaultValue: "LY066" },
    jenis_fasilitasi: { type: DataTypes.ENUM, allowNull: false },
    nama_program: { type: DataTypes.STRING(255), allowNull: false },
    periode: { type: DataTypes.DATEONLY, allowNull: false },
    tahun: { type: DataTypes.INTEGER, allowNull: false },
    wilayah_sasaran: { type: DataTypes.STRING(255), allowNull: true },
    kelompok_sasaran: { type: DataTypes.STRING(255), allowNull: true },
    jumlah_penerima: { type: DataTypes.INTEGER, allowNull: true },
    jenis_intervensi: { type: DataTypes.ENUM, allowNull: true },
    volume_bantuan: { type: DataTypes.DECIMAL, allowNull: true },
    satuan: { type: DataTypes.STRING(50), allowNull: true },
    nilai_bantuan: { type: DataTypes.DECIMAL, allowNull: true },
    sumber_bantuan: { type: DataTypes.STRING(255), allowNull: true },
    instansi_pemberi: { type: DataTypes.STRING(255), allowNull: true },
    tanggal_penyaluran: { type: DataTypes.DATEONLY, allowNull: true },
    lokasi_penyaluran: { type: DataTypes.STRING(255), allowNull: true },
    penanggung_jawab_penyaluran: { type: DataTypes.STRING(255), allowNull: true },
    target_output: { type: DataTypes.TEXT, allowNull: true },
    target_outcome: { type: DataTypes.TEXT, allowNull: true },
    realisasi: { type: DataTypes.TEXT, allowNull: true },
    kendala: { type: DataTypes.TEXT, allowNull: true },
    solusi: { type: DataTypes.TEXT, allowNull: true },
    dampak: { type: DataTypes.TEXT, allowNull: true },
    dokumentasi_kegiatan: { type: DataTypes.JSONB, allowNull: true },
    file_proposal: { type: DataTypes.STRING(255), allowNull: true },
    file_bast: { type: DataTypes.STRING(255), allowNull: true },
    file_laporan: { type: DataTypes.STRING(255), allowNull: true },
    rincian_layanan: { type: DataTypes.TEXT, allowNull: true },
    penanggung_jawab: { type: DataTypes.STRING(255), allowNull: false, defaultValue: "Kepala Bidang Ketersediaan" },
    pelaksana: { type: DataTypes.STRING(255), allowNull: false },
    kelompok_penerima: { type: DataTypes.STRING(255), allowNull: true },
    jenis_data: { type: DataTypes.STRING(255), allowNull: true },
    is_sensitive: { type: DataTypes.ENUM, allowNull: false, defaultValue: "Biasa" },
    status: { type: DataTypes.ENUM, allowNull: false, defaultValue: "perencanaan" },
    keterangan: { type: DataTypes.TEXT, allowNull: true },
    created_by: { type: DataTypes.INTEGER, allowNull: false },
    created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
    updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
  }, { tableName: 'BKT-FSL', timestamps: false });

export default BKT-FSL;
