import { DataTypes } from 'sequelize';
import sequelize from '../config/database.js';
const SEK-REN = sequelize.define(
  'SEK-REN', {
    id: { type: DataTypes.INTEGER, allowNull: false, unique: true, autoIncrement: true, primaryKey: true },
    layanan_id: { type: DataTypes.STRING(10), allowNull: false },
    jenis_layanan_perencanaan: { type: DataTypes.ENUM, allowNull: false },
    tahun_perencanaan: { type: DataTypes.INTEGER, allowNull: false },
    periode_renstra: { type: DataTypes.STRING(20), allowNull: true },
    visi: { type: DataTypes.TEXT, allowNull: true },
    misi: { type: DataTypes.TEXT, allowNull: true },
    tujuan: { type: DataTypes.TEXT, allowNull: true },
    sasaran: { type: DataTypes.TEXT, allowNull: true },
    strategi: { type: DataTypes.TEXT, allowNull: true },
    kode_program: { type: DataTypes.STRING(50), allowNull: true },
    nama_program: { type: DataTypes.STRING(255), allowNull: true },
    kode_kegiatan: { type: DataTypes.STRING(50), allowNull: true },
    nama_kegiatan: { type: DataTypes.STRING(255), allowNull: true },
    indikator_kinerja: { type: DataTypes.TEXT, allowNull: true },
    target_kinerja: { type: DataTypes.STRING(255), allowNull: true },
    satuan_target: { type: DataTypes.STRING(50), allowNull: true },
    realisasi_kinerja: { type: DataTypes.STRING(255), allowNull: true },
    persentase_capaian: { type: DataTypes.DECIMAL, allowNull: true },
    pagu_anggaran: { type: DataTypes.DECIMAL, allowNull: true },
    bidang_pelaksana: { type: DataTypes.STRING(255), allowNull: true },
    penanggung_jawab_kegiatan: { type: DataTypes.STRING(255), allowNull: true },
    waktu_pelaksanaan: { type: DataTypes.STRING(100), allowNull: true },
    output: { type: DataTypes.TEXT, allowNull: true },
    outcome: { type: DataTypes.TEXT, allowNull: true },
    kendala: { type: DataTypes.TEXT, allowNull: true },
    solusi: { type: DataTypes.TEXT, allowNull: true },
    rekomendasi: { type: DataTypes.TEXT, allowNull: true },
    status_sinkronisasi: { type: DataTypes.ENUM, allowNull: true },
    file_renstra: { type: DataTypes.STRING(255), allowNull: true },
    file_renja: { type: DataTypes.STRING(255), allowNull: true },
    file_lakip: { type: DataTypes.STRING(255), allowNull: true },
    file_laporan_kinerja: { type: DataTypes.STRING(255), allowNull: true },
    file_pendukung: { type: DataTypes.JSONB, allowNull: true },
    penanggung_jawab: { type: DataTypes.STRING(255), allowNull: false, defaultValue: "Fungsional Perencana" },
    pelaksana: { type: DataTypes.STRING(255), allowNull: false },
    is_sensitive: { type: DataTypes.ENUM, allowNull: false, defaultValue: "Sensitif" },
    status: { type: DataTypes.ENUM, allowNull: false, defaultValue: "draft" },
    keterangan: { type: DataTypes.TEXT, allowNull: true },
    created_by: { type: DataTypes.INTEGER, allowNull: false },
    created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
    updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
  }, { tableName: 'SEK-REN', timestamps: false });

export default SEK-REN;
