import { DataTypes } from 'sequelize';
import sequelize from '../config/database.js';
const SEK-RMH = sequelize.define(
  'SEK-RMH', {
    id: { type: DataTypes.INTEGER, allowNull: false, unique: true, autoIncrement: true, primaryKey: true },
    layanan_id: { type: DataTypes.STRING(10), allowNull: false },
    jenis_layanan_rumah_tangga: { type: DataTypes.ENUM, allowNull: false },
    nomor_sppd: { type: DataTypes.STRING(100), allowNull: true },
    nomor_st: { type: DataTypes.STRING(100), allowNull: true },
    nama_pegawai: { type: DataTypes.STRING(255), allowNull: true },
    nip_pegawai: { type: DataTypes.STRING(18), allowNull: true },
    tujuan: { type: DataTypes.STRING(255), allowNull: true },
    keperluan: { type: DataTypes.TEXT, allowNull: true },
    tanggal_berangkat: { type: DataTypes.DATEONLY, allowNull: true },
    tanggal_kembali: { type: DataTypes.DATEONLY, allowNull: true },
    lama_hari: { type: DataTypes.INTEGER, allowNull: true },
    biaya_transport: { type: DataTypes.DECIMAL, allowNull: true },
    biaya_penginapan: { type: DataTypes.DECIMAL, allowNull: true },
    uang_harian: { type: DataTypes.DECIMAL, allowNull: true },
    total_biaya: { type: DataTypes.DECIMAL, allowNull: true },
    area_kebersihan: { type: DataTypes.STRING(255), allowNull: true },
    jadwal_kebersihan: { type: DataTypes.ENUM, allowNull: true },
    petugas_kebersihan: { type: DataTypes.STRING(255), allowNull: true },
    pos_keamanan: { type: DataTypes.STRING(100), allowNull: true },
    shift_keamanan: { type: DataTypes.ENUM, allowNull: true },
    petugas_keamanan: { type: DataTypes.STRING(255), allowNull: true },
    jenis_fasilitas: { type: DataTypes.STRING(255), allowNull: true },
    kondisi_fasilitas: { type: DataTypes.ENUM, allowNull: true, defaultValue: "Baik" },
    nama_ruang_rapat: { type: DataTypes.STRING(255), allowNull: true },
    kapasitas: { type: DataTypes.INTEGER, allowNull: true },
    tanggal_pemesanan: { type: DataTypes.DATEONLY, allowNull: true },
    jam_mulai: { type: DataTypes.STRING, allowNull: true },
    jam_selesai: { type: DataTypes.STRING, allowNull: true },
    pemesan: { type: DataTypes.STRING(255), allowNull: true },
    nomor_polisi: { type: DataTypes.STRING(20), allowNull: true },
    jenis_kendaraan: { type: DataTypes.ENUM, allowNull: true },
    driver: { type: DataTypes.STRING(255), allowNull: true },
    tanggal_pakai: { type: DataTypes.DATEONLY, allowNull: true },
    km_awal: { type: DataTypes.INTEGER, allowNull: true },
    km_akhir: { type: DataTypes.INTEGER, allowNull: true },
    bbm_liter: { type: DataTypes.DECIMAL, allowNull: true },
    file_sppd: { type: DataTypes.STRING(255), allowNull: true },
    file_laporan: { type: DataTypes.STRING(255), allowNull: true },
    penanggung_jawab: { type: DataTypes.STRING(255), allowNull: false, defaultValue: "Kasubbag Umum" },
    pelaksana: { type: DataTypes.STRING(255), allowNull: false },
    is_sensitive: { type: DataTypes.ENUM, allowNull: false, defaultValue: "Biasa" },
    status: { type: DataTypes.ENUM, allowNull: false, defaultValue: "pending" },
    keterangan: { type: DataTypes.TEXT, allowNull: true },
    created_by: { type: DataTypes.INTEGER, allowNull: false },
    created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
    updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
  }, { tableName: 'SEK-RMH', timestamps: false });

export default SEK-RMH;
