import { DataTypes } from 'sequelize';
import sequelize from '../config/database.js';
const UPT-INS = sequelize.define(
  'UPT-INS', {
    id: { type: DataTypes.INTEGER, allowNull: false, unique: true, autoIncrement: true, primaryKey: true },
    layanan_id: { type: DataTypes.STRING(10), allowNull: false },
    jenis_layanan_inspeksi: { type: DataTypes.ENUM, allowNull: false },
    nomor_inspeksi: { type: DataTypes.STRING(100), allowNull: true },
    nomor_audit_ins: { type: DataTypes.STRING(100), allowNull: true },
    tanggal_inspeksi: { type: DataTypes.DATEONLY, allowNull: true },
    lokasi_inspeksi: { type: DataTypes.STRING(255), allowNull: true },
    objek_inspeksi: { type: DataTypes.STRING(255), allowNull: true },
    nama_usaha_inspeksi: { type: DataTypes.STRING(255), allowNull: true },
    pemilik_usaha_inspeksi: { type: DataTypes.STRING(255), allowNull: true },
    alamat_inspeksi: { type: DataTypes.TEXT, allowNull: true },
    tim_inspeksi: { type: DataTypes.TEXT, allowNull: true },
    jenis_sertifikasi_audit: { type: DataTypes.ENUM, allowNull: true },
    audit_awal_ulang: { type: DataTypes.ENUM, allowNull: true, defaultValue: "Awal" },
    alasan_audit_ulang: { type: DataTypes.TEXT, allowNull: true },
    checklist_inspeksi: { type: DataTypes.JSONB, allowNull: true },
    skor_inspeksi: { type: DataTypes.DECIMAL, allowNull: true },
    hasil_inspeksi: { type: DataTypes.ENUM, allowNull: true },
    temuan_inspeksi: { type: DataTypes.TEXT, allowNull: true },
    catatan_inspeksi: { type: DataTypes.TEXT, allowNull: true },
    rekomendasi_inspeksi: { type: DataTypes.TEXT, allowNull: true },
    tindakan_korektif_inspeksi: { type: DataTypes.TEXT, allowNull: true },
    batas_waktu_ins: { type: DataTypes.DATEONLY, allowNull: true },
    jenis_sampel_pangan: { type: DataTypes.STRING(255), allowNull: true },
    lokasi_pengambilan: { type: DataTypes.STRING(255), allowNull: true },
    tanggal_sampling: { type: DataTypes.DATEONLY, allowNull: true },
    sampler: { type: DataTypes.STRING(255), allowNull: true },
    jumlah_sampel_diambil: { type: DataTypes.INTEGER, allowNull: true },
    metode_sampling: { type: DataTypes.STRING(255), allowNull: true },
    kondisi_sampel: { type: DataTypes.ENUM, allowNull: true, defaultValue: "Baik" },
    penyimpanan_sampel: { type: DataTypes.STRING(255), allowNull: true },
    nomor_sampel: { type: DataTypes.STRING(100), allowNull: true },
    parameter_pengujian: { type: DataTypes.TEXT, allowNull: true },
    metode_pengujian: { type: DataTypes.STRING(255), allowNull: true },
    analis_pengujian: { type: DataTypes.STRING(255), allowNull: true },
    tanggal_pengujian_mulai: { type: DataTypes.DATEONLY, allowNull: true },
    tanggal_pengujian_selesai: { type: DataTypes.DATEONLY, allowNull: true },
    hasil_pengujian: { type: DataTypes.TEXT, allowNull: true },
    kesimpulan_pengujian: { type: DataTypes.ENUM, allowNull: true },
    tanggal_verifikasi_uji: { type: DataTypes.DATEONLY, allowNull: true },
    verifikator_uji: { type: DataTypes.STRING(255), allowNull: true },
    hasil_verifikasi_uji: { type: DataTypes.ENUM, allowNull: true },
    catatan_verifikasi_uji: { type: DataTypes.TEXT, allowNull: true },
    jenis_rekomendasi_pengawasan: { type: DataTypes.ENUM, allowNull: true },
    isi_rekomendasi_pengawasan: { type: DataTypes.TEXT, allowNull: true },
    tindak_lanjut_rekomendasi: { type: DataTypes.TEXT, allowNull: true },
    status_rekomendasi_pengawasan: { type: DataTypes.ENUM, allowNull: true, defaultValue: "Open" },
    jenis_pembinaan: { type: DataTypes.ENUM, allowNull: true },
    tanggal_pembinaan: { type: DataTypes.DATEONLY, allowNull: true },
    lokasi_pembinaan: { type: DataTypes.STRING(255), allowNull: true },
    penerima_pembinaan: { type: DataTypes.STRING(255), allowNull: true },
    materi_pembinaan: { type: DataTypes.TEXT, allowNull: true },
    hasil_pembinaan: { type: DataTypes.TEXT, allowNull: true },
    opd_dikoordinasikan: { type: DataTypes.TEXT, allowNull: true },
    tanggal_koordinasi: { type: DataTypes.DATEONLY, allowNull: true },
    topik_koordinasi_opd: { type: DataTypes.TEXT, allowNull: true },
    hasil_koordinasi_opd: { type: DataTypes.TEXT, allowNull: true },
    tindak_lanjut_koordinasi: { type: DataTypes.TEXT, allowNull: true },
    objek_monitoring: { type: DataTypes.STRING(255), allowNull: true },
    tanggal_monitoring: { type: DataTypes.DATEONLY, allowNull: true },
    hasil_monitoring: { type: DataTypes.TEXT, allowNull: true },
    status_perbaikan_monitoring: { type: DataTypes.ENUM, allowNull: true },
    tanggal_penjadwalan: { type: DataTypes.DATEONLY, allowNull: true },
    jenis_kegiatan_jadwal: { type: DataTypes.ENUM, allowNull: true },
    petugas_dijadwalkan: { type: DataTypes.TEXT, allowNull: true },
    status_jadwal: { type: DataTypes.ENUM, allowNull: true, defaultValue: "Scheduled" },
    jenis_layanan_lapangan: { type: DataTypes.STRING(255), allowNull: true },
    tanggal_pelaksanaan: { type: DataTypes.DATEONLY, allowNull: true },
    lokasi_pelaksanaan: { type: DataTypes.STRING(255), allowNull: true },
    tim_pelaksana: { type: DataTypes.TEXT, allowNull: true },
    hasil_pelaksanaan: { type: DataTypes.TEXT, allowNull: true },
    periode_pelaporan_teknis: { type: DataTypes.DATEONLY, allowNull: true },
    jenis_laporan_teknis: { type: DataTypes.ENUM, allowNull: true },
    total_inspeksi: { type: DataTypes.INTEGER, allowNull: true },
    total_audit_teknis: { type: DataTypes.INTEGER, allowNull: true },
    total_sampel_diambil: { type: DataTypes.INTEGER, allowNull: true },
    total_pengujian_teknis: { type: DataTypes.INTEGER, allowNull: true },
    persentase_kelulusan_teknis: { type: DataTypes.DECIMAL, allowNull: true },
    temuan_tidak_sesuai: { type: DataTypes.INTEGER, allowNull: true },
    tindakan_pengawasan: { type: DataTypes.INTEGER, allowNull: true },
    pembinaan_dilakukan: { type: DataTypes.INTEGER, allowNull: true },
    ringkasan_laporan_teknis: { type: DataTypes.TEXT, allowNull: true },
    jenis_data_layanan: { type: DataTypes.ENUM, allowNull: true },
    periode_data: { type: DataTypes.DATEONLY, allowNull: true },
    format_data: { type: DataTypes.ENUM, allowNull: true, defaultValue: "Excel" },
    keterangan_data: { type: DataTypes.TEXT, allowNull: true },
    file_laporan_inspeksi: { type: DataTypes.STRING(255), allowNull: true },
    file_laporan_audit_ins: { type: DataTypes.STRING(255), allowNull: true },
    file_hasil_pengujian: { type: DataTypes.STRING(255), allowNull: true },
    file_berita_acara: { type: DataTypes.STRING(255), allowNull: true },
    file_dokumentasi: { type: DataTypes.JSONB, allowNull: true },
    file_laporan_teknis_ins: { type: DataTypes.STRING(255), allowNull: true },
    file_data_layanan: { type: DataTypes.STRING(255), allowNull: true },
    rincian_layanan: { type: DataTypes.TEXT, allowNull: true },
    penanggung_jawab: { type: DataTypes.STRING(255), allowNull: false, defaultValue: "Kasi Manajemen Teknis" },
    pelaksana: { type: DataTypes.STRING(255), allowNull: false },
    kelompok_penerima: { type: DataTypes.STRING(255), allowNull: true, defaultValue: "Pelaku Usaha/Masyarakat" },
    jenis_data: { type: DataTypes.STRING(255), allowNull: true },
    is_sensitive: { type: DataTypes.ENUM, allowNull: false, defaultValue: "Sensitif" },
    status: { type: DataTypes.ENUM, allowNull: false, defaultValue: "pending" },
    keterangan: { type: DataTypes.TEXT, allowNull: true },
    created_by: { type: DataTypes.INTEGER, allowNull: false },
    created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
    updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
  }, { tableName: 'UPT-INS', timestamps: false });

export default UPT-INS;
