import { DataTypes } from 'sequelize';
import sequelize from '../config/database.js';
const UPT-MTU = sequelize.define(
  'UPT-MTU', {
    id: { type: DataTypes.INTEGER, allowNull: false, unique: true, autoIncrement: true, primaryKey: true },
    layanan_id: { type: DataTypes.STRING(10), allowNull: false },
    jenis_layanan_mutu: { type: DataTypes.ENUM, allowNull: false },
    nomor_dokumen_mutu: { type: DataTypes.STRING(100), allowNull: true },
    judul_dokumen: { type: DataTypes.STRING(255), allowNull: true },
    tanggal_dokumen: { type: DataTypes.DATEONLY, allowNull: true },
    versi: { type: DataTypes.STRING(20), allowNull: true, defaultValue: "1.0" },
    status_dokumen: { type: DataTypes.ENUM, allowNull: true },
    objek_verifikasi: { type: DataTypes.STRING(255), allowNull: true },
    standar_kepatuhan: { type: DataTypes.STRING(255), allowNull: true },
    hasil_verifikasi: { type: DataTypes.ENUM, allowNull: true },
    catatan_verifikasi: { type: DataTypes.TEXT, allowNull: true },
    jenis_audit_mutu: { type: DataTypes.ENUM, allowNull: true },
    tanggal_audit_mutu: { type: DataTypes.DATEONLY, allowNull: true },
    auditor_mutu: { type: DataTypes.STRING(255), allowNull: true },
    hasil_audit_mutu: { type: DataTypes.TEXT, allowNull: true },
    temuan_mayor: { type: DataTypes.TEXT, allowNull: true },
    temuan_minor: { type: DataTypes.TEXT, allowNull: true },
    observasi: { type: DataTypes.TEXT, allowNull: true },
    tindakan_korektif_mutu: { type: DataTypes.TEXT, allowNull: true },
    penanggung_jawab_perbaikan: { type: DataTypes.STRING(255), allowNull: true },
    batas_waktu_perbaikan_mutu: { type: DataTypes.DATEONLY, allowNull: true },
    status_perbaikan: { type: DataTypes.ENUM, allowNull: true },
    kode_sop: { type: DataTypes.STRING(50), allowNull: true },
    nama_sop: { type: DataTypes.STRING(255), allowNull: true },
    lingkup_sop: { type: DataTypes.TEXT, allowNull: true },
    tujuan_sop: { type: DataTypes.TEXT, allowNull: true },
    definisi: { type: DataTypes.TEXT, allowNull: true },
    prosedur: { type: DataTypes.TEXT, allowNull: true },
    flowchart: { type: DataTypes.STRING(255), allowNull: true },
    formulir_terkait: { type: DataTypes.TEXT, allowNull: true },
    dokumen_terkait: { type: DataTypes.TEXT, allowNull: true },
    tanggal_review: { type: DataTypes.DATEONLY, allowNull: true },
    reviewer: { type: DataTypes.STRING(255), allowNull: true },
    hasil_review: { type: DataTypes.TEXT, allowNull: true },
    perubahan_yang_dilakukan: { type: DataTypes.TEXT, allowNull: true },
    alasan_perubahan: { type: DataTypes.TEXT, allowNull: true },
    jenis_standar_layanan: { type: DataTypes.ENUM, allowNull: true },
    isi_standar: { type: DataTypes.TEXT, allowNull: true },
    metode_sosialisasi: { type: DataTypes.ENUM, allowNull: true },
    tanggal_sosialisasi: { type: DataTypes.DATEONLY, allowNull: true },
    peserta_sosialisasi: { type: DataTypes.INTEGER, allowNull: true },
    materi_sosialisasi: { type: DataTypes.STRING(255), allowNull: true },
    nama_pelatihan: { type: DataTypes.STRING(255), allowNull: true },
    jenis_pelatihan: { type: DataTypes.ENUM, allowNull: true },
    tanggal_pelatihan: { type: DataTypes.DATEONLY, allowNull: true },
    durasi_pelatihan: { type: DataTypes.INTEGER, allowNull: true },
    trainer: { type: DataTypes.STRING(255), allowNull: true },
    peserta_pelatihan: { type: DataTypes.TEXT, allowNull: true },
    materi_pelatihan: { type: DataTypes.TEXT, allowNull: true },
    hasil_evaluasi_pelatihan: { type: DataTypes.TEXT, allowNull: true },
    auditor_id: { type: DataTypes.INTEGER, allowNull: true },
    nama_auditor: { type: DataTypes.STRING(255), allowNull: true },
    nip_auditor: { type: DataTypes.STRING(18), allowNull: true },
    sertifikat_auditor: { type: DataTypes.STRING(255), allowNull: true },
    jenis_sertifikat_auditor: { type: DataTypes.ENUM, allowNull: true },
    tanggal_sertifikat: { type: DataTypes.DATEONLY, allowNull: true },
    masa_berlaku_auditor: { type: DataTypes.DATEONLY, allowNull: true },
    lembaga_penerbit: { type: DataTypes.STRING(255), allowNull: true },
    kompetensi_auditor: { type: DataTypes.TEXT, allowNull: true },
    jumlah_audit_dilakukan: { type: DataTypes.INTEGER, allowNull: true, defaultValue: "0" },
    status_auditor: { type: DataTypes.ENUM, allowNull: true, defaultValue: "Aktif" },
    jenis_evaluasi_auditor: { type: DataTypes.ENUM, allowNull: true },
    tanggal_evaluasi_auditor: { type: DataTypes.DATEONLY, allowNull: true },
    skor_evaluasi: { type: DataTypes.DECIMAL, allowNull: true },
    hasil_evaluasi_auditor: { type: DataTypes.ENUM, allowNull: true },
    rekomendasi_evaluasi: { type: DataTypes.TEXT, allowNull: true },
    tanggal_supervisi: { type: DataTypes.DATEONLY, allowNull: true },
    lokasi_supervisi: { type: DataTypes.STRING(255), allowNull: true },
    supervisor: { type: DataTypes.STRING(255), allowNull: true },
    auditor_disupervisi: { type: DataTypes.STRING(255), allowNull: true },
    temuan_supervisi: { type: DataTypes.TEXT, allowNull: true },
    rekomendasi_supervisi: { type: DataTypes.TEXT, allowNull: true },
    periode_evaluasi: { type: DataTypes.DATEONLY, allowNull: true },
    total_sertifikasi_periode: { type: DataTypes.INTEGER, allowNull: true },
    lulus_sertifikasi: { type: DataTypes.INTEGER, allowNull: true },
    tidak_lulus: { type: DataTypes.INTEGER, allowNull: true },
    persentase_kelulusan_sertifikasi: { type: DataTypes.DECIMAL, allowNull: true },
    analisis_evaluasi: { type: DataTypes.TEXT, allowNull: true },
    jenis_rekomendasi: { type: DataTypes.ENUM, allowNull: true },
    isi_rekomendasi: { type: DataTypes.TEXT, allowNull: true },
    ditujukan_kepada: { type: DataTypes.STRING(255), allowNull: true, defaultValue: "Kepala UPTD" },
    status_rekomendasi: { type: DataTypes.ENUM, allowNull: true, defaultValue: "Open" },
    periode_laporan_mutu: { type: DataTypes.DATEONLY, allowNull: true },
    indikator_mutu: { type: DataTypes.TEXT, allowNull: true },
    capaian_mutu: { type: DataTypes.TEXT, allowNull: true },
    persentase_kepuasan_pelanggan: { type: DataTypes.DECIMAL, allowNull: true },
    temuan_mutu_periode: { type: DataTypes.INTEGER, allowNull: true },
    temuan_diselesaikan: { type: DataTypes.INTEGER, allowNull: true },
    ringkasan_laporan_mutu: { type: DataTypes.TEXT, allowNull: true },
    file_sop: { type: DataTypes.STRING(255), allowNull: true },
    file_flowchart: { type: DataTypes.STRING(255), allowNull: true },
    file_dokumen_mutu: { type: DataTypes.STRING(255), allowNull: true },
    file_sertifikat_auditor: { type: DataTypes.STRING(255), allowNull: true },
    file_laporan_mutu: { type: DataTypes.STRING(255), allowNull: true },
    file_materi: { type: DataTypes.JSONB, allowNull: true },
    rincian_layanan: { type: DataTypes.TEXT, allowNull: true },
    penanggung_jawab: { type: DataTypes.STRING(255), allowNull: false, defaultValue: "Kasi Manajemen Mutu" },
    pelaksana: { type: DataTypes.STRING(255), allowNull: false },
    kelompok_penerima: { type: DataTypes.STRING(255), allowNull: true, defaultValue: "Internal UPTD" },
    jenis_data: { type: DataTypes.STRING(255), allowNull: true },
    is_sensitive: { type: DataTypes.ENUM, allowNull: false, defaultValue: "Sensitif" },
    status: { type: DataTypes.ENUM, allowNull: false, defaultValue: "draft" },
    keterangan: { type: DataTypes.TEXT, allowNull: true },
    created_by: { type: DataTypes.INTEGER, allowNull: false },
    created_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
    updated_at: { type: DataTypes.DATE, allowNull: false, defaultValue: "CURRENT_TIMESTAMP" },
  }, { tableName: 'UPT-MTU', timestamps: false });

export default UPT-MTU;
