-- =====================================================
-- TABLE: upt_ins
-- MODULE: UPT-INS
-- Generated: 2026-02-17T19:24:46.519Z
-- =====================================================

CREATE TABLE IF NOT EXISTS upt_ins (
  id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
  layanan_id VARCHAR(10) NOT NULL,
  jenis_layanan_inspeksi VARCHAR(100) CHECK(jenis_layanan_inspeksi IN ('Inspeksi Lapangan', 'Audit Sertifikasi', 'Audit Ulang', 'Pengambilan Sampel', 'Pengujian Mutu', 'Verifikasi Hasil Uji', 'Rekomendasi Pengawasan', 'Pembinaan', 'Koordinasi OPD', 'Monitoring Perbaikan', 'Penjadwalan', 'Pelaksanaan Lapangan', 'Pelaporan Teknis', 'Data Layanan')) NOT NULL,
  nomor_inspeksi VARCHAR(100),
  nomor_audit_ins VARCHAR(100),
  tanggal_inspeksi DATE,
  lokasi_inspeksi VARCHAR(255),
  objek_inspeksi VARCHAR(255),
  nama_usaha_inspeksi VARCHAR(255),
  pemilik_usaha_inspeksi VARCHAR(255),
  alamat_inspeksi TEXT,
  tim_inspeksi TEXT,
  jenis_sertifikasi_audit VARCHAR(100) CHECK(jenis_sertifikasi_audit IN ('GMP', 'GHP', 'NKV', 'Prima 1', 'Prima 2', 'Prima 3', 'GFP', 'HACCP', 'Lainnya')),
  audit_awal_ulang VARCHAR(100) CHECK(audit_awal_ulang IN ('Awal', 'Ulang', 'Surveillance')) DEFAULT 'Awal',
  alasan_audit_ulang TEXT,
  checklist_inspeksi JSON,
  skor_inspeksi DECIMAL(5,2),
  hasil_inspeksi VARCHAR(100) CHECK(hasil_inspeksi IN ('Lulus', 'Tidak Lulus', 'Lulus Bersyarat')),
  temuan_inspeksi TEXT,
  catatan_inspeksi TEXT,
  rekomendasi_inspeksi TEXT,
  tindakan_korektif_inspeksi TEXT,
  batas_waktu_ins DATE,
  jenis_sampel_pangan VARCHAR(255),
  lokasi_pengambilan VARCHAR(255),
  tanggal_sampling DATE,
  sampler VARCHAR(255),
  jumlah_sampel_diambil INTEGER,
  metode_sampling VARCHAR(255),
  kondisi_sampel VARCHAR(100) CHECK(kondisi_sampel IN ('Baik', 'Rusak', 'Kadaluarsa')) DEFAULT 'Baik',
  penyimpanan_sampel VARCHAR(255),
  nomor_sampel VARCHAR(100),
  parameter_pengujian TEXT,
  metode_pengujian VARCHAR(255),
  analis_pengujian VARCHAR(255),
  tanggal_pengujian_mulai DATE,
  tanggal_pengujian_selesai DATE,
  hasil_pengujian TEXT,
  kesimpulan_pengujian VARCHAR(100) CHECK(kesimpulan_pengujian IN ('Memenuhi Syarat', 'Tidak Memenuhi Syarat')),
  tanggal_verifikasi_uji DATE,
  verifikator_uji VARCHAR(255),
  hasil_verifikasi_uji VARCHAR(100) CHECK(hasil_verifikasi_uji IN ('Approved', 'Rejected', 'Need Retest')),
  catatan_verifikasi_uji TEXT,
  jenis_rekomendasi_pengawasan VARCHAR(100) CHECK(jenis_rekomendasi_pengawasan IN ('Rekomendasi Tindakan', 'Rekomendasi Sanksi', 'Rekomendasi Pembinaan', 'Rekomendasi Pemantauan')),
  isi_rekomendasi_pengawasan TEXT,
  tindak_lanjut_rekomendasi TEXT,
  status_rekomendasi_pengawasan VARCHAR(100) CHECK(status_rekomendasi_pengawasan IN ('Open', 'In Progress', 'Closed')) DEFAULT 'Open',
  jenis_pembinaan VARCHAR(100) CHECK(jenis_pembinaan IN ('Pembinaan Langsung', 'Bimbingan Teknis', 'Konsultasi', 'Pelatihan', 'Lainnya')),
  tanggal_pembinaan DATE,
  lokasi_pembinaan VARCHAR(255),
  penerima_pembinaan VARCHAR(255),
  materi_pembinaan TEXT,
  hasil_pembinaan TEXT,
  opd_dikoordinasikan TEXT,
  tanggal_koordinasi DATE,
  topik_koordinasi_opd TEXT,
  hasil_koordinasi_opd TEXT,
  tindak_lanjut_koordinasi TEXT,
  objek_monitoring VARCHAR(255),
  tanggal_monitoring DATE,
  hasil_monitoring TEXT,
  status_perbaikan_monitoring VARCHAR(100) CHECK(status_perbaikan_monitoring IN ('Belum', 'Proses', 'Selesai', 'Verified')),
  tanggal_penjadwalan DATE,
  jenis_kegiatan_jadwal VARCHAR(100) CHECK(jenis_kegiatan_jadwal IN ('Inspeksi', 'Audit', 'Sampling', 'Pengujian', 'Pembinaan', 'Monitoring')),
  petugas_dijadwalkan TEXT,
  status_jadwal VARCHAR(100) CHECK(status_jadwal IN ('Scheduled', 'Ongoing', 'Completed', 'Cancelled', 'Rescheduled')) DEFAULT 'Scheduled',
  jenis_layanan_lapangan VARCHAR(255),
  tanggal_pelaksanaan DATE,
  lokasi_pelaksanaan VARCHAR(255),
  tim_pelaksana TEXT,
  hasil_pelaksanaan TEXT,
  periode_pelaporan_teknis DATE,
  jenis_laporan_teknis VARCHAR(100) CHECK(jenis_laporan_teknis IN ('Bulanan', 'Triwulanan', 'Semesteran', 'Tahunan')),
  total_inspeksi INTEGER,
  total_audit_teknis INTEGER,
  total_sampel_diambil INTEGER,
  total_pengujian_teknis INTEGER,
  persentase_kelulusan_teknis DECIMAL(5,2),
  temuan_tidak_sesuai INTEGER,
  tindakan_pengawasan INTEGER,
  pembinaan_dilakukan INTEGER,
  ringkasan_laporan_teknis TEXT,
  jenis_data_layanan VARCHAR(100) CHECK(jenis_data_layanan IN ('Data Inspeksi', 'Data Audit', 'Data Sampling', 'Data Pengujian', 'Data Sertifikasi', 'Data Pembinaan', 'Data Monitoring')),
  periode_data DATE,
  format_data VARCHAR(100) CHECK(format_data IN ('Excel', 'PDF', 'CSV', 'JSON')) DEFAULT 'Excel',
  keterangan_data TEXT,
  file_laporan_inspeksi VARCHAR(255),
  file_laporan_audit_ins VARCHAR(255),
  file_hasil_pengujian VARCHAR(255),
  file_berita_acara VARCHAR(255),
  file_dokumentasi JSON,
  file_laporan_teknis_ins VARCHAR(255),
  file_data_layanan VARCHAR(255),
  rincian_layanan TEXT,
  penanggung_jawab VARCHAR(255) NOT NULL DEFAULT 'Kasi Manajemen Teknis',
  pelaksana VARCHAR(255) NOT NULL,
  kelompok_penerima VARCHAR(255) DEFAULT 'Pelaku Usaha/Masyarakat',
  jenis_data VARCHAR(255),
  is_sensitive VARCHAR(100) CHECK(is_sensitive IN ('Biasa', 'Sensitif')) NOT NULL DEFAULT 'Sensitif',
  status VARCHAR(100) CHECK(status IN ('pending', 'scheduled', 'ongoing', 'completed', 'verified')) NOT NULL DEFAULT 'pending',
  keterangan TEXT,
  created_by INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_upt_ins_layanan_id ON upt_ins(layanan_id);
CREATE INDEX IF NOT EXISTS idx_upt_ins_status ON upt_ins(status);
CREATE INDEX IF NOT EXISTS idx_upt_ins_created_at ON upt_ins(created_at);

