-- =====================================================
-- TABLE: upt_mtu
-- MODULE: UPT-MTU
-- Generated: 2026-02-17T19:24:46.525Z
-- =====================================================

CREATE TABLE IF NOT EXISTS upt_mtu (
  id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
  layanan_id VARCHAR(10) NOT NULL,
  jenis_layanan_mutu VARCHAR(100) CHECK(jenis_layanan_mutu IN ('Penjaminan Mutu', 'Verifikasi Kepatuhan', 'Pengendalian Mutu', 'Pengelolaan Temuan', 'Penyusunan SOP', 'Review SOP', 'Standar Layanan', 'Sosialisasi', 'Pelatihan Auditor', 'Sertifikasi Auditor', 'Evaluasi Auditor', 'Database Auditor', 'Supervisi Audit', 'Evaluasi Sertifikasi', 'Rekomendasi Mutu', 'Laporan Mutu')) NOT NULL,
  nomor_dokumen_mutu VARCHAR(100),
  judul_dokumen VARCHAR(255),
  tanggal_dokumen DATE,
  versi VARCHAR(20) DEFAULT '1.0',
  status_dokumen VARCHAR(100) CHECK(status_dokumen IN ('Draft', 'Review', 'Approved', 'Active', 'Obsolete')),
  objek_verifikasi VARCHAR(255),
  standar_kepatuhan VARCHAR(255),
  hasil_verifikasi VARCHAR(100) CHECK(hasil_verifikasi IN ('Sesuai', 'Tidak Sesuai', 'Perlu Perbaikan')),
  catatan_verifikasi TEXT,
  jenis_audit_mutu VARCHAR(100) CHECK(jenis_audit_mutu IN ('Audit Internal', 'Audit Eksternal', 'Surveillance', 'Witnessing')),
  tanggal_audit_mutu DATE,
  auditor_mutu VARCHAR(255),
  hasil_audit_mutu TEXT,
  temuan_mayor TEXT,
  temuan_minor TEXT,
  observasi TEXT,
  tindakan_korektif_mutu TEXT,
  penanggung_jawab_perbaikan VARCHAR(255),
  batas_waktu_perbaikan_mutu DATE,
  status_perbaikan VARCHAR(100) CHECK(status_perbaikan IN ('Open', 'In Progress', 'Closed', 'Verified')),
  kode_sop VARCHAR(50),
  nama_sop VARCHAR(255),
  lingkup_sop TEXT,
  tujuan_sop TEXT,
  definisi TEXT,
  prosedur TEXT,
  flowchart VARCHAR(255),
  formulir_terkait TEXT,
  dokumen_terkait TEXT,
  tanggal_review DATE,
  reviewer VARCHAR(255),
  hasil_review TEXT,
  perubahan_yang_dilakukan TEXT,
  alasan_perubahan TEXT,
  jenis_standar_layanan VARCHAR(100) CHECK(jenis_standar_layanan IN ('Persyaratan', 'Prosedur', 'Waktu', 'Biaya', 'Produk', 'Kompetensi', 'Sarana')),
  isi_standar TEXT,
  metode_sosialisasi VARCHAR(100) CHECK(metode_sosialisasi IN ('Workshop', 'Rapat', 'Presentasi', 'Leaflet', 'Online')),
  tanggal_sosialisasi DATE,
  peserta_sosialisasi INTEGER,
  materi_sosialisasi VARCHAR(255),
  nama_pelatihan VARCHAR(255),
  jenis_pelatihan VARCHAR(100) CHECK(jenis_pelatihan IN ('Basic Auditor', 'Lead Auditor', 'Refreshment', 'Advance')),
  tanggal_pelatihan DATE,
  durasi_pelatihan INTEGER,
  trainer VARCHAR(255),
  peserta_pelatihan TEXT,
  materi_pelatihan TEXT,
  hasil_evaluasi_pelatihan TEXT,
  auditor_id INTEGER,
  nama_auditor VARCHAR(255),
  nip_auditor VARCHAR(18),
  sertifikat_auditor VARCHAR(255),
  jenis_sertifikat_auditor VARCHAR(100) CHECK(jenis_sertifikat_auditor IN ('Basic Auditor', 'Lead Auditor', 'Auditor GMP', 'Auditor HACCP', 'Lainnya')),
  tanggal_sertifikat DATE,
  masa_berlaku_auditor DATE,
  lembaga_penerbit VARCHAR(255),
  kompetensi_auditor TEXT,
  jumlah_audit_dilakukan INTEGER DEFAULT 0,
  status_auditor VARCHAR(100) CHECK(status_auditor IN ('Aktif', 'Nonaktif', 'Expired')) DEFAULT 'Aktif',
  jenis_evaluasi_auditor VARCHAR(100) CHECK(jenis_evaluasi_auditor IN ('Evaluasi Kinerja', 'Evaluasi Kompetensi', 'Evaluasi Post Training')),
  tanggal_evaluasi_auditor DATE,
  skor_evaluasi DECIMAL(5,2),
  hasil_evaluasi_auditor VARCHAR(100) CHECK(hasil_evaluasi_auditor IN ('Sangat Baik', 'Baik', 'Cukup', 'Kurang')),
  rekomendasi_evaluasi TEXT,
  tanggal_supervisi DATE,
  lokasi_supervisi VARCHAR(255),
  supervisor VARCHAR(255),
  auditor_disupervisi VARCHAR(255),
  temuan_supervisi TEXT,
  rekomendasi_supervisi TEXT,
  periode_evaluasi DATE,
  total_sertifikasi_periode INTEGER,
  lulus_sertifikasi INTEGER,
  tidak_lulus INTEGER,
  persentase_kelulusan_sertifikasi DECIMAL(5,2),
  analisis_evaluasi TEXT,
  jenis_rekomendasi VARCHAR(100) CHECK(jenis_rekomendasi IN ('Rekomendasi Perbaikan Sistem', 'Rekomendasi Perbaikan Proses', 'Rekomendasi Pelatihan', 'Rekomendasi Investasi')),
  isi_rekomendasi TEXT,
  ditujukan_kepada VARCHAR(255) DEFAULT 'Kepala UPTD',
  status_rekomendasi VARCHAR(100) CHECK(status_rekomendasi IN ('Open', 'In Progress', 'Closed')) DEFAULT 'Open',
  periode_laporan_mutu DATE,
  indikator_mutu TEXT,
  capaian_mutu TEXT,
  persentase_kepuasan_pelanggan DECIMAL(5,2),
  temuan_mutu_periode INTEGER,
  temuan_diselesaikan INTEGER,
  ringkasan_laporan_mutu TEXT,
  file_sop VARCHAR(255),
  file_flowchart VARCHAR(255),
  file_dokumen_mutu VARCHAR(255),
  file_sertifikat_auditor VARCHAR(255),
  file_laporan_mutu VARCHAR(255),
  file_materi JSON,
  rincian_layanan TEXT,
  penanggung_jawab VARCHAR(255) NOT NULL DEFAULT 'Kasi Manajemen Mutu',
  pelaksana VARCHAR(255) NOT NULL,
  kelompok_penerima VARCHAR(255) DEFAULT 'Internal UPTD',
  jenis_data VARCHAR(255),
  is_sensitive VARCHAR(100) CHECK(is_sensitive IN ('Biasa', 'Sensitif')) NOT NULL DEFAULT 'Sensitif',
  status VARCHAR(100) CHECK(status IN ('draft', 'review', 'approved', 'active')) NOT NULL DEFAULT 'draft',
  keterangan TEXT,
  created_by INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_upt_mtu_layanan_id ON upt_mtu(layanan_id);
CREATE INDEX IF NOT EXISTS idx_upt_mtu_auditor_id ON upt_mtu(auditor_id);
CREATE INDEX IF NOT EXISTS idx_upt_mtu_status ON upt_mtu(status);
CREATE INDEX IF NOT EXISTS idx_upt_mtu_created_at ON upt_mtu(created_at);

