import { useState, useEffect, useCallback } from "react";
import { useParams, Link } from "react-router-dom";
import api from "../utils/api";

export default function ViewDetailPage() {
  const { moduleId, id } = useParams();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const fetchData = useCallback(async () => {
    try {
      const response = await api.get(`/${moduleId}/${id}`);
      setData(response.data.data);
    } catch (err) {
      setError(err.response?.data?.message || "Error loading data");
    } finally {
      setLoading(false);
    }
  }, [moduleId, id]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="bg-red-50 border border-red-200 rounded-lg p-6">
        <p className="text-red-700">❌ {error || "Data tidak ditemukan"}</p>
        <Link
          to={`/module/${moduleId}`}
          className="text-blue-600 hover:underline mt-4 inline-block"
        >
          ← Kembali ke List
        </Link>
      </div>
    );
  }

  const moduleName = getModuleName(moduleId);
  const detailEntries = getDetailEntries(moduleId, data);

  return (
    <div>
      {/* Header */}
      <div className="mb-6">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-bold text-gray-800">
              Detail {moduleName}
            </h2>
            <p className="text-sm text-gray-500">ID: {id}</p>
          </div>
          <div className="flex space-x-3">
            <Link
              to={`/module/${moduleId}/${id}/edit`}
              className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg font-medium"
            >
              ✏️ Edit
            </Link>
            <Link
              to={`/module/${moduleId}`}
              className="bg-gray-600 hover:bg-gray-700 text-white px-4 py-2 rounded-lg font-medium"
            >
              ← Kembali
            </Link>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="bg-white rounded-lg shadow overflow-hidden">
        <div className="p-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {detailEntries.map(([key, value]) => (
              <div key={key} className="border-b border-gray-200 pb-4">
                <dt className="text-sm font-medium text-gray-500 mb-1">
                  {formatLabel(key)}
                </dt>
                <dd className="text-base text-gray-900">
                  {formatValue(key, value)}
                </dd>
              </div>
            ))}
          </div>
        </div>

        {/* Footer */}
        <div className="bg-gray-50 px-6 py-4 border-t border-gray-200">
          <div className="flex justify-between text-xs text-gray-500">
            <span>Dibuat: {formatDate(data.created_at)}</span>
            {data.updated_at && (
              <span>Diupdate: {formatDate(data.updated_at)}</span>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

// Helper functions
function getModuleName(moduleId) {
  const names = {
    "sek-adm": "Administrasi Umum",
    "sek-keu": "Keuangan & Anggaran",
    "sek-rmh": "Rumah Tangga & Umum",
    "sek-ast": "Aset & BMD",
    "sek-hum": "Protokol & Kehumasan",
    "sek-kbj": "Kebijakan & Koordinasi",
    "bds-hrg": "Harga Pangan",
    "bds-kbj": "Kebijakan Distribusi",
    "bds-mon": "Monitoring Distribusi",
    "bds-cpd": "Cadangan Pangan Daerah (CPPD)",
    "bds-bmb": "Bimbingan & Pendampingan Distribusi",
    "bds-evl": "Evaluasi Distribusi",
    "bds-lap": "Pelaporan Kinerja Distribusi",
    "bkt-pgd": "Produksi Pangan",
    "bkt-kbj": "Kebijakan & Analisis Ketersediaan",
    "bkt-krw": "Kerawanan Pangan",
    "bkt-mev": "Monitoring Evaluasi & Pelaporan",
    "bkt-fsl": "Fasilitasi & Intervensi",
    "bkt-bmb": "Bimbingan & Pendampingan",
    "sek-kep": "Kepegawaian",
  };
  return names[moduleId] || moduleId.toUpperCase();
}

function formatLabel(key) {
  const labels = {
    nomor_surat: "Nomor Surat",
    jenis_naskah: "Jenis Naskah",
    tanggal_surat: "Tanggal Surat",
    pengirim_penerima: "Pengirim/Penerima",
    perihal: "Perihal",
    status: "Status",
    nama_komoditas: "Komoditas",
    nama_pasar: "Nama Pasar",
    tanggal_pantau: "Tanggal Pantau",
    harga: "Harga",
    satuan: "Satuan",
    tren_harga: "Tren Harga",
    periode: "Periode",
    luas_tanam: "Luas Tanam (Ha)",
    luas_panen: "Luas Panen (Ha)",
    produksi: "Produksi (Ton)",
    produksi_total: "Produksi (Ton)",
    produktivitas: "Produktivitas",
    keterangan: "Keterangan",
    unit_kerja: "Unit Kerja",
    layanan_id: "ID Layanan",
    kode_unit: "Kode Unit",
    tahun_anggaran: "Tahun Anggaran",
    jenis_layanan_keuangan: "Jenis Layanan Keuangan",
    nomor_dpa: "Nomor DPA",
    kode_rekening: "Kode Rekening",
    nama_rekening: "Nama Rekening",
    pagu_anggaran: "Pagu Anggaran",
    sisa_anggaran: "Sisa Anggaran",
    persentase_realisasi: "Persentase Realisasi (%)",
    jenis_belanja: "Jenis Belanja",
    uraian_belanja: "Uraian Belanja",
    keperluan: "Keperluan",
    penerima_uang: "Penerima Uang",
    tanggal_pencairan: "Tanggal Pencairan",
    jumlah_pencairan: "Jumlah Pencairan",
    nomor_spj: "Nomor SPJ",
    tanggal_spj: "Tanggal SPJ",
    status_spj: "Status SPJ",
    jenis_revisi: "Jenis Revisi",
    alasan_revisi: "Alasan Revisi",
    file_dpa: "File DPA",
    file_spj: "File SPJ",
    file_bukti: "File Bukti",
    jenis_layanan_rumah_tangga: "Jenis Layanan Rumah Tangga",
    nomor_sppd: "Nomor SPPD",
    nomor_st: "Nomor ST",
    nama_pegawai: "Nama Pegawai",
    nip_pegawai: "NIP Pegawai",
    tanggal_berangkat: "Tanggal Berangkat",
    tanggal_kembali: "Tanggal Kembali",
    lama_hari: "Lama Hari",
    biaya_transport: "Biaya Transport",
    biaya_penginapan: "Biaya Penginapan",
    uang_harian: "Uang Harian",
    total_biaya: "Total Biaya",
    area_kebersihan: "Area Kebersihan",
    jadwal_kebersihan: "Jadwal Kebersihan",
    petugas_kebersihan: "Petugas Kebersihan",
    pos_keamanan: "Pos Keamanan",
    shift_keamanan: "Shift Keamanan",
    petugas_keamanan: "Petugas Keamanan",
    jenis_fasilitas: "Jenis Fasilitas",
    kondisi_fasilitas: "Kondisi Fasilitas",
    nama_ruang_rapat: "Nama Ruang Rapat",
    kapasitas: "Kapasitas",
    tanggal_pemesanan: "Tanggal Pemesanan",
    pemesan: "Pemesan",
    nomor_polisi: "Nomor Polisi",
    jenis_kendaraan: "Jenis Kendaraan",
    driver: "Driver",
    tanggal_pakai: "Tanggal Pakai",
    km_awal: "KM Awal",
    km_akhir: "KM Akhir",
    bbm_liter: "BBM (Liter)",
    file_sppd: "File SPPD",
    jenis_layanan_humas: "Jenis Layanan Humas",
    jenis_acara: "Jenis Acara",
    tanggal_acara: "Tanggal Acara",
    waktu_mulai: "Waktu Mulai",
    waktu_selesai: "Waktu Selesai",
    pimpinan_hadir: "Pimpinan Hadir",
    tamu_vip: "Tamu VIP",
    rundown_acara: "Rundown Acara",
    mc: "MC",
    protokoler: "Petugas Protokol",
    nama_tamu: "Nama Tamu",
    instansi_tamu: "Instansi Tamu",
    keperluan_kunjungan: "Keperluan Kunjungan",
    penerima_tamu: "Penerima Tamu",
    judul_publikasi: "Judul Publikasi",
    jenis_publikasi: "Jenis Publikasi",
    media_publikasi: "Media Publikasi",
    link_publikasi: "Link Publikasi",
    isi_publikasi: "Isi Publikasi",
    fotografer: "Fotografer",
    videografer: "Videografer",
    jumlah_foto: "Jumlah Foto",
    jumlah_video: "Jumlah Video",
    file_video: "File Video",
    file_rundown: "File Rundown",
    file_undangan: "File Undangan",
    jenis_layanan_kebijakan: "Jenis Layanan Kebijakan",
    judul: "Judul",
    ruang_lingkup: "Ruang Lingkup",
    opsi_kebijakan: "Opsi Kebijakan",
    rekomendasi_kebijakan: "Rekomendasi Kebijakan",
    dampak: "Dampak",
    dasar_hukum: "Dasar Hukum",
    sumber_data_bidang_ketersediaan: "Sumber Data Bidang Ketersediaan",
    sumber_data_bidang_distribusi: "Sumber Data Bidang Distribusi",
    sumber_data_bidang_konsumsi: "Sumber Data Bidang Konsumsi",
    sumber_data_uptd: "Sumber Data UPTD",
    rekapitulasi_keuangan: "Rekapitulasi Keuangan",
    rekapitulasi_program: "Rekapitulasi Program",
    rekapitulasi_capaian: "Rekapitulasi Capaian",
    kesimpulan: "Kesimpulan",
    file_dokumen: "File Dokumen",
    file_lampiran: "File Lampiran",
    kode_aset: "Kode Aset",
    nama_aset: "Nama Aset",
    kategori_aset: "Kategori Aset",
    merk_type: "Merk/Tipe",
    nomor_seri: "Nomor Seri",
    tahun_perolehan: "Tahun Perolehan",
    cara_perolehan: "Cara Perolehan",
    harga_perolehan: "Harga Perolehan",
    nilai_buku: "Nilai Buku",
    kondisi: "Kondisi",
    lokasi: "Lokasi",
    ruangan: "Ruangan",
    penanggung_jawab_aset: "Penanggung Jawab Aset",
    qr_code: "QR Code",
    tanggal_inventarisasi: "Tanggal Inventarisasi",
    tanggal_pemeliharaan_terakhir: "Tanggal Pemeliharaan Terakhir",
    tanggal_pemeliharaan_berikutnya: "Tanggal Pemeliharaan Berikutnya",
    biaya_pemeliharaan: "Biaya Pemeliharaan",
    jenis_pemeliharaan: "Jenis Pemeliharaan",
    status_aset: "Status Aset",
    alasan_penghapusan: "Alasan Penghapusan",
    tanggal_penghapusan: "Tanggal Penghapusan",
    nomor_sk_penghapusan: "Nomor SK Penghapusan",
    file_foto: "File Foto",
    asn_id: "ID ASN",
    nip: "NIP",
    nama_asn: "Nama ASN",
    jenis_layanan_kepegawaian: "Jenis Layanan Kepegawaian",
    pangkat_lama: "Pangkat Lama",
    pangkat_baru: "Pangkat Baru",
    golongan_lama: "Golongan Lama",
    golongan_baru: "Golongan Baru",
    jabatan_lama: "Jabatan Lama",
    jabatan_baru: "Jabatan Baru",
    tmt_kenaikan: "TMT Kenaikan",
    nomor_sk: "Nomor SK",
    tanggal_sk: "Tanggal SK",
    jenis_cuti: "Jenis Cuti",
    tanggal_mulai_cuti: "Tanggal Mulai Cuti",
    tanggal_selesai_cuti: "Tanggal Selesai Cuti",
    lama_cuti: "Lama Cuti",
    nilai_skp: "Nilai SKP",
    predikat_kinerja: "Predikat Kinerja",
    jenis_sanksi: "Jenis Sanksi",
    uraian_sanksi: "Uraian Sanksi",
    tanggal_pensiun: "Tanggal Pensiun",
    jenis_pensiun: "Jenis Pensiun",
    gaji_pokok: "Gaji Pokok",
    total_tunjangan: "Total Tunjangan",
    file_sk: "File SK",
    file_pendukung: "File Pendukung",
    penanggung_jawab: "Penanggung Jawab",
    pelaksana: "Pelaksana",
    reported_to_sekretariat: "Dilaporkan ke Sekretariat",
    reported_at: "Waktu Pelaporan",
    sekretariat_notes: "Catatan Sekretariat",
    jenis_fasilitasi: "Jenis Fasilitasi",
    nama_program: "Nama Program",
    tahun: "Tahun",
    wilayah_sasaran: "Wilayah Sasaran",
    kelompok_sasaran: "Kelompok Sasaran",
    jumlah_penerima: "Jumlah Penerima",
    jenis_intervensi: "Jenis Intervensi",
    volume_bantuan: "Volume Bantuan",
    nilai_bantuan: "Nilai Bantuan",
    sumber_bantuan: "Sumber Bantuan",
    instansi_pemberi: "Instansi Pemberi",
    tanggal_penyaluran: "Tanggal Penyaluran",
    lokasi_penyaluran: "Lokasi Penyaluran",
    penanggung_jawab_penyaluran: "Penanggung Jawab Penyaluran",
    target_output: "Target Output",
    target_outcome: "Target Outcome",
    realisasi: "Realisasi",
    kendala: "Kendala",
    solusi: "Solusi",
    dokumentasi_kegiatan: "Dokumentasi Kegiatan",
    file_proposal: "File Proposal",
    file_bast: "File BAST",
    file_laporan: "File Laporan",
    rincian_layanan: "Rincian Layanan",
    kelompok_penerima: "Kelompok Penerima",
    jenis_data: "Jenis Data",
    is_sensitive: "Sensitivitas Data",
    jenis_bimbingan: "Jenis Bimbingan",
    nama_kegiatan: "Nama Kegiatan",
    tanggal_kegiatan: "Tanggal Kegiatan",
    tempat: "Tempat",
    kabupaten: "Kabupaten",
    sasaran_peserta: "Sasaran Peserta",
    jumlah_peserta: "Jumlah Peserta",
    narasumber: "Narasumber",
    fasilitator: "Fasilitator",
    materi_bimbingan: "Materi Bimbingan",
    metode_pelaksanaan: "Metode Pelaksanaan",
    topik_pemetaan: "Topik Pemetaan",
    hasil_pemetaan: "Hasil Pemetaan",
    area_supervisi: "Area Supervisi",
    temuan_supervisi: "Temuan Supervisi",
    rekomendasi_supervisi: "Rekomendasi Supervisi",
    topik_konsultasi: "Topik Konsultasi",
    pemohon_konsultasi: "Pemohon Konsultasi",
    jawaban_konsultasi: "Jawaban Konsultasi",
    durasi_pendampingan: "Durasi Pendampingan",
    frekuensi_pendampingan: "Frekuensi Pendampingan",
    output_kegiatan: "Output Kegiatan",
    outcome_kegiatan: "Outcome Kegiatan",
    evaluasi_kegiatan: "Evaluasi Kegiatan",
    tindak_lanjut: "Tindak Lanjut",
    biaya_kegiatan: "Biaya Kegiatan",
    sumber_anggaran: "Sumber Anggaran",
    file_materi: "File Materi",
    file_daftar_hadir: "File Daftar Hadir",
    file_dokumentasi: "File Dokumentasi",
    // BDS-HRG
    jenis_layanan_harga: "Jenis Layanan Harga",
    tingkat_fluktuasi: "Tingkat Fluktuasi",
    penyebab_fluktuasi: "Penyebab Fluktuasi",
    dampak_fluktuasi: "Dampak Fluktuasi",
    analisis_harga: "Analisis Harga",
    prediksi_harga: "Prediksi Harga",
    rekomendasi_stabilisasi: "Rekomendasi Stabilisasi",
    tanggal_rapat_tpid: "Tanggal Rapat TPID",
    tempat_rapat_tpid: "Tempat Rapat TPID",
    peserta_tpid: "Peserta TPID",
    agenda_tpid: "Agenda TPID",
    hasil_rapat_tpid: "Hasil Rapat TPID",
    rekomendasi_tpid: "Rekomendasi TPID",
    tindak_lanjut_tpid: "Tindak Lanjut TPID",
    inflasi_pangan: "Inflasi Pangan (%)",
    target_inflasi_tpid: "Target Inflasi TPID (%)",
    status_inflasi: "Status Inflasi",
    // BDS-KBJ
    tujuan: "Tujuan",
    sasaran: "Sasaran",
    wilayah_distribusi: "Wilayah Distribusi",
    komoditas_distribusi: "Komoditas Distribusi",
    jalur_distribusi_utama: "Jalur Distribusi Utama",
    jalur_distribusi_alternatif: "Jalur Distribusi Alternatif",
    titik_distribusi: "Titik Distribusi",
    strategi_distribusi: "Strategi Distribusi",
    mekanisme_distribusi: "Mekanisme Distribusi",
    stakeholder_terlibat: "Stakeholder Terlibat",
    target_capaian: "Target Capaian",
    // BDS-MON
    jenis_monitoring: "Jenis Monitoring",
    wilayah_asal: "Wilayah Asal",
    wilayah_tujuan: "Wilayah Tujuan",
    volume_distribusi: "Volume Distribusi",
    stok_pasar: "Stok Pasar",
    stok_normal: "Stok Normal",
    status_stok: "Status Stok",
    jenis_hambatan: "Jenis Hambatan",
    lokasi_hambatan: "Lokasi Hambatan",
    deskripsi_hambatan: "Deskripsi Hambatan",
    dampak_hambatan: "Dampak Hambatan",
    tingkat_hambatan: "Tingkat Hambatan",
    solusi_hambatan: "Solusi Hambatan",
    status_penanganan: "Status Penanganan",
    penerima_fasilitasi: "Penerima Fasilitasi",
    tindakan_fasilitasi: "Tindakan Fasilitasi",
    instansi_koordinasi: "Instansi Koordinasi",
    topik_koordinasi: "Topik Koordinasi",
    // BDS-CPD
    jenis_layanan_cppd: "Jenis Layanan CPPD",
    kebutuhan_cppd: "Kebutuhan CPPD",
    dasar_perhitungan: "Dasar Perhitungan",
    target_stok: "Target Stok",
    lokasi_penyimpanan: "Lokasi Penyimpanan",
    kapasitas_gudang: "Kapasitas Gudang",
    rencana_pengadaan: "Rencana Pengadaan",
    sumber_pengadaan: "Sumber Pengadaan",
    metode_pengadaan: "Metode Pengadaan",
    penyedia: "Penyedia",
    tanggal_pengadaan: "Tanggal Pengadaan",
    volume_pengadaan: "Volume Pengadaan",
    harga_satuan: "Harga Satuan",
    total_nilai: "Total Nilai",
    kualitas_cppd: "Kualitas CPPD",
    tanggal_masuk_gudang: "Tanggal Masuk Gudang",
    stok_awal_bulan: "Stok Awal Bulan",
    penerimaan_bulan_ini: "Penerimaan Bulan Ini",
    penyaluran_bulan_ini: "Penyaluran Bulan Ini",
    stok_akhir_bulan: "Stok Akhir Bulan",
    persentase_terhadap_target: "Persentase terhadap Target (%)",
    kondisi_fisik_cppd: "Kondisi Fisik CPPD",
    suhu_gudang: "Suhu Gudang",
    kelembaban_gudang: "Kelembaban Gudang",
    petugas_gudang: "Petugas Gudang",
    jenis_penyaluran: "Jenis Penyaluran",
    alasan_penyaluran: "Alasan Penyaluran",
    wilayah_penyaluran: "Wilayah Penyaluran",
    penerima_penyaluran: "Penerima Penyaluran",
    volume_penyaluran: "Volume Penyaluran",
    status_penyaluran: "Status Penyaluran",
    jumlah_penerima_manfaat: "Jumlah Penerima Manfaat",
    dampak_penyaluran: "Dampak Penyaluran",
    evaluasi_pelaksanaan: "Evaluasi Pelaksanaan",
    // BDS-BMB
    objek_supervisi: "Objek Supervisi",
    instansi_pemohon: "Instansi Pemohon",
    permasalahan_konsultasi: "Permasalahan Konsultasi",
    stakeholder_difasilitasi: "Stakeholder Difasilitasi",
    topik_fasilitasi: "Topik Fasilitasi",
    hasil_fasilitasi: "Hasil Fasilitasi",
    // BDS-EVL
    jenis_evaluasi: "Jenis Evaluasi",
    judul_evaluasi: "Judul Evaluasi",
    objek_evaluasi: "Objek Evaluasi",
    tujuan_evaluasi: "Tujuan Evaluasi",
    metode_evaluasi: "Metode Evaluasi",
    tim_evaluasi: "Tim Evaluasi",
    tanggal_evaluasi: "Tanggal Evaluasi",
    lokasi_evaluasi: "Lokasi Evaluasi",
    program_dievaluasi: "Program Dievaluasi",
    target_program: "Target Program",
    realisasi_program: "Realisasi Program",
    temuan_evaluasi: "Temuan Evaluasi",
    // BDS-LAP
    ringkasan_eksekutif: "Ringkasan Eksekutif",
    capaian_distribusi: "Capaian Distribusi",
    capaian_stabilisasi_harga: "Capaian Stabilisasi Harga",
    capaian_cppd: "Capaian CPPD",
    target_inflasi: "Target Inflasi (%)",
    volume_distribusi_total: "Volume Distribusi Total",
    stok_cppd: "Stok CPPD",
    operasi_pasar_dilakukan: "Operasi Pasar Dilakukan",
    rapat_tpid_dilakukan: "Rapat TPID Dilakukan",
    // BKT-KBJ
    jenis_kebijakan: "Jenis Kebijakan",
    nomor_dokumen: "Nomor Dokumen",
    tanggal_dokumen: "Tanggal Dokumen",
    periode_analisis: "Periode Analisis",
    judul_kebijakan: "Judul Kebijakan",
    latar_belakang: "Latar Belakang",
    analisis_situasi: "Analisis Situasi",
    permasalahan: "Permasalahan",
    opsi_solusi: "Opsi Solusi",
    komoditas_strategis: "Komoditas Strategis",
    target_pencapaian: "Target Pencapaian",
    indikator_keberhasilan: "Indikator Keberhasilan",
    instansi_terkait: "Instansi Terkait",
    koordinasi_dengan: "Koordinasi Dengan",
    hasil_sinkronisasi: "Hasil Sinkronisasi",
    // BKT-KRW
    jenis_kerawanan: "Jenis Kerawanan",
    kecamatan: "Kecamatan",
    desa: "Desa",
    latitude: "Latitude",
    longitude: "Longitude",
    tingkat_kerawanan: "Tingkat Kerawanan",
    skor_kerawanan: "Skor Kerawanan",
    jumlah_penduduk: "Jumlah Penduduk",
    jumlah_kk: "Jumlah KK",
    jumlah_kk_miskin: "Jumlah KK Miskin",
    persentase_kemiskinan: "Persentase Kemiskinan (%)",
    status_ketersediaan: "Status Ketersediaan",
    penyebab_kerawanan: "Penyebab Kerawanan",
    dampak_kerawanan: "Dampak Kerawanan",
    rencana_aksi: "Rencana Aksi",
    target_intervensi: "Target Intervensi",
    waktu_pelaksanaan: "Waktu Pelaksanaan",
    anggaran_kebutuhan: "Anggaran Kebutuhan",
    hasil_koordinasi: "Hasil Koordinasi",
    tindak_lanjut_koordinasi: "Tindak Lanjut Koordinasi",
    // BKT-MEV
    jenis_monev: "Jenis Monev",
    judul_laporan: "Judul Laporan",
    objek_monev: "Objek Monev",
    lokasi_monev: "Lokasi Monev",
    tanggal_monev: "Tanggal Monev",
    metode_monev: "Metode Monev",
    tim_monev: "Tim Monev",
    program_yang_dimonev: "Program yang Dimonev",
    target_kinerja: "Target Kinerja",
    realisasi_kinerja: "Realisasi Kinerja",
    persentase_capaian: "Persentase Capaian (%)",
    indikator_kinerja: "Indikator Kinerja",
    temuan_monev: "Temuan Monev",
    analisis_capaian: "Analisis Capaian",
    best_practice: "Best Practice",
    lesson_learned: "Lesson Learned",
    data_sakip_ikk: "Data SAKIP IKK",
    anggaran_program: "Anggaran Program",
    realisasi_anggaran: "Realisasi Anggaran",
    persentase_serapan: "Persentase Serapan (%)",
    output_program: "Output Program",
    outcome_program: "Outcome Program",
    dampak_program: "Dampak Program",
    ditujukan_kepada: "Ditujukan Kepada",
    // BKT-PGD
    jenis_pengendalian: "Jenis Pengendalian",
    bulan: "Bulan",
    target_produksi: "Target Produksi (Ton)",
    pasokan_lokal: "Pasokan Lokal",
    pasokan_luar_daerah: "Pasokan Luar Daerah",
    pasokan_impor: "Pasokan Impor",
    total_pasokan: "Total Pasokan",
    konsumsi_estimasi: "Estimasi Konsumsi",
    stok_awal: "Stok Awal",
    stok_akhir: "Stok Akhir",
    surplus_defisit: "Surplus/Defisit",
    early_warning_status: "Status Early Warning",
    indikator_early_warning: "Indikator Early Warning",
    rekomendasi_ews: "Rekomendasi EWS",
    neraca_pangan_ketersediaan: "Neraca Pangan (Ketersediaan)",
    neraca_pangan_penggunaan: "Neraca Pangan (Penggunaan)",
    sumber_data: "Sumber Data",
    metode_pengumpulan: "Metode Pengumpulan",
    validitas_data: "Validitas Data",
    analisis: "Analisis",
    rekomendasi: "Rekomendasi",
  };

  return (
    labels[key] ||
    key
      .split("_")
      .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
      .join(" ")
  );
}

function formatValue(key, value) {
  if (value === null || value === undefined || value === "") return "-";

  if (typeof value === "boolean") {
    return value ? "Ya" : "Tidak";
  }

  if (Array.isArray(value)) {
    return value.length
      ? value
          .map((item) =>
            typeof item === "string" ? item : JSON.stringify(item),
          )
          .join(", ")
      : "-";
  }

  if (typeof value === "object") {
    return JSON.stringify(value);
  }

  // Date fields
  if (key.includes("tanggal") || key === "periode" || key.includes("_at")) {
    return formatDate(value);
  }

  if (key.includes("waktu_")) {
    return String(value).slice(0, 5);
  }

  // Currency
  if (
    [
      "harga",
      "harga_bulan_lalu",
      "perubahan_harga",
      "nilai_bantuan",
      "biaya_kegiatan",
      "anggaran_kebutuhan",
      "anggaran_program",
      "realisasi_anggaran",
      "harga_pasar_normal",
      "harga_operasi_pasar",
      "subsidi_per_unit",
      "total_nilai_subsidi",
      "kebutuhan_cppd",
      "target_stok",
      "kapasitas_gudang",
      "rencana_pengadaan",
      "volume_pengadaan",
      "harga_satuan",
      "total_nilai",
      "volume_penyaluran",
      "gaji_pokok",
      "total_tunjangan",
      "pagu_anggaran",
      "realisasi",
      "sisa_anggaran",
      "jumlah_pencairan",
      "harga_perolehan",
      "nilai_buku",
      "biaya_pemeliharaan",
    ].includes(key)
  ) {
    return new Intl.NumberFormat("id-ID", {
      style: "currency",
      currency: "IDR",
      minimumFractionDigits: 0,
    }).format(value);
  }

  // Number
  if (
    key.includes("luas_") ||
    key.includes("pasokan_") ||
    key.includes("stok_") ||
    key.includes("neraca_") ||
    [
      "produksi",
      "produksi_total",
      "target_produksi",
      "produktivitas",
      "jumlah_penerima",
      "volume_bantuan",
      "jumlah_peserta",
      "frekuensi_pendampingan",
      "jumlah_penduduk",
      "jumlah_kk",
      "jumlah_kk_miskin",
      "konsumsi_estimasi",
      "surplus_defisit",
      "total_pasokan",
      "volume_distribusi",
      "stok_pasar",
      "stok_normal",
      "jumlah_pembeli",
      "persentase_perubahan",
      "inflasi_pangan",
      "target_inflasi_tpid",
      "target_inflasi",
      "persentase_terhadap_target",
      "suhu_gudang",
      "kelembaban_gudang",
      "jumlah_penerima_manfaat",
      "jumlah_foto",
      "jumlah_video",
      "persentase_capaian",
      "lama_cuti",
      "nilai_skp",
      "data_sakip_capaian",
      "data_sakip_target",
      "persentase_serapan",
      "volume_distribusi_total",
      "stok_cppd",
      "operasi_pasar_dilakukan",
      "rapat_tpid_dilakukan",
      "tahun_anggaran",
      "tahun_perolehan",
      "persentase_realisasi",
    ].includes(key)
  ) {
    return new Intl.NumberFormat("id-ID", {
      minimumFractionDigits: 0,
      maximumFractionDigits: 2,
    }).format(value);
  }

  // Status badge
  if (
    [
      "status",
      "tren_harga",
      "is_sensitive",
      "status_ketersediaan",
      "tingkat_kerawanan",
      "early_warning_status",
      "status_stok",
      "status_penanganan",
      "status_penyaluran",
      "status_inflasi",
      "status_spj",
      "status_aset",
      "kondisi",
    ].includes(key)
  ) {
    const colors = {
      draft: "bg-gray-100 text-gray-800",
      pending: "bg-yellow-100 text-yellow-800",
      persiapan: "bg-sky-100 text-sky-800",
      berlangsung: "bg-indigo-100 text-indigo-800",
      proses: "bg-yellow-100 text-yellow-800",
      diverifikasi: "bg-blue-100 text-blue-800",
      review: "bg-blue-100 text-blue-800",
      selesai: "bg-green-100 text-green-800",
      ditolak: "bg-red-100 text-red-800",
      arsip: "bg-gray-200 text-gray-800",
      final: "bg-green-100 text-green-800",
      publish: "bg-emerald-100 text-emerald-800",
      approved: "bg-emerald-100 text-emerald-800",
      finalisasi: "bg-purple-100 text-purple-800",
      disetujui: "bg-emerald-100 text-emerald-800",
      Naik: "bg-red-100 text-red-800",
      Turun: "bg-green-100 text-green-800",
      Stabil: "bg-blue-100 text-blue-800",
      perencanaan: "bg-gray-100 text-gray-800",
      pelaksanaan: "bg-blue-100 text-blue-800",
      Biasa: "bg-slate-100 text-slate-800",
      Sensitif: "bg-rose-100 text-rose-800",
      Surplus: "bg-blue-100 text-blue-800",
      Aman: "bg-green-100 text-green-800",
      Menipis: "bg-orange-100 text-orange-800",
      Defisit: "bg-red-100 text-red-800",
      Kritis: "bg-red-100 text-red-800",
      Waspada: "bg-yellow-100 text-yellow-800",
      Rawan: "bg-orange-100 text-orange-800",
      "Sangat Rawan": "bg-red-100 text-red-800",
      "Belum Ditangani": "bg-red-100 text-red-800",
      "Dalam Proses": "bg-yellow-100 text-yellow-800",
      "Belum SPJ": "bg-orange-100 text-orange-800",
      "SPJ Lengkap": "bg-green-100 text-green-800",
      "SPJ Kurang": "bg-yellow-100 text-yellow-800",
      Diverifikasi: "bg-blue-100 text-blue-800",
      Ditolak: "bg-red-100 text-red-800",
      Aktif: "bg-green-100 text-green-800",
      "Tidak Digunakan": "bg-slate-100 text-slate-800",
      Rusak: "bg-red-100 text-red-800",
      "Dalam Perbaikan": "bg-yellow-100 text-yellow-800",
      "Akan Dihapus": "bg-orange-100 text-orange-800",
      Dihapuskan: "bg-gray-300 text-gray-800",
      Baik: "bg-green-100 text-green-800",
      "Rusak Ringan": "bg-yellow-100 text-yellow-800",
      "Rusak Berat": "bg-red-100 text-red-800",
      Perencanaan: "bg-gray-100 text-gray-800",
      Proses: "bg-blue-100 text-blue-800",
      Selesai: "bg-green-100 text-green-800",
      "On Target": "bg-green-100 text-green-800",
      Warning: "bg-yellow-100 text-yellow-800",
      Alert: "bg-red-100 text-red-800",
      Normal: "bg-green-100 text-green-800",
      Siaga: "bg-orange-100 text-orange-800",
      Darurat: "bg-red-100 text-red-800",
      "Prioritas 1": "bg-red-100 text-red-800",
      "Prioritas 2": "bg-red-100 text-red-800",
      "Prioritas 3": "bg-orange-100 text-orange-800",
      "Prioritas 4": "bg-yellow-100 text-yellow-800",
      "Prioritas 5": "bg-blue-100 text-blue-800",
      "Prioritas 6": "bg-green-100 text-green-800",
    };
    const colorClass = colors[value] || "bg-gray-100 text-gray-800";
    return (
      <span
        className={`inline-block px-3 py-1 text-sm font-medium rounded-full ${colorClass}`}
      >
        {value}
      </span>
    );
  }

  return String(value);
}

function formatDate(dateString) {
  if (!dateString) return "-";
  return new Date(dateString).toLocaleDateString("id-ID", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function getDetailEntries(moduleId, data) {
  const hiddenKeys = new Set([
    "id",
    "created_by",
    "updated_by",
    "created_at",
    "updated_at",
  ]);

  const orderedKeys = {
    "sek-adm": [
      "unit_kerja",
      "layanan_id",
      "nomor_surat",
      "jenis_naskah",
      "tanggal_surat",
      "pengirim_penerima",
      "perihal",
      "isi_ringkas",
      "disposisi",
      "ditujukan_kepada",
      "arsip_code",
      "is_rahasia",
      "penanggung_jawab",
      "pelaksana",
      "is_sensitive",
      "status",
      "keterangan",
    ],
    "sek-kep": [
      "unit_kerja",
      "layanan_id",
      "asn_id",
      "nip",
      "nama_asn",
      "jenis_layanan_kepegawaian",
      "pangkat_lama",
      "pangkat_baru",
      "golongan_lama",
      "golongan_baru",
      "jabatan_lama",
      "jabatan_baru",
      "tmt_kenaikan",
      "nomor_sk",
      "tanggal_sk",
      "jenis_cuti",
      "tanggal_mulai_cuti",
      "tanggal_selesai_cuti",
      "lama_cuti",
      "nilai_skp",
      "predikat_kinerja",
      "jenis_sanksi",
      "uraian_sanksi",
      "tanggal_pensiun",
      "jenis_pensiun",
      "gaji_pokok",
      "total_tunjangan",
      "file_sk",
      "file_pendukung",
      "penanggung_jawab",
      "pelaksana",
      "is_sensitive",
      "status",
      "keterangan",
    ],
    "sek-keu": [
      "unit_kerja",
      "kode_unit",
      "layanan_id",
      "tahun_anggaran",
      "jenis_layanan_keuangan",
      "nomor_dpa",
      "kode_rekening",
      "nama_rekening",
      "pagu_anggaran",
      "realisasi",
      "sisa_anggaran",
      "persentase_realisasi",
      "jenis_belanja",
      "uraian_belanja",
      "keperluan",
      "penerima_uang",
      "tanggal_pencairan",
      "jumlah_pencairan",
      "nomor_spj",
      "tanggal_spj",
      "status_spj",
      "jenis_revisi",
      "alasan_revisi",
      "file_dpa",
      "file_spj",
      "file_bukti",
      "file_laporan",
      "penanggung_jawab",
      "pelaksana",
      "is_sensitive",
      "status",
      "keterangan",
    ],
    "sek-rmh": [
      "unit_kerja",
      "layanan_id",
      "jenis_layanan_rumah_tangga",
      "nomor_sppd",
      "nomor_st",
      "nama_pegawai",
      "nip_pegawai",
      "tujuan",
      "keperluan",
      "tanggal_berangkat",
      "tanggal_kembali",
      "lama_hari",
      "biaya_transport",
      "biaya_penginapan",
      "uang_harian",
      "total_biaya",
      "area_kebersihan",
      "jadwal_kebersihan",
      "petugas_kebersihan",
      "pos_keamanan",
      "shift_keamanan",
      "petugas_keamanan",
      "jenis_fasilitas",
      "kondisi_fasilitas",
      "nama_ruang_rapat",
      "kapasitas",
      "tanggal_pemesanan",
      "jam_mulai",
      "jam_selesai",
      "pemesan",
      "nomor_polisi",
      "jenis_kendaraan",
      "driver",
      "tanggal_pakai",
      "km_awal",
      "km_akhir",
      "bbm_liter",
      "file_sppd",
      "file_laporan",
      "penanggung_jawab",
      "pelaksana",
      "is_sensitive",
      "status",
      "keterangan",
    ],
    "sek-ast": [
      "unit_kerja",
      "layanan_id",
      "kode_aset",
      "nama_aset",
      "kategori_aset",
      "merk_type",
      "nomor_seri",
      "tahun_perolehan",
      "cara_perolehan",
      "harga_perolehan",
      "nilai_buku",
      "kondisi",
      "lokasi",
      "ruangan",
      "penanggung_jawab_aset",
      "qr_code",
      "tanggal_inventarisasi",
      "tanggal_pemeliharaan_terakhir",
      "tanggal_pemeliharaan_berikutnya",
      "biaya_pemeliharaan",
      "jenis_pemeliharaan",
      "status_aset",
      "alasan_penghapusan",
      "tanggal_penghapusan",
      "nomor_sk_penghapusan",
      "file_foto",
      "file_bast",
      "file_sk",
      "penanggung_jawab",
      "pelaksana",
      "is_sensitive",
      "keterangan",
    ],
    "sek-hum": [
      "layanan_id",
      "jenis_layanan_humas",
      "nama_kegiatan",
      "jenis_acara",
      "tanggal_acara",
      "waktu_mulai",
      "waktu_selesai",
      "tempat",
      "pimpinan_hadir",
      "tamu_vip",
      "jumlah_peserta",
      "rundown_acara",
      "mc",
      "protokoler",
      "nama_tamu",
      "instansi_tamu",
      "keperluan_kunjungan",
      "penerima_tamu",
      "judul_publikasi",
      "jenis_publikasi",
      "media_publikasi",
      "link_publikasi",
      "isi_publikasi",
      "fotografer",
      "videografer",
      "jumlah_foto",
      "jumlah_video",
      "file_foto",
      "file_video",
      "file_rundown",
      "file_undangan",
      "penanggung_jawab",
      "pelaksana",
      "is_sensitive",
      "status",
      "keterangan",
    ],
    "sek-kbj": [
      "layanan_id",
      "jenis_layanan_kebijakan",
      "judul",
      "periode",
      "tahun",
      "ruang_lingkup",
      "latar_belakang",
      "permasalahan",
      "analisis",
      "opsi_kebijakan",
      "rekomendasi_kebijakan",
      "dampak",
      "dasar_hukum",
      "sumber_data_bidang_ketersediaan",
      "sumber_data_bidang_distribusi",
      "sumber_data_bidang_konsumsi",
      "sumber_data_uptd",
      "rekapitulasi_keuangan",
      "rekapitulasi_program",
      "rekapitulasi_capaian",
      "kesimpulan",
      "tindak_lanjut",
      "file_dokumen",
      "file_lampiran",
      "ditujukan_kepada",
      "penanggung_jawab",
      "pelaksana",
      "is_sensitive",
      "status",
      "keterangan",
    ],
    "bds-hrg": [
      "unit_kerja",
      "layanan_id",
      "jenis_layanan_harga",
      "periode",
      "tahun",
      "bulan",
      "nama_komoditas",
      "nama_pasar",
      "tanggal_pantau",
      "harga",
      "satuan",
      "tren_harga",
      "tingkat_fluktuasi",
      "analisis_harga",
      "prediksi_harga",
      "rekomendasi_stabilisasi",
      "inflasi_pangan",
      "target_inflasi_tpid",
      "status_inflasi",
      "penanggung_jawab",
      "pelaksana",
      "is_sensitive",
      "reported_to_sekretariat",
      "reported_at",
      "sekretariat_notes",
      "status",
      "keterangan",
    ],
    "bds-kbj": [
      "unit_kerja",
      "layanan_id",
      "jenis_kebijakan",
      "nomor_dokumen",
      "tanggal_dokumen",
      "tahun",
      "judul_kebijakan",
      "latar_belakang",
      "tujuan",
      "sasaran",
      "wilayah_distribusi",
      "jalur_distribusi_utama",
      "strategi_distribusi",
      "koordinasi_dengan",
      "rekomendasi",
      "tindak_lanjut",
      "penanggung_jawab",
      "pelaksana",
      "is_sensitive",
      "reported_to_sekretariat",
      "reported_at",
      "sekretariat_notes",
      "status",
      "keterangan",
    ],
    "bds-mon": [
      "unit_kerja",
      "layanan_id",
      "jenis_monitoring",
      "periode",
      "tahun",
      "bulan",
      "nama_komoditas",
      "wilayah_asal",
      "wilayah_tujuan",
      "volume_distribusi",
      "nama_pasar",
      "stok_pasar",
      "status_stok",
      "jenis_hambatan",
      "tingkat_hambatan",
      "status_penanganan",
      "rekomendasi",
      "penanggung_jawab",
      "pelaksana",
      "is_sensitive",
      "reported_to_sekretariat",
      "reported_at",
      "sekretariat_notes",
      "status",
      "keterangan",
    ],
    "bds-cpd": [
      "unit_kerja",
      "layanan_id",
      "jenis_layanan_cppd",
      "periode",
      "tahun",
      "bulan",
      "nama_komoditas",
      "kebutuhan_cppd",
      "target_stok",
      "stok_akhir_bulan",
      "status_stok",
      "jenis_penyaluran",
      "wilayah_penyaluran",
      "volume_penyaluran",
      "status_penyaluran",
      "penanggung_jawab",
      "pelaksana",
      "is_sensitive",
      "reported_to_sekretariat",
      "reported_at",
      "sekretariat_notes",
      "status",
      "keterangan",
    ],
    "bds-bmb": [
      "unit_kerja",
      "layanan_id",
      "jenis_bimbingan",
      "nama_kegiatan",
      "tanggal_kegiatan",
      "waktu_mulai",
      "waktu_selesai",
      "tempat",
      "kabupaten",
      "sasaran_peserta",
      "jumlah_peserta",
      "narasumber",
      "fasilitator",
      "metode_pelaksanaan",
      "materi_bimbingan",
      "topik_pemetaan",
      "hasil_pemetaan",
      "area_supervisi",
      "temuan_supervisi",
      "rekomendasi_supervisi",
      "topik_konsultasi",
      "pemohon_konsultasi",
      "jawaban_konsultasi",
      "durasi_pendampingan",
      "frekuensi_pendampingan",
      "output_kegiatan",
      "outcome_kegiatan",
      "evaluasi_kegiatan",
      "tindak_lanjut",
      "biaya_kegiatan",
      "sumber_anggaran",
      "hasil_fasilitasi",
      "penanggung_jawab",
      "pelaksana",
      "is_sensitive",
      "reported_to_sekretariat",
      "reported_at",
      "sekretariat_notes",
      "status",
      "keterangan",
    ],
    "bds-evl": [
      "unit_kerja",
      "layanan_id",
      "jenis_evaluasi",
      "periode",
      "tahun",
      "bulan",
      "judul_evaluasi",
      "objek_evaluasi",
      "metode_evaluasi",
      "persentase_capaian",
      "temuan_evaluasi",
      "rekomendasi",
      "tindak_lanjut",
      "penanggung_jawab",
      "pelaksana",
      "is_sensitive",
      "reported_to_sekretariat",
      "reported_at",
      "sekretariat_notes",
      "status",
      "keterangan",
    ],
    "bds-lap": [
      "unit_kerja",
      "layanan_id",
      "periode",
      "tahun",
      "bulan",
      "judul_laporan",
      "ringkasan_eksekutif",
      "inflasi_pangan",
      "target_inflasi",
      "status_inflasi",
      "volume_distribusi_total",
      "stok_cppd",
      "operasi_pasar_dilakukan",
      "rapat_tpid_dilakukan",
      "permasalahan",
      "rekomendasi",
      "tindak_lanjut",
      "penanggung_jawab",
      "pelaksana",
      "is_sensitive",
      "reported_to_sekretariat",
      "reported_at",
      "sekretariat_notes",
      "status",
      "keterangan",
    ],
    "bkt-pgd": [
      "unit_kerja",
      "layanan_id",
      "jenis_pengendalian",
      "nama_komoditas",
      "kabupaten",
      "kecamatan",
      "periode",
      "tahun",
      "bulan",
      "luas_tanam",
      "luas_panen",
      "produktivitas",
      "produksi_total",
      "target_produksi",
      "pasokan_lokal",
      "pasokan_luar_daerah",
      "pasokan_impor",
      "total_pasokan",
      "konsumsi_estimasi",
      "stok_awal",
      "stok_akhir",
      "surplus_defisit",
      "status_ketersediaan",
      "early_warning_status",
      "indikator_early_warning",
      "rekomendasi_ews",
      "analisis",
      "kendala",
      "rekomendasi",
      "penanggung_jawab",
      "pelaksana",
      "is_sensitive",
      "reported_to_sekretariat",
      "reported_at",
      "sekretariat_notes",
      "status",
      "keterangan",
    ],
    "bkt-kbj": [
      "unit_kerja",
      "layanan_id",
      "jenis_kebijakan",
      "nomor_dokumen",
      "tanggal_dokumen",
      "tahun",
      "judul_kebijakan",
      "latar_belakang",
      "rekomendasi",
      "target_pencapaian",
      "instansi_terkait",
      "koordinasi_dengan",
      "tindak_lanjut",
      "penanggung_jawab",
      "pelaksana",
      "is_sensitive",
      "reported_to_sekretariat",
      "reported_at",
      "sekretariat_notes",
      "status",
      "keterangan",
    ],
    "bkt-krw": [
      "unit_kerja",
      "layanan_id",
      "jenis_kerawanan",
      "periode",
      "tahun",
      "kabupaten",
      "kecamatan",
      "desa",
      "tingkat_kerawanan",
      "status_ketersediaan",
      "jumlah_penduduk",
      "jumlah_kk",
      "jumlah_kk_miskin",
      "penyebab_kerawanan",
      "dampak_kerawanan",
      "rencana_aksi",
      "target_intervensi",
      "anggaran_kebutuhan",
      "sumber_anggaran",
      "instansi_terkait",
      "tindak_lanjut_koordinasi",
      "penanggung_jawab",
      "pelaksana",
      "is_sensitive",
      "reported_to_sekretariat",
      "reported_at",
      "sekretariat_notes",
      "status",
      "keterangan",
    ],
    "bkt-mev": [
      "unit_kerja",
      "layanan_id",
      "jenis_monev",
      "periode",
      "tahun",
      "bulan",
      "judul_laporan",
      "objek_monev",
      "lokasi_monev",
      "tanggal_monev",
      "metode_monev",
      "program_yang_dimonev",
      "target_kinerja",
      "realisasi_kinerja",
      "persentase_capaian",
      "temuan_monev",
      "permasalahan",
      "rekomendasi",
      "tindak_lanjut",
      "ditujukan_kepada",
      "penanggung_jawab",
      "pelaksana",
      "is_sensitive",
      "reported_to_sekretariat",
      "reported_at",
      "sekretariat_notes",
      "status",
      "keterangan",
    ],
    "bkt-fsl": [
      "unit_kerja",
      "layanan_id",
      "jenis_fasilitasi",
      "nama_program",
      "periode",
      "tahun",
      "wilayah_sasaran",
      "kelompok_sasaran",
      "jumlah_penerima",
      "jenis_intervensi",
      "volume_bantuan",
      "satuan",
      "nilai_bantuan",
      "sumber_bantuan",
      "instansi_pemberi",
      "tanggal_penyaluran",
      "lokasi_penyaluran",
      "penanggung_jawab_penyaluran",
      "target_output",
      "target_outcome",
      "realisasi",
      "kendala",
      "solusi",
      "dampak",
      "penanggung_jawab",
      "pelaksana",
      "is_sensitive",
      "reported_to_sekretariat",
      "reported_at",
      "sekretariat_notes",
      "status",
      "keterangan",
    ],
    "bkt-bmb": [
      "unit_kerja",
      "layanan_id",
      "jenis_bimbingan",
      "nama_kegiatan",
      "tanggal_kegiatan",
      "waktu_mulai",
      "waktu_selesai",
      "tempat",
      "kabupaten",
      "sasaran_peserta",
      "jumlah_peserta",
      "narasumber",
      "fasilitator",
      "materi_bimbingan",
      "metode_pelaksanaan",
      "topik_pemetaan",
      "hasil_pemetaan",
      "area_supervisi",
      "temuan_supervisi",
      "rekomendasi_supervisi",
      "topik_konsultasi",
      "pemohon_konsultasi",
      "jawaban_konsultasi",
      "durasi_pendampingan",
      "frekuensi_pendampingan",
      "output_kegiatan",
      "outcome_kegiatan",
      "evaluasi_kegiatan",
      "tindak_lanjut",
      "biaya_kegiatan",
      "sumber_anggaran",
      "penanggung_jawab",
      "pelaksana",
      "is_sensitive",
      "reported_to_sekretariat",
      "reported_at",
      "sekretariat_notes",
      "status",
      "keterangan",
    ],
  };

  const preferredKeys = orderedKeys[moduleId];
  if (!preferredKeys) {
    return Object.entries(data).filter(([key]) => !hiddenKeys.has(key));
  }

  const orderedEntries = preferredKeys
    .filter((key) => Object.prototype.hasOwnProperty.call(data, key))
    .map((key) => [key, data[key]]);

  const remainingEntries = Object.entries(data).filter(
    ([key]) => !hiddenKeys.has(key) && !preferredKeys.includes(key),
  );

  return [...orderedEntries, ...remainingEntries];
}
