export const fields = [
  {
    "field_name": "id",
    "field_label": "ID",
    "field_type": "auto_increment",
    "field_length": "11",
    "is_required": "true",
    "is_unique": "true",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Primary Key"
  },
  {
    "field_name": "layanan_id",
    "field_label": "Layanan",
    "field_type": "varchar",
    "field_length": "10",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "FK ke layanan_menpanrb (LY007",
    "__parsed_extra": [
      "LY030-LY034)"
    ]
  },
  {
    "field_name": "jenis_layanan_rumah_tangga",
    "field_label": "Jenis Layanan",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Perjalanan Dinas,Kebersihan,Keamanan,Fasilitas,Ruang Rapat,Kendaraan",
    "help_text": "Jenis layanan RT"
  },
  {
    "field_name": "nomor_sppd",
    "field_label": "Nomor SPPD",
    "field_type": "varchar",
    "field_length": "100",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Untuk perjalanan dinas"
  },
  {
    "field_name": "nomor_st",
    "field_label": "Nomor ST",
    "field_type": "varchar",
    "field_length": "100",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Nomor Surat Tugas"
  },
  {
    "field_name": "nama_pegawai",
    "field_label": "Nama Pegawai",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Yang perjalanan dinas"
  },
  {
    "field_name": "nip_pegawai",
    "field_label": "NIP",
    "field_type": "varchar",
    "field_length": "18",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "NIP pegawai"
  },
  {
    "field_name": "tujuan",
    "field_label": "Tujuan",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tujuan perjalanan"
  },
  {
    "field_name": "keperluan",
    "field_label": "Keperluan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Keperluan perjalanan"
  },
  {
    "field_name": "tanggal_berangkat",
    "field_label": "Tanggal Berangkat",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Berangkat"
  },
  {
    "field_name": "tanggal_kembali",
    "field_label": "Tanggal Kembali",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Kembali"
  },
  {
    "field_name": "lama_hari",
    "field_label": "Lama Hari",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Jumlah hari"
  },
  {
    "field_name": "biaya_transport",
    "field_label": "Biaya Transport",
    "field_type": "decimal",
    "field_length": "15,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Biaya transportasi"
  },
  {
    "field_name": "biaya_penginapan",
    "field_label": "Biaya Penginapan",
    "field_type": "decimal",
    "field_length": "15,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Biaya hotel"
  },
  {
    "field_name": "uang_harian",
    "field_label": "Uang Harian",
    "field_type": "decimal",
    "field_length": "15,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Per hari"
  },
  {
    "field_name": "total_biaya",
    "field_label": "Total Biaya",
    "field_type": "decimal",
    "field_length": "15,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Total perjalanan dinas"
  },
  {
    "field_name": "area_kebersihan",
    "field_label": "Area Kebersihan",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Area yang dibersihkan"
  },
  {
    "field_name": "jadwal_kebersihan",
    "field_label": "Jadwal",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Harian,Mingguan,Bulanan",
    "help_text": "Jadwal kebersihan"
  },
  {
    "field_name": "petugas_kebersihan",
    "field_label": "Petugas",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Petugas cleaning"
  },
  {
    "field_name": "pos_keamanan",
    "field_label": "Pos Keamanan",
    "field_type": "varchar",
    "field_length": "100",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Pos security"
  },
  {
    "field_name": "shift_keamanan",
    "field_label": "Shift",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Pagi,Siang,Malam",
    "help_text": "Shift keamanan"
  },
  {
    "field_name": "petugas_keamanan",
    "field_label": "Petugas Keamanan",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Nama security"
  },
  {
    "field_name": "jenis_fasilitas",
    "field_label": "Jenis Fasilitas",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "AC printer dll"
  },
  {
    "field_name": "kondisi_fasilitas",
    "field_label": "Kondisi",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "Baik",
    "validation": "none",
    "dropdown_options": "Baik,Rusak,Perlu Perbaikan",
    "help_text": "Kondisi fasilitas"
  },
  {
    "field_name": "nama_ruang_rapat",
    "field_label": "Nama Ruang Rapat",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Ruang rapat A/B/C"
  },
  {
    "field_name": "kapasitas",
    "field_label": "Kapasitas",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Kapasitas orang"
  },
  {
    "field_name": "tanggal_pemesanan",
    "field_label": "Tanggal Pemesanan",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Booking ruang rapat"
  },
  {
    "field_name": "jam_mulai",
    "field_label": "Jam Mulai",
    "field_type": "time",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Jam mulai pakai"
  },
  {
    "field_name": "jam_selesai",
    "field_label": "Jam Selesai",
    "field_type": "time",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Jam selesai pakai"
  },
  {
    "field_name": "pemesan",
    "field_label": "Pemesan",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Yang memesan"
  },
  {
    "field_name": "nomor_polisi",
    "field_label": "Nomor Polisi",
    "field_type": "varchar",
    "field_length": "20",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Kendaraan dinas"
  },
  {
    "field_name": "jenis_kendaraan",
    "field_label": "Jenis Kendaraan",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Mobil Dinas,Motor Dinas,Mobil Operasional",
    "help_text": "Jenis kendaraan"
  },
  {
    "field_name": "driver",
    "field_label": "Driver",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Nama driver"
  },
  {
    "field_name": "tanggal_pakai",
    "field_label": "Tanggal Pakai",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tanggal kendaraan dipakai"
  },
  {
    "field_name": "km_awal",
    "field_label": "KM Awal",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Odometer awal"
  },
  {
    "field_name": "km_akhir",
    "field_label": "KM Akhir",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Odometer akhir"
  },
  {
    "field_name": "bbm_liter",
    "field_label": "BBM (Liter)",
    "field_type": "decimal",
    "field_length": "10,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Pengisian BBM"
  },
  {
    "field_name": "file_sppd",
    "field_label": "File SPPD",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Upload SPPD"
  },
  {
    "field_name": "file_laporan",
    "field_label": "File Laporan",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Laporan perjalanan dinas"
  },
  {
    "field_name": "penanggung_jawab",
    "field_label": "Penanggung Jawab",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "Kasubbag Umum",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "PIC"
  },
  {
    "field_name": "pelaksana",
    "field_label": "Pelaksana",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Yang melaksanakan"
  },
  {
    "field_name": "is_sensitive",
    "field_label": "Tingkat Sensitivitas",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "Biasa",
    "validation": "none",
    "dropdown_options": "Biasa,Sensitif",
    "help_text": "Klasifikasi (perjalanan dinas = sensitif)"
  },
  {
    "field_name": "status",
    "field_label": "Status",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "pending",
    "validation": "none",
    "dropdown_options": "pending,disetujui,ditolak,selesai",
    "help_text": "Status"
  },
  {
    "field_name": "keterangan",
    "field_label": "Keterangan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Catatan"
  },
  {
    "field_name": "created_by",
    "field_label": "Dibuat Oleh",
    "field_type": "int",
    "field_length": "11",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "User ID"
  },
  {
    "field_name": "created_at",
    "field_label": "Dibuat Pada",
    "field_type": "timestamp",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "CURRENT_TIMESTAMP",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": ""
  },
  {
    "field_name": "updated_at",
    "field_label": "Diperbarui Pada",
    "field_type": "timestamp",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "CURRENT_TIMESTAMP",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": ""
  }
];
