export const fields = [
  {
    "field_name": "id",
    "field_label": "ID",
    "field_type": "auto_increment",
    "field_length": "11",
    "is_required": "true",
    "is_unique": "true",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Primary Key"
  },
  {
    "field_name": "unit_kerja",
    "field_label": "Unit Kerja",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Sekretariat,UPTD,Bidang Ketersediaan,Bidang Distribusi,Bidang Konsumsi",
    "help_text": "Unit yang input data (AUTO-SET sesuai bidang)"
  },
  {
    "field_name": "reported_to_sekretariat",
    "field_label": "Dilaporkan ke Sekretariat",
    "field_type": "boolean",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "0",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Sudah dilaporkan ke Sekretariat untuk konsolidasi"
  },
  {
    "field_name": "reported_at",
    "field_label": "Tanggal Lapor ke Sekretariat",
    "field_type": "timestamp",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Kapan dilaporkan ke Sekretariat"
  },
  {
    "field_name": "sekretariat_notes",
    "field_label": "Catatan Sekretariat",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Catatan dari Sekretaris saat review/konsolidasi"
  },
  {
    "field_name": "layanan_id",
    "field_label": "Layanan",
    "field_type": "varchar",
    "field_length": "10",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "LY066",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "FK ke layanan_menpanrb"
  },
  {
    "field_name": "jenis_fasilitasi",
    "field_label": "Jenis Fasilitasi",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Intervensi Produksi,Intervensi Distribusi,Intervensi Konsumsi,Bantuan Pangan,Lainnya",
    "help_text": "Jenis fasilitasi"
  },
  {
    "field_name": "nama_program",
    "field_label": "Nama Program",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Nama program intervensi"
  },
  {
    "field_name": "periode",
    "field_label": "Periode",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Periode pelaksanaan"
  },
  {
    "field_name": "tahun",
    "field_label": "Tahun",
    "field_type": "int",
    "field_length": "4",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Tahun"
  },
  {
    "field_name": "wilayah_sasaran",
    "field_label": "Wilayah Sasaran",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Kabupaten/kecamatan sasaran"
  },
  {
    "field_name": "kelompok_sasaran",
    "field_label": "Kelompok Sasaran",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Petani/nelayan/masyarakat"
  },
  {
    "field_name": "jumlah_penerima",
    "field_label": "Jumlah Penerima",
    "field_type": "int",
    "field_length": "11",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Total penerima manfaat"
  },
  {
    "field_name": "jenis_intervensi",
    "field_label": "Jenis Intervensi",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "Bantuan Benih,Bantuan Pupuk,Bantuan Alat,Bantuan Pangan,Pelatihan,Pendampingan,Lainnya",
    "help_text": "Jenis intervensi"
  },
  {
    "field_name": "volume_bantuan",
    "field_label": "Volume Bantuan",
    "field_type": "decimal",
    "field_length": "15,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Volume bantuan"
  },
  {
    "field_name": "satuan",
    "field_label": "Satuan",
    "field_type": "varchar",
    "field_length": "50",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Satuan (kg ton unit dll)"
  },
  {
    "field_name": "nilai_bantuan",
    "field_label": "Nilai Bantuan",
    "field_type": "decimal",
    "field_length": "15,2",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Nilai dalam rupiah"
  },
  {
    "field_name": "sumber_bantuan",
    "field_label": "Sumber Bantuan",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "APBN/APBD/Donor/Lainnya"
  },
  {
    "field_name": "instansi_pemberi",
    "field_label": "Instansi Pemberi",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Instansi pemberi bantuan"
  },
  {
    "field_name": "tanggal_penyaluran",
    "field_label": "Tanggal Penyaluran",
    "field_type": "date",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Kapan disalurkan"
  },
  {
    "field_name": "lokasi_penyaluran",
    "field_label": "Lokasi Penyaluran",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Dimana disalurkan"
  },
  {
    "field_name": "penanggung_jawab_penyaluran",
    "field_label": "PJ Penyaluran",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "PIC penyaluran"
  },
  {
    "field_name": "target_output",
    "field_label": "Target Output",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Output yang diharapkan"
  },
  {
    "field_name": "target_outcome",
    "field_label": "Target Outcome",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Outcome yang diharapkan"
  },
  {
    "field_name": "realisasi",
    "field_label": "Realisasi",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Realisasi pelaksanaan"
  },
  {
    "field_name": "kendala",
    "field_label": "Kendala",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Kendala yang dihadapi"
  },
  {
    "field_name": "solusi",
    "field_label": "Solusi",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Solusi atas kendala"
  },
  {
    "field_name": "dampak",
    "field_label": "Dampak",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Dampak yang dirasakan"
  },
  {
    "field_name": "dokumentasi_kegiatan",
    "field_label": "Dokumentasi Kegiatan",
    "field_type": "json",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Array foto kegiatan"
  },
  {
    "field_name": "file_proposal",
    "field_label": "File Proposal",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Proposal program"
  },
  {
    "field_name": "file_bast",
    "field_label": "File BAST",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Berita Acara Serah Terima"
  },
  {
    "field_name": "file_laporan",
    "field_label": "File Laporan",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Laporan pelaksanaan"
  },
  {
    "field_name": "rincian_layanan",
    "field_label": "Rincian Layanan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Detail layanan"
  },
  {
    "field_name": "penanggung_jawab",
    "field_label": "Penanggung Jawab",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "Kepala Bidang Ketersediaan",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "PIC"
  },
  {
    "field_name": "pelaksana",
    "field_label": "Pelaksana",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Yang melaksanakan"
  },
  {
    "field_name": "kelompok_penerima",
    "field_label": "Kelompok Penerima",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Siapa yang terima"
  },
  {
    "field_name": "jenis_data",
    "field_label": "Jenis Data",
    "field_type": "varchar",
    "field_length": "255",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Jenis data"
  },
  {
    "field_name": "is_sensitive",
    "field_label": "Tingkat Sensitivitas",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "Biasa",
    "validation": "none",
    "dropdown_options": "Biasa,Sensitif",
    "help_text": "Data fasilitasi biasa"
  },
  {
    "field_name": "status",
    "field_label": "Status",
    "field_type": "enum",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "perencanaan",
    "validation": "none",
    "dropdown_options": "perencanaan,pelaksanaan,selesai",
    "help_text": "Status pelaksanaan"
  },
  {
    "field_name": "keterangan",
    "field_label": "Keterangan",
    "field_type": "text",
    "field_length": "NULL",
    "is_required": "false",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "Catatan"
  },
  {
    "field_name": "created_by",
    "field_label": "Dibuat Oleh",
    "field_type": "int",
    "field_length": "11",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "NULL",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": "User ID"
  },
  {
    "field_name": "created_at",
    "field_label": "Dibuat Pada",
    "field_type": "timestamp",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "CURRENT_TIMESTAMP",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": ""
  },
  {
    "field_name": "updated_at",
    "field_label": "Diperbarui Pada",
    "field_type": "timestamp",
    "field_length": "NULL",
    "is_required": "true",
    "is_unique": "false",
    "default_value": "CURRENT_TIMESTAMP",
    "validation": "none",
    "dropdown_options": "NULL",
    "help_text": ""
  }
];
